<?php

namespace DoctrineORMModule\Proxy\__CG__\Cache\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CacheEntity extends \Cache\Entity\CacheEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'idCache', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'noCache', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'dsCache', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'dsValor', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'idCliente');
        }

        return array('__isInitialized__', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'idCache', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'noCache', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'dsCache', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'dsValor', '' . "\0" . 'Cache\\Entity\\CacheEntity' . "\0" . 'idCliente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CacheEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCache()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCache();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCache', array());

        return parent::getIdCache();
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCache', array());

        return parent::getNoCache();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsCache()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsCache', array());

        return parent::getDsCache();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsValor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsValor', array());

        return parent::getDsValor();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCache($idCache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCache', array($idCache));

        return parent::setIdCache($idCache);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCache($noCache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCache', array($noCache));

        return parent::setNoCache($noCache);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsCache($dsCache)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsCache', array($dsCache));

        return parent::setDsCache($dsCache);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsValor($dsValor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsValor', array($dsValor));

        return parent::setDsValor($dsValor);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(\Cliente\Entity\ClienteEntity $idCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
