<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DadosCadastraisEntity extends \Usuario\Entity\DadosCadastraisEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'usuarios', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'idUsuario', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'dtNascimento', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'nome', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'nuCpf', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'sgUf', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'cidade', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'bairro', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'endereco', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'tel1', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'tel2', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'altura', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'peso', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'cep');
        }

        return array('__isInitialized__', 'usuarios', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'idUsuario', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'dtNascimento', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'nome', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'nuCpf', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'sgUf', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'cidade', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'bairro', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'endereco', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'tel1', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'tel2', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'altura', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'peso', '' . "\0" . 'Usuario\\Entity\\DadosCadastraisEntity' . "\0" . 'cep');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DadosCadastraisEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUsuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtNascimento', array());

        return parent::getDtNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getNuCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuCpf', array());

        return parent::getNuCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function getSgUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSgUf', array());

        return parent::getSgUf();
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', array());

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', array());

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', array());

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function getTel1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel1', array());

        return parent::getTel1();
    }

    /**
     * {@inheritDoc}
     */
    public function getTel2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel2', array());

        return parent::getTel2();
    }

    /**
     * {@inheritDoc}
     */
    public function getAltura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAltura', array());

        return parent::getAltura();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeso', array());

        return parent::getPeso();
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', array());

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtNascimento($dtNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtNascimento', array($dtNascimento));

        return parent::setDtNascimento($dtNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function setNuCpf($nuCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuCpf', array($nuCpf));

        return parent::setNuCpf($nuCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function setSgUf($sgUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSgUf', array($sgUf));

        return parent::setSgUf($sgUf);
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', array($cidade));

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', array($bairro));

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco($endereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', array($endereco));

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function setTel1($tel1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel1', array($tel1));

        return parent::setTel1($tel1);
    }

    /**
     * {@inheritDoc}
     */
    public function setTel2($tel2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel2', array($tel2));

        return parent::setTel2($tel2);
    }

    /**
     * {@inheritDoc}
     */
    public function setAltura($altura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAltura', array($altura));

        return parent::setAltura($altura);
    }

    /**
     * {@inheritDoc}
     */
    public function setPeso($peso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeso', array($peso));

        return parent::setPeso($peso);
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', array($cep));

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
