<?php

namespace DoctrineORMModule\Proxy\__CG__\AlbumFoto\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AlbumEntity extends \AlbumFoto\Entity\AlbumEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'idAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'tpAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'stAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'stComentario', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'dtCriacao', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'noAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'dsAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'idCliente');
        }

        return array('__isInitialized__', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'idAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'tpAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'stAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'stComentario', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'dtCriacao', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'noAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'dsAlbum', '' . "\0" . 'AlbumFoto\\Entity\\AlbumEntity' . "\0" . 'idCliente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AlbumEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdAlbum()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAlbum();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAlbum', array());

        return parent::getIdAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpAlbum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpAlbum', array());

        return parent::getTpAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function getStAlbum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAlbum', array());

        return parent::getStAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function getStComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStComentario', array());

        return parent::getStComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCriacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCriacao', array());

        return parent::getDtCriacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getNoAlbum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoAlbum', array());

        return parent::getNoAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsAlbum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsAlbum', array());

        return parent::getDsAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAlbum($idAlbum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAlbum', array($idAlbum));

        return parent::setIdAlbum($idAlbum);
    }

    /**
     * {@inheritDoc}
     */
    public function setTpAlbum($tpAlbum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpAlbum', array($tpAlbum));

        return parent::setTpAlbum($tpAlbum);
    }

    /**
     * {@inheritDoc}
     */
    public function setStAlbum($stAlbum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAlbum', array($stAlbum));

        return parent::setStAlbum($stAlbum);
    }

    /**
     * {@inheritDoc}
     */
    public function setStComentario($stComentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStComentario', array($stComentario));

        return parent::setStComentario($stComentario);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCriacao(\DateTime $dtCriacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCriacao', array($dtCriacao));

        return parent::setDtCriacao($dtCriacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoAlbum($noAlbum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoAlbum', array($noAlbum));

        return parent::setNoAlbum($noAlbum);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsAlbum($dsAlbum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsAlbum', array($dsAlbum));

        return parent::setDsAlbum($dsAlbum);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(\Cliente\Entity\ClienteEntity $idCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
