<?php

namespace DoctrineORMModule\Proxy\__CG__\Login\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CodPromoEntity extends \Login\Entity\CodPromoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'idCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'stCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'noCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'dsCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'nuDiasContrato', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'dtExpira', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'qdAtual', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'qdMax', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'vlDesconto');
        }

        return array('__isInitialized__', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'idCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'stCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'noCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'dsCod', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'nuDiasContrato', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'dtExpira', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'qdAtual', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'qdMax', '' . "\0" . 'Login\\Entity\\CodPromoEntity' . "\0" . 'vlDesconto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CodPromoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCod()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCod();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCod', array());

        return parent::getIdCod();
    }

    /**
     * {@inheritDoc}
     */
    public function getStCod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStCod', array());

        return parent::getStCod();
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCod', array());

        return parent::getNoCod();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsCod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsCod', array());

        return parent::getDsCod();
    }

    /**
     * {@inheritDoc}
     */
    public function getNuDiasContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuDiasContrato', array());

        return parent::getNuDiasContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtExpira()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtExpira', array());

        return parent::getDtExpira();
    }

    /**
     * {@inheritDoc}
     */
    public function getQdAtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQdAtual', array());

        return parent::getQdAtual();
    }

    /**
     * {@inheritDoc}
     */
    public function getQdMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQdMax', array());

        return parent::getQdMax();
    }

    /**
     * {@inheritDoc}
     */
    public function getVlDesconto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlDesconto', array());

        return parent::getVlDesconto();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCod($idCod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCod', array($idCod));

        return parent::setIdCod($idCod);
    }

    /**
     * {@inheritDoc}
     */
    public function setStCod($stCod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStCod', array($stCod));

        return parent::setStCod($stCod);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCod($noCod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCod', array($noCod));

        return parent::setNoCod($noCod);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsCod($dsCod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsCod', array($dsCod));

        return parent::setDsCod($dsCod);
    }

    /**
     * {@inheritDoc}
     */
    public function setNuDiasContrato($nuDiasContrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuDiasContrato', array($nuDiasContrato));

        return parent::setNuDiasContrato($nuDiasContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtExpira($dtExpita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtExpira', array($dtExpita));

        return parent::setDtExpira($dtExpita);
    }

    /**
     * {@inheritDoc}
     */
    public function setQdAtual($qdAtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQdAtual', array($qdAtual));

        return parent::setQdAtual($qdAtual);
    }

    /**
     * {@inheritDoc}
     */
    public function setQdMax($qdMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQdMax', array($qdMax));

        return parent::setQdMax($qdMax);
    }

    /**
     * {@inheritDoc}
     */
    public function setVlDesconto($vlDesconto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlDesconto', array($vlDesconto));

        return parent::setVlDesconto($vlDesconto);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
