<?php

namespace DoctrineORMModule\Proxy\__CG__\Cliente\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClienteEntity extends \Cliente\Entity\ClienteEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'idCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'tpCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'stCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'tpSexo', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'stLiConcordo', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dtHrCadastro', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dtNascimento', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dtVencimento', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'noCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'nuCpf', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'nuCep', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dsEndereco', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'sgUf', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'noCidade', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'nuTelefone');
        }

        return array('__isInitialized__', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'idCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'tpCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'stCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'tpSexo', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'stLiConcordo', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dtHrCadastro', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dtNascimento', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dtVencimento', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'noCliente', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'nuCpf', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'nuCep', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'dsEndereco', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'sgUf', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'noCidade', '' . "\0" . 'Cliente\\Entity\\ClienteEntity' . "\0" . 'nuTelefone');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClienteEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCliente();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setStCliente($stCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStCliente', array($stCliente));

        return parent::setStCliente($stCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getStCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStCliente', array());

        return parent::getStCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtHrCadastro($dtHrCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtHrCadastro', array($dtHrCadastro));

        return parent::setDtHrCadastro($dtHrCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtHrCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtHrCadastro', array());

        return parent::getDtHrCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCliente($noCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCliente', array($noCliente));

        return parent::setNoCliente($noCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCliente', array());

        return parent::getNoCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsEndereco($dsEndereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsEndereco', array($dsEndereco));

        return parent::setDsEndereco($dsEndereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsEndereco', array());

        return parent::getDsEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuTelefone($nuTelefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuTelefone', array($nuTelefone));

        return parent::setNuTelefone($nuTelefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuTelefone', array());

        return parent::getNuTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpCliente', array());

        return parent::getTpCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpCliente($tpCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpCliente', array($tpCliente));

        return parent::setTpCliente($tpCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuCpf', array());

        return parent::getNuCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpSexo', array());

        return parent::getTpSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtNascimento', array());

        return parent::getDtNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtVencimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtVencimento', array());

        return parent::getDtVencimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuCpf($nuCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuCpf', array($nuCpf));

        return parent::setNuCpf($nuCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function setTpSexo($tpSexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpSexo', array($tpSexo));

        return parent::setTpSexo($tpSexo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtNascimento($dtNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtNascimento', array($dtNascimento));

        return parent::setDtNascimento($dtNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtVencimento($dtVencimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtVencimento', array($dtVencimento));

        return parent::setDtVencimento($dtVencimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuCep', array());

        return parent::getNuCep();
    }

    /**
     * {@inheritDoc}
     */
    public function getSgUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSgUf', array());

        return parent::getSgUf();
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCidade', array());

        return parent::getNoCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuCep($nuCep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuCep', array($nuCep));

        return parent::setNuCep($nuCep);
    }

    /**
     * {@inheritDoc}
     */
    public function setSgUf($sgUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSgUf', array($sgUf));

        return parent::setSgUf($sgUf);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCidade($noCidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCidade', array($noCidade));

        return parent::setNoCidade($noCidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getStLiConcordo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStLiConcordo', array());

        return parent::getStLiConcordo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStLiConcordo($stLiConcordo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStLiConcordo', array($stLiConcordo));

        return parent::setStLiConcordo($stLiConcordo);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
