<?php

namespace DoctrineORMModule\Proxy\__CG__\Banner\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BannerEntity extends \Banner\Entity\BannerEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'idBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'stBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'tpBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'dtInicio', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'dtFim', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'dsBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'idCliente');
        }

        return array('__isInitialized__', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'idBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'stBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'tpBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'dtInicio', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'dtFim', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'dsBanner', '' . "\0" . 'Banner\\Entity\\BannerEntity' . "\0" . 'idCliente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BannerEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdBanner()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdBanner();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBanner', array());

        return parent::getIdBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function getStBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStBanner', array());

        return parent::getStBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpBanner', array());

        return parent::getTpBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtInicio', array());

        return parent::getDtInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtFim', array());

        return parent::getDtFim();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsBanner', array());

        return parent::getDsBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdBanner($idBanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdBanner', array($idBanner));

        return parent::setIdBanner($idBanner);
    }

    /**
     * {@inheritDoc}
     */
    public function setStBanner($stBanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStBanner', array($stBanner));

        return parent::setStBanner($stBanner);
    }

    /**
     * {@inheritDoc}
     */
    public function setTpBanner($tpBanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpBanner', array($tpBanner));

        return parent::setTpBanner($tpBanner);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtInicio(\DateTime $dtInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtInicio', array($dtInicio));

        return parent::setDtInicio($dtInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtFim(\DateTime $dtFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtFim', array($dtFim));

        return parent::setDtFim($dtFim);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsBanner($dsBanner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsBanner', array($dsBanner));

        return parent::setDsBanner($dsBanner);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(\Cliente\Entity\ClienteEntity $idCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
