<?php

namespace DoctrineORMModule\Proxy\__CG__\Usuario\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DadosContratoEntity extends \Usuario\Entity\DadosContratoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'idContrato', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'idUsuario', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'stPerfil', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'dtInicio', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'dtFinal', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'dsMotivo', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'codPromo', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'vlContrato');
        }

        return array('__isInitialized__', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'idContrato', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'idUsuario', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'stPerfil', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'dtInicio', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'dtFinal', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'dsMotivo', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'codPromo', '' . "\0" . 'Usuario\\Entity\\DadosContratoEntity' . "\0" . 'vlContrato');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DadosContratoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdContrato()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdContrato();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdContrato', array());

        return parent::getIdContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getStPerfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStPerfil', array());

        return parent::getStPerfil();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtInicio', array());

        return parent::getDtInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtFinal', array());

        return parent::getDtFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsMotivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsMotivo', array());

        return parent::getDsMotivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodPromo', array());

        return parent::getCodPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function getVlContrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlContrato', array());

        return parent::getVlContrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdContrato($idContrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdContrato', array($idContrato));

        return parent::setIdContrato($idContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setStPerfil($stPerfil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStPerfil', array($stPerfil));

        return parent::setStPerfil($stPerfil);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtInicio($dtInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtInicio', array($dtInicio));

        return parent::setDtInicio($dtInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtFinal($dtFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtFinal', array($dtFinal));

        return parent::setDtFinal($dtFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsMotivo($dsMotivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsMotivo', array($dsMotivo));

        return parent::setDsMotivo($dsMotivo);
    }

    /**
     * {@inheritDoc}
     */
    public function setCodPromo($codPromo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodPromo', array($codPromo));

        return parent::setCodPromo($codPromo);
    }

    /**
     * {@inheritDoc}
     */
    public function setVlContrato($vlContrato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlContrato', array($vlContrato));

        return parent::setVlContrato($vlContrato);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
