<?php

namespace DoctrineORMModule\Proxy\__CG__\Video\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VideoEntity extends \Video\Entity\VideoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'idVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'tpVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'dsVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'tiVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'idCliente');
        }

        return array('__isInitialized__', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'idVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'tpVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'dsVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'tiVideo', '' . "\0" . 'Video\\Entity\\VideoEntity' . "\0" . 'idCliente');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (VideoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdVideo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdVideo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdVideo', array());

        return parent::getIdVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpVideo', array());

        return parent::getTpVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsVideo', array());

        return parent::getDsVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdVideo($idVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdVideo', array($idVideo));

        return parent::setIdVideo($idVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function setTpVideo($tpVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpVideo', array($tpVideo));

        return parent::setTpVideo($tpVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsVideo($dsVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsVideo', array($dsVideo));

        return parent::setDsVideo($dsVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(\Cliente\Entity\ClienteEntity $idCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiVideo', array());

        return parent::getTiVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiVideo($tiVideo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiVideo', array($tiVideo));

        return parent::setTiVideo($tiVideo);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
