<?php

namespace DoctrineORMModule\Proxy\__CG__\AlbumFoto\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FotoEntity extends \AlbumFoto\Entity\FotoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'idFoto', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'stComentario', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'stFoto', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'tpFoto', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'dsLegenda', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'dsArquivo', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'dtCadastro', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'idAlbum');
        }

        return array('__isInitialized__', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'idFoto', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'stComentario', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'stFoto', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'tpFoto', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'dsLegenda', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'dsArquivo', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'dtCadastro', '' . "\0" . 'AlbumFoto\\Entity\\FotoEntity' . "\0" . 'idAlbum');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FotoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdFoto()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdFoto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFoto', array());

        return parent::getIdFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getStComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStComentario', array());

        return parent::getStComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function getStFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStFoto', array());

        return parent::getStFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpFoto', array());

        return parent::getTpFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsLegenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsLegenda', array());

        return parent::getDsLegenda();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsArquivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsArquivo', array());

        return parent::getDsArquivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCadastro', array());

        return parent::getDtCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAlbum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAlbum', array());

        return parent::getIdAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFoto($idFoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFoto', array($idFoto));

        return parent::setIdFoto($idFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function setStComentario($stComentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStComentario', array($stComentario));

        return parent::setStComentario($stComentario);
    }

    /**
     * {@inheritDoc}
     */
    public function setStFoto($stFoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStFoto', array($stFoto));

        return parent::setStFoto($stFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function setTpFoto($tpFoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpFoto', array($tpFoto));

        return parent::setTpFoto($tpFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsLegenda($dsLegenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsLegenda', array($dsLegenda));

        return parent::setDsLegenda($dsLegenda);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsArquivo($dsArquivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsArquivo', array($dsArquivo));

        return parent::setDsArquivo($dsArquivo);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCadastro(\DateTime $dtCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCadastro', array($dtCadastro));

        return parent::setDtCadastro($dtCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAlbum(\AlbumFoto\Entity\AlbumEntity $idAlbum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAlbum', array($idAlbum));

        return parent::setIdAlbum($idAlbum);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
