<?php

namespace DoctrineORMModule\Proxy\__CG__\Anunciante\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnuncianteEntity extends \Anunciante\Entity\AnuncianteEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'idAnunciante', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'stAnunciante', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'tpAnunciante', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'tpCabeloCor', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'stAceitaCartao', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dtAlteracao', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'noArtistico', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'nuTelefone', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'nuLatitude', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'nuLongitude', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsFrase1', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsFrase2', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsFrase3', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsUrlSite', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'idCliente', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'idCidade');
        }

        return array('__isInitialized__', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'idAnunciante', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'stAnunciante', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'tpAnunciante', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'tpCabeloCor', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'stAceitaCartao', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dtAlteracao', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'noArtistico', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'nuTelefone', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'nuLatitude', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'nuLongitude', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsFrase1', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsFrase2', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsFrase3', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'dsUrlSite', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'idCliente', '' . "\0" . 'Anunciante\\Entity\\AnuncianteEntity' . "\0" . 'idCidade');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AnuncianteEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdAnunciante()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAnunciante();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAnunciante', array());

        return parent::getIdAnunciante();
    }

    /**
     * {@inheritDoc}
     */
    public function getStAnunciante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAnunciante', array());

        return parent::getStAnunciante();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpAnunciante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpAnunciante', array());

        return parent::getTpAnunciante();
    }

    /**
     * {@inheritDoc}
     */
    public function getTpCabeloCor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpCabeloCor', array());

        return parent::getTpCabeloCor();
    }

    /**
     * {@inheritDoc}
     */
    public function getStAceitaCartao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAceitaCartao', array());

        return parent::getStAceitaCartao();
    }

    /**
     * {@inheritDoc}
     */
    public function getDtAlteracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtAlteracao', array());

        return parent::getDtAlteracao();
    }

    /**
     * {@inheritDoc}
     */
    public function getNoArtistico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoArtistico', array());

        return parent::getNoArtistico();
    }

    /**
     * {@inheritDoc}
     */
    public function getNuTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuTelefone', array());

        return parent::getNuTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function getNuLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuLatitude', array());

        return parent::getNuLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function getNuLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuLongitude', array());

        return parent::getNuLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsFrase1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsFrase1', array());

        return parent::getDsFrase1();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsFrase2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsFrase2', array());

        return parent::getDsFrase2();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsFrase3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsFrase3', array());

        return parent::getDsFrase3();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsUrlSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsUrlSite', array());

        return parent::getDsUrlSite();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCliente', array());

        return parent::getIdCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCidade', array());

        return parent::getIdCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAnunciante($idAnunciante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAnunciante', array($idAnunciante));

        return parent::setIdAnunciante($idAnunciante);
    }

    /**
     * {@inheritDoc}
     */
    public function setStAnunciante($stAnunciante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAnunciante', array($stAnunciante));

        return parent::setStAnunciante($stAnunciante);
    }

    /**
     * {@inheritDoc}
     */
    public function setTpAnunciante($tpAnunciante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpAnunciante', array($tpAnunciante));

        return parent::setTpAnunciante($tpAnunciante);
    }

    /**
     * {@inheritDoc}
     */
    public function setTpCabeloCor($tpCabeloCor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpCabeloCor', array($tpCabeloCor));

        return parent::setTpCabeloCor($tpCabeloCor);
    }

    /**
     * {@inheritDoc}
     */
    public function setStAceitaCartao($stAceitaCartao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAceitaCartao', array($stAceitaCartao));

        return parent::setStAceitaCartao($stAceitaCartao);
    }

    /**
     * {@inheritDoc}
     */
    public function setDtAlteracao(\DateTime $dtAlteracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtAlteracao', array($dtAlteracao));

        return parent::setDtAlteracao($dtAlteracao);
    }

    /**
     * {@inheritDoc}
     */
    public function setNoArtistico($noArtistico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoArtistico', array($noArtistico));

        return parent::setNoArtistico($noArtistico);
    }

    /**
     * {@inheritDoc}
     */
    public function setNuTelefone($nuTelefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuTelefone', array($nuTelefone));

        return parent::setNuTelefone($nuTelefone);
    }

    /**
     * {@inheritDoc}
     */
    public function setNuLatitude($nuLatitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuLatitude', array($nuLatitude));

        return parent::setNuLatitude($nuLatitude);
    }

    /**
     * {@inheritDoc}
     */
    public function setNuLongitude($nuLongitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuLongitude', array($nuLongitude));

        return parent::setNuLongitude($nuLongitude);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsFrase1($dsFrase1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsFrase1', array($dsFrase1));

        return parent::setDsFrase1($dsFrase1);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsFrase2($dsFrase2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsFrase2', array($dsFrase2));

        return parent::setDsFrase2($dsFrase2);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsFrase3($dsFrase3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsFrase3', array($dsFrase3));

        return parent::setDsFrase3($dsFrase3);
    }

    /**
     * {@inheritDoc}
     */
    public function setDsUrlSite($dsUrlSite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsUrlSite', array($dsUrlSite));

        return parent::setDsUrlSite($dsUrlSite);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCliente(\Cliente\Entity\ClienteEntity $idCliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCliente', array($idCliente));

        return parent::setIdCliente($idCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCidade(\Cidade\Entity\CidadeEntity $idCidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCidade', array($idCidade));

        return parent::setIdCidade($idCidade);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
