<?php

namespace Agenda\Entity\Repository;

use Agenda\Entity\AgendaEventoEntity;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

/**
 * AgendaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaEventoRepository extends EntityRepository
{
    //Função que verifica se o código ja esá cadastrado
    //$dataHoje = data do dia atual no formato AAAA-MM-DD
    public function listaEventos($dataHoje){
        $select = $this->getEntityManager()->createQueryBuilder()
                  ->select(array('e.idEvento','e.stDisp','e.txTitulo','e.txDescricao','e.dtInicial','e.dtFinal'))
                  ->from('Agenda\Entity\AgendaEventoEntity', 'e')
                  ->where('e.dtFinal >= :dataHoje')
                  ->setParameter('dataHoje', $dataHoje);
        
        $qry = $select->getQuery();        
        $result = $qry->getResult();
        return $result;
    }//função para lista eventos
    
}//AgendaEventoRepository