<?php

namespace Agenda\Entity\Repository;

use Agenda\Entity\AgendaEventoFotoEntity;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

/**
 * AgendaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaEventoFotoRepository extends EntityRepository
{
    //Função que verifica se o código ja esá cadastrado
    
    
}//AgendaEventoRepository