<?php

namespace Agenda\Entity\Repository;

use Agenda\Entity\AgendaEventoFotoEntity;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

/**
 * AgendaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaEventoFotoRepository extends EntityRepository
{
    //Função que lista os registros de fotos referentes a um evento através do ID
    public function listaFotos($idEvento){
        $select = $this->getEntityManager()->createQueryBuilder()
                  ->select(array('f.tpFoto','f.txPath','f.txLegenda'))
                  ->from('Agenda\Entity\AgendaEventoFotosEntity' , 'f')
                  ->where('f.fkIdEvento = :id')
                  ->setParameter('id', $idEvento);
        
        $qry    = $select->getQuery();
        $result = $qry->getResult();
        return $result;        
    }///lista fotos eventos
    
    
}//AgendaEventoFotoRepository