<?php

namespace Agenda\Entity\Repository;

use Agenda\Entity\AgendaEventoEntity;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

/**
 * AgendaEventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaEventoRepository extends EntityRepository
{
    //Função que verifica se o código ja esá cadastrado
    public function listaEventos(){
        $select = $this->getEntityManager()->createQueryBuilder()
                  ->select(array('e.stDisp','e.txTitulo','e.txDescricao'))
                  ->from('Agenda\Entity\AgendaEventoEntity', 'e')
                  ->leftJoin('Agenda\Entity\AgendaEventoFotosEntity', 'f','WITH','e.idEvento = f.fkIdEvento')
                  ->where('1=1');
        
        $qry = $select->getQuery();
        $result = $qry->getResult();
        return $result;        
    }//função para lista eventos
    
}//AgendaEventoRepository