<div class="row">
    
    <?php if ($this->idClientePerfil != "") : ?>
    
        <?php echo $this->partial('form-cad-cliente'); ?>
        
    <?php else: ?>
    
        <!-- LEFT -->
        <div class="col-lg-3 col-md-4">
            <!-- MENU -->
            <?php echo $this->partial('menu-vertical-perfil'); ?>
            <!-- /MENU -->
        </div>

        <!-- RIGHT -->
        <div class="col-lg-9 col-md-8">
            <div class="tab-content transparent">

                <!-- SETTINGS TAB 1 -->
                <div id="tab-s1" class="tab-pane active">
                    <?php echo $this->partial('form-cad-usuario'); ?>
                </div>
                <!-- /SETTINGS TAB 1 -->

                <!-- SETTINGS TAB 2 -->
                <div id="tab-s11" class="tab-pane">
                    <?php echo $this->partial('form-foto-perfil'); ?>
                </div>
                <!-- /SETTINGS TAB 2 -->

                <!-- SETTINGS TAB 3 -->
                <div id="tab-s12" class="tab-pane">
                    <?php echo $this->partial('form-alterar-senha'); ?>
                </div>
                <!-- /SETTINGS TAB 3 -->

                <!-- SETTINGS TAB 4 -->
                <div id="tab-s13" class="tab-pane">
                    <?php echo $this->partial('form-config-pagina-perfil'); ?>
                </div>
                <!-- /SETTINGS TAB 4 -->

            </div>
        </div>
    
    <?php endif; ?>
        
</div>