<div class="row">
    <!-- LEFT -->
    <div class="col-lg-4 col-md-5">

        <!-- USER ACTIVITY -->
        <h5 class="text-danger bold margin-top10 hidden-xs">
            <i class="fa fa-rss"></i>
            Activity
        </h5>

        <!-- activity list -->
        <div class="row profile-activity hidden-xs">

            <!-- activity item -->
            <div class="col-xs-2 col-sm-1">
                <time datetime="2014-06-29" class="datebox">
                    <strong>Jun</strong>
                    <span>29</span>
                </time>
            </div>

            <div class="col-xs-10 col-sm-11">
                <h6><a href="#">Lorem ipsum dolor sit amet</a></h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
                    tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet dolore magna aliquam 
                    tincidunt erat volutpat.
                </p>
            </div>
            <!-- /activity item -->

            <div class="col-sm-12">
                <hr class="half-margins" />
            </div><!-- /activity separator -->

            <!-- activity item -->
            <div class="col-xs-2 col-sm-1">
                <time datetime="2014-06-29" class="datebox">
                    <strong>Jun</strong>
                    <span>29</span>
                </time>
            </div>

            <div class="col-xs-10 col-sm-11">
                <h6><a href="#">Sed diam nonummy nibh euismod</a></h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
                    tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet dolore magna aliquam 
                    tincidunt erat volutpat.
                </p>
            </div>
            <!-- /activity item -->

            <div class="col-sm-12">
                <hr class="half-margins" />
            </div><!-- /activity separator -->

            <!-- activity item -->
            <div class="col-xs-2 col-sm-1">
                <time datetime="2014-06-29" class="datebox">
                    <strong>Jun</strong>
                    <span>29</span>
                </time>
            </div>

            <div class="col-xs-10 col-sm-11">
                <h6><a href="#">Sed diam nonummy nibh euismod</a></h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod 
                    tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet dolore magna aliquam 
                    tincidunt erat volutpat.
                </p>
            </div>
            <!-- /activity item -->

            <div class="col-sm-12">
                <hr class="half-margins" />
            </div><!-- /activity separator -->

            <!-- paginatoin -->
            <div class="text-center">
                <ul class="pagination pagination-sm">
                    <li class="disabled"><a href="#">Prev</a></li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                </ul>													
            </div>
            <!-- /paginatoin -->

        </div>
        <!-- /activity list -->

        <!-- /USER ACTIVITY -->
    </div>

    <!-- RIGHT -->
    <div class="col-md-7">

        <form class="well">
            <textarea rows="2" class="form-control" placeholder="No que você está pensando?"></textarea>

            <div class="margin-top-10">
                <button type="submit" class="btn btn-sm btn-primary pull-right">Postar</button>
                <a href="#" class="btn btn-link profile-btn-link" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Add a Location"><i class="fa fa-map-marker"></i></a>
                <a href="#" class="btn btn-link profile-btn-link" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Add Photo"><i class="fa fa-camera"></i></a>
                <a href="#" class="btn btn-link profile-btn-link" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Add File"><i class="fa fa-file"></i></a>
            </div>
        </form>

        <!-- COMMENT -->
        <ul class="comment list-unstyled">
            <li class="comment">

                <!-- avatar -->
                <img class="avatar" src="<?php echo $this->basePath() . '/epona/images/demo/fashion/thumb/3.jpg'; ?>" width="50" height="50" alt="avatar" />

                <!-- comment body -->
                <div class="comment-body"> 
                    <a href="#" class="comment-author">
                        <small class="text-muted pull-right"> 12 Minutes ago </small>
                        <span>Melisa Doe</span>
                    </a>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                        euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet 
                        dolore magna aliquam tincidunt erat volutpat.  
                    </p>
                </div><!-- /comment body -->

                <!-- options -->
                <ul class="list-inline fsize11">
                    <li>
                        <a href="#" class="text-info"><i class="fa fa-reply"></i> Responder</a>
                    </li>
                    <li>
                        <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Curtir</a>
                    </li>
                    <li>
                        <a href="#" class="text-muted">Show All Comments (36)</a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-danger">Remover</a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-primary">Editar</a>
                    </li>
                </ul>
            </li><!-- /options -->

            <li class="comment comment-reply">

                <!-- avatar -->
                <img class="avatar" src="<?php echo $this->basePath() . '/epona/images/demo/fashion/thumb/1.jpg'; ?>" width="35" height="35" alt="avatar" />

                <!-- comment body -->
                <div class="comment-body"> 
                    <a href="#" class="comment-author">
                        <small class="text-muted pull-right"> 4 Minutes ago </small>
                        <span class="text-muted">Ioana Doe</span>
                    </a>
                    <p class="text-muted">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
                    </p>
                </div><!-- /comment body -->

                <!-- options -->
                <ul class="list-inline fsize11">
                    <li>
                        <a href="#" class="text-success"><span class="text-muted"><i class="fa fa-thumbs-up"></i> Curtir</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-danger"><span class="text-muted">Remover</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-primary"><span class="text-muted">Editar</span></a>
                    </li>
                </ul><!-- /options -->

            </li>

            <li class="comment comment-reply">

                <!-- avatar -->
                <img class="avatar" src="<?php echo $this->basePath() . '/epona/images/demo/fashion/thumb/2.jpg'; ?>" width="35" height="35" alt="avatar" />

                <!-- comment body -->
                <div class="comment-body"> 
                    <a href="#" class="comment-author">
                        <small class="text-muted pull-right"> a moment ago </small>
                        <span class="text-muted">Simona Doe</span>
                    </a>
                    <p class="text-muted">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
                    </p>
                </div><!-- /comment body -->

                <!-- options -->
                <ul class="list-inline fsize11">
                    <li>
                        <a href="#" class="text-success"><span class="text-muted"><i class="fa fa-thumbs-up"></i> Curtir</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-danger"><span class="text-muted">Remover</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-primary"><span class="text-muted">Editar</span></a>
                    </li>
                </ul><!-- /options -->

            </li>
        </ul>
        <!-- /COMMENT -->

        <!-- COMMENT -->
        <ul class="comment list-unstyled">
            <li class="comment">

                <!-- avatar -->
                <img class="avatar" src="<?php echo $this->basePath() . '/epona/images/demo/fashion/thumb/4.jpg'; ?>" width="50" height="50" alt="avatar" />

                <!-- comment body -->
                <div class="comment-body"> 
                    <a href="#" class="comment-author">
                        <small class="text-muted pull-right"> 12 Minutes ago </small>
                        <span>Melisa Doe</span>
                    </a>
                    <p>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                        euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet 
                        dolore magna aliquam tincidunt erat volutpat.  
                    </p>
                </div><!-- /comment body -->

                <!-- options -->
                <ul class="list-inline fsize11">
                    <li>
                        <a href="#" class="text-info"><i class="fa fa-reply"></i> Responder</a>
                    </li>
                    <li>
                        <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Curtir</a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-danger">Remover</a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-primary">Editar</a>
                    </li>
                </ul>
            </li><!-- /options -->

            <li class="comment comment-reply">

                <!-- avatar -->
                <img class="avatar" src="<?php echo $this->basePath() . '/epona/images/demo/fashion/thumb/3.jpg'; ?>" width="35" height="35" alt="avatar" />

                <!-- comment body -->
                <div class="comment-body"> 
                    <a href="#" class="comment-author">
                        <small class="text-muted pull-right"> 4 Minutes ago </small>
                        <span class="text-muted">Ioana Doe</span>
                    </a>
                    <p class="text-muted">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
                    </p>
                </div><!-- /comment body -->

                <!-- options -->
                <ul class="list-inline fsize11">
                    <li>
                        <a href="#" class="text-success"><span class="text-muted"><i class="fa fa-thumbs-up"></i> Curtir</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-danger"><span class="text-muted">Remover</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-primary"><span class="text-muted">Editar</span></a>
                    </li>
                </ul><!-- /options -->

            </li>

            <li class="comment comment-reply">

                <!-- avatar -->
                <img class="avatar" src="<?php echo $this->basePath() . '/epona/images/demo/fashion/thumb/5.jpg'; ?>" width="35" height="35" alt="avatar" />

                <!-- comment body -->
                <div class="comment-body"> 
                    <a href="#" class="comment-author">
                        <small class="text-muted pull-right"> a moment ago </small>
                        <span class="text-muted">Simona Doe</span>
                    </a>
                    <p class="text-muted">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
                    </p>
                </div><!-- /comment body -->

                <!-- options -->
                <ul class="list-inline fsize11">
                    <li>
                        <a href="#" class="text-success"><span class="text-muted"><i class="fa fa-thumbs-up"></i> Curtir</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-danger"><span class="text-muted">Remover</span></a>
                    </li>
                    <li class="pull-right">
                        <a href="#" class="text-primary"><span class="text-muted">Editar</span></a>
                    </li>
                </ul><!-- /options -->

            </li>
            <li>
                <div class="input-group">
                    <input id="btn-input" type="text" class="form-control" placeholder="Digite sua mensagem...">
                    <span class="input-group-btn">
                        <button class="btn btn-primary" id="btn-chat">
                            <i class="fa fa-reply"></i> Responder
                        </button> 
                    </span>
                </div>
            </li>
        </ul>
        <!-- /COMMENT -->


    </div>
</div>