<script type="text/javascript" src="<?php echo $this->basePath() . '/js/perfil/aba-menu-alterar-senha.js' ?>"></script>

<form id="formAlterarSenha" class="sky-form boxed" action="<?php echo $this->basePath() . '/perfil/alterar-senha' ?>" method="post">

    <!-- BASIC FORM -->
    <div class="panel panel-light margin-bottom8">

        <div class="panel-heading">
            <h3 id="tituloUsuario" class="panel-title bold">Alterar Senha</h3>
        </div>

        <div class="panel-body">

            <div class="row">
                <div class="form-group">
                    Senha Atual*:
                    <label class="input">
                        <i class="icon-append fa fa-lock"></i>
                        <input name="senhaAtual" id="senhaAtual" type="password" class="form-control">
                        <b class="tooltip tooltip-bottom-right">(*) Obrigatório - Informação sigilosa.</b>
                    </label>
                </div>
                <div class="form-group">
                    Nova Senha*:
                    <label class="input">
                        <i class="icon-append fa fa-lock"></i>
                        <input name="senhaNova" id="senhaNova" type="password" class="form-control">
                        <b class="tooltip tooltip-bottom-right">(*) Obrigatório - Informação sigilosa.</b>
                    </label>
                </div>
                <div class="form-group">
                    Confirmar Nova Senha*:
                    <label class="input">
                        <i class="icon-append fa fa-lock"></i>
                        <input name="senhaConfirm" id="senhaConfirm" type="password" class="form-control">
                        <b class="tooltip tooltip-bottom-right">(*) Obrigatório - Informação sigilosa.</b>
                    </label>
                </div>

                <div class="margiv-top10">
                    <a href="#" class="btn btn-primary" id="btnAlterarSenha"><i class="fa fa-save"></i>Salvar</a>
                </div>
                
            </div>
            
        </div>
        
    </div>

</form>