<div class="row">

    <!-- LEFT -->
    <div class="col-md-4">
        <!-- IMAGE -->
        <figure class="default-gradient bg-silver text-center margin-bottom8">
            <img id="imgFotoPerfilUsuario" class="img-responsive" src="" alt="" />
        </figure>
        <!-- /IMAGE -->
    </div>

    <!-- RIGHT -->
    <div class="col-md-8">
        
        <!--<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet dolore magna aliquam tincidunt erat volutpat.</p>-->
        
        <ul class="has-icons list-unstyled">
            <li><i class="gray fa fa-calendar"></i> <?php echo $this->masterHelper()->tipoUsuario($this->identity()->getTpUsuario()); ?> desde <?php echo $this->identity()->getDtCadastro()->format('d/m/Y'); ?>.&nbsp;(<?php echo $this->masterHelper()->acrescentarZeros($this->masterHelper()->calcularDias($this->identity()->getDtCadastro()->format('Y-m-d')), 2) . " dia(s)"; ?>)</li>
            
            <?php if ($this->identity()->getTpUsuario() == 1 || $this->identity()->getTpUsuario() == 2) : ?>
            
                <?php $qtdeContatosAdmin = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeContatosHelper(),2); ?>
                <?php $qtdeDepoimentosAdmin = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeDepoimentosHelper(NULL),2); ?>
                <?php $qtdeAnunciantesAdmin = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeClientesHelper(1),2); ?>
                <?php $qtdeSociosAdmin = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeClientesHelper(2),2); ?>
            
            <li><i class="gray fa fa-stack-exchange"></i> Contatos: <?php echo $qtdeContatosAdmin; ?> registro(s)</li>
            <li><i class="gray fa fa-comments"></i> Depoimentos: <?php echo $qtdeDepoimentosAdmin; ?> registro(s)</li>
            <li><i class="gray fa fa-user"></i> Anunciantes: <?php echo $qtdeAnunciantesAdmin; ?> registro(s)</li>
            <li><i class="gray fa fa-users"></i> Sócios: <?php echo $qtdeSociosAdmin; ?> registro(s)</li>
            <?php endif; ?>
                
            <?php if ($this->identity()->getTpUsuario() == 3) : ?>
                
                <?php $qtdeFavoritosCliente = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeFavoritosHelper($this->idClientePerfil),2); ?>
                <?php $qtdeCurtidasCliente = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeCurtidasHelper($this->idClientePerfil),2); ?>
                <?php $qtdeDepoimentosCliente = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeDepoimentosHelper($this->idClientePerfil),2); ?>
                <?php $qtdeVisualizacoesCliente = $this->masterHelper()->acrescentarZeros($this->mostrarVisualizacaoPaginaHelper($this->idClientePerfil),2); ?>
                
            <li><i class="gray fa fa-users"></i> <?php echo $qtdeVisualizacoesCliente; ?> Visitante(s) acessaram sua página</li>
            <li><i class="gray fa fa fa-thumbs-up"></i> <?php echo $qtdeCurtidasCliente; ?> Curtida(s) em sua página</li>
            <li><i class="gray fa fa-star"></i> <?php echo $qtdeFavoritosCliente; ?> Adicionada como Favorita</li>
            <li><i class="gray fa fa-comments"></i> <?php echo $qtdeDepoimentosCliente; ?> Depoimento(s) recebidos(s)</li>
                
            <?php endif; ?>
        </ul>
        
        <?php $qtdeFavoritos = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeFavoritosHelper("", $this->identity()->getIdUsuario()),2); ?>
        <?php $qtdeCurtidas = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeCurtidasHelper("", $this->identity()->getIdUsuario()),2); ?>
        <?php $qtdeDepoimentos = $this->masterHelper()->acrescentarZeros($this->mostrarQtdeDepoimentosHelper("", $this->identity()->getIdUsuario()),2); ?>
        
        <ul class="has-icons list-unstyled">
            <li><i class="gray fa fa-star"></i> <?php echo $qtdeFavoritos; ?> Anunciante(s) Favorita(s)</li>
            <li><i class="gray fa fa fa-thumbs-up"></i> <?php echo $qtdeCurtidas; ?> Página(s) Curtida(s)</li>
            <li><i class="gray fa fa-comments"></i> <?php echo $qtdeDepoimentos; ?> Depoimento(s) registrado(s)</li>
            <!-- EM BREVE QTDE MENSAGENS RECEBIDAS -->
            <!--<li><i class="gray fa fa-envelope"></i> Mensagens: 17 nova(s) de 777 registro(s)</li>-->
        </ul>
        
    </div>
<!--    
    <div class="col-md-5">
    //Espaco para colocar um Banner
    </div>
-->

</div>