<div class="clearfix tab-header">
    <ul class="side-nav list-group margin-bottom30">
        <?php if ($this->configPaginaPerfil['stInfoUsuario'] != 2) : ?>
        <li class="list-group-item active"><a href="#tab-s0" data-toggle="tab"><i class="fa fa-home"></i> Meu Perfil</a></li>
        <?php endif; ?>
        <li class="list-group-item"><a href="#tab-s1" data-toggle="tab"><i class="fa fa-cog"></i> Dados Cadastrais</a></li>
        <li class="list-group-item"><a href="#tab-s11" data-toggle="tab"><i class="fa fa-eye"></i> Foto Perfil</a></li>
        <li class="list-group-item"><a href="#tab-s12" data-toggle="tab"><i class="fa fa-lock"></i> Alterar Senha</a></li>
        <li class="list-group-item"><a href="#tab-s13" data-toggle="tab" id="menuConfiguracoesPerfilCad"><i class="fa fa-gears"></i> Configurações do Perfil</a></li>

        <li class="list-group-item list-toggle">
            <a data-toggle="collapse" data-parent="#sidebar-nav" href="#collapse-2"><i class="fa fa-level-down"></i> Administração</a>
            <ul id="collapse-2" class="collapse">
                <li><a href="<?php echo $this->basePath() . '/agenda/configuracoes' ?>"><i class="fa fa-angle-right"></i> Controle de Agenda</a></li>
                <li><a href="<?php echo $this->basePath() . '/anunciante/' ?>"><i class="fa fa-angle-right"></i> Controle de Anunciantes</a></li>
                <li><a href="<?php echo $this->basePath() . '/banner/' ?>"><i class="fa fa-angle-right"></i> Controle de Banners</a></li>
                <li><a href="<?php echo $this->basePath() . '/cliente/' ?>"><i class="fa fa-angle-right"></i> Controle de Clientes</a></li>
                <li><a href="<?php echo $this->basePath() . '/contato' ?>"><span class="badge">14 News</span><i class="fa fa-angle-right"></i> Controle de Contatos</a></li>
                <li><a href="<?php echo $this->basePath() . '/pagamento/' ?>"><i class="fa fa-angle-right"></i> Controle de Pagamentos</a></li>
                <li><a href="<?php echo $this->basePath() . '/usuario/' ?>"><i class="fa fa-angle-right"></i> Controle de Usuários</a></li>
            </ul>
        </li>

        <li class="list-group-item list-toggle">
            <a data-toggle="collapse" data-parent="#sidebar-nav" href="#collapse-4"><i class="fa fa-level-down"></i> Parametros</a>
            <ul id="collapse-4" class="collapse">
                <li><a href="<?php echo $this->basePath() . '/cidade/' ?>"><i class="fa fa-angle-right"></i> Cadastro de Cidades</a></li>
                <li><a href="<?php echo $this->basePath() . '/caracteristicas/' ?>"><i class="fa fa-angle-right"></i> Cadastro de Caracterísitcas</a></li>
                <!--<li><a href="<?php echo $this->basePath() . '/categoria/' ?>"><i class="fa fa-angle-right"></i> Cadastro de Categorias</a></li>-->
            </ul>
        </li>
    </ul>
</div>