<!--Scripts JS-->
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/agenda/novo.js'; ?>"></script>
<!--Scripts JS END-->

<!--Div de Conteúdo-->
<div class="col-sm-12 col-md-12 col-lg-12">
    <!--Header-->
    <div class="col-sm-12 col-md-12 text-center" >
        <h4><!-- Page Title -->
            <b>Cadastro de Novo Evento na Agenda</b>
        </h4><!-- /Page Title -->
    </div><!--Header END-->
        
    <!--Content-->
    <div class="col-sm-12 col-md-12" style="overflow: hidden;">
        <?php 
            //Iniciando o Formulário
            $formNovo = $this->dataForm;
            $formNovo->prepare();
            echo $this->form()->openTag($formNovo);            
        ?>        
        
        <!--Dados Principais do Evento - PAINEL PRINCIPAL-->
        <div id="painel_principal" class="col-sm-12 col-md-12">
             <!--Título-->
            <div class="col-sm-12 col-md-12">
                <h3>
                    <b><u>Cadastro dos dados principais</u></b>&nbsp;<br>
                    <span style="font-size:12px;">
                        Aqui é necessário cadastrar os dados de divulgação do seu evento.
                    </span>
                </h3>                
            </div><!--Título END-->
            
            <!--Título do Evento-->
            <div class="col-sm-12 col-md-12" style="background:#222222;">
                Título / Nome do Evento:<br>
                <?php echo $this->formElement($formNovo->get('titulo')); ?>
            </div><!--Título do Evento END-->
            
            <!--Estado e Endereço do Evento-->
            <div class="col-sm-12 col-md-12" style="background:#424242;">
                <!--EStado-->
                <div class="col-sm-5 col-md-5">
                    Estado onde acontecerá o Evento:<br>
                    <?php echo $this->formElement($formNovo->get('sgUfCad')); ?>
                </div><!--EStado END-->
                
                <!--Endereço-->
                <div class="col-sm-6 col-sm-offset-1 col-md-6 col-md-offset-1">
                     Endereço, cidade, bairro ou local de onde acontecerá o Evento:<br>
                    <?php echo $this->formElement($formNovo->get('endereco')); ?>
                </div><!--Endereço END-->
            </div><!--Estado e Endereço do Evento END-->
            
            <!--Descrição do Evento-->
            <div class="col-sm-12 col-md-12" style="background:#222222;">
                Informações detalhadas sobre o evento:<br>
                <?php echo $this->formElement($formNovo->get('descricao')); ?>
            </div><!--Descrição do Evento END-->
            
            <!--Botões de Controle-->
            <div class="col-sm-12 col-md-12" style="background:#424242;">
                <!--Botão Voltar-->
                <div class="col-sm-6 col-md-6">
                    &nbsp;
                </div><!--Botão Voltar END-->
                
                <!--Botao Avançar-->
                <div class="col-sm-5 col-sm-offset-1 col-md-5 col-md-offset-1">
                    <br>
                    <input type="button" value="Continuar >>" class="btn btn-sm col-sm-12 col-md-6 col-md-offset-6" style="color:#FFF;font-size:14px;" onclick="proximoSlide('painel_principal','painel_data')" />
                </div><!--Botao Avançar END-->
            </div><!--Botões de Controle END-->            
        </div><!--PAINEL PRINCIPAL END--> 
        
        <!--DIAS E HORÁRIOS DO EVENTO - PAINEL DATA-->
        <div id="painel_data" class="col-sm-12 col-md-12" style="display: none;">
            <!--Título-->
            <div class="col-sm-12 col-md-12">
                <h3>
                    <b><u>Cadastro dos Dias e Horários</u></b>&nbsp;<br>
                    <span style="font-size:12px;">
                        Aqui é possível cadastrar os dias e Horários que acontecerão o seu evento.                        
                    </span>
                </h3>                
            </div><!--Título END-->
            
            <!--Pèríodo do Evento-->
            <div class="col-sm-12 col-md-12" style="background:#222222;"> 
                <!--Data Inicial-->
                <div class="col-sm-5 col-md-3">
                    <div class="form-group col-sm-12 col-md-12">
                        <label class="control-label"> Data de Início do Evento:</label><br>
                        <div class="input-group">
                            <?php echo $this->formElement($formNovo->get('dtInicial')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>    
                </div><!--Data Inicial END-->
                
                <!--Data Final-->
                <div class="col-sm-5 col-sm-offset-1 col-md-3 col-md-offset-1">
                    <div class="form-group col-sm-12 col-md-12">
                        <label class="control-label"> Data de Término do Evento:</label><br>
                        <div class="input-group">
                            <?php echo $this->formElement($formNovo->get('dtFinal')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div><!--Data Final END-->
                
                <!--Botão para verificar o horário-->
                <div class="col-sm-12 col-md-4 col-md-offset-1">
                     <br>
                     <?php echo $this->formElement($formNovo->get('btnVerifHorario')); ?>
                </div><!--Botão para verificar o horário END-->                               
            </div><!--Período do Evento END-->
            
            <!--Lista de dias e Horários do Evento-->
            <div class="col-sm-12 col-md-12" style="background:#424242;">
                <div id="dv_horarios_evento" class="col-sm-12 col-md-12"></div>
            </div><!--Lista de dias e Horários do Evento END--> 
            
             <!--Botões de Controle-->
            <div class="col-sm-12 col-md-12" style="background:#424242;">
                <!--Botão Voltar-->
                <div class="col-sm-6 col-md-6">
                    <br><input type="button" value="<< Voltar" class="btn btn-sm col-sm-12 col-md-6" style="color:#FFF;font-size:14px;" onclick="voltarSlide('painel_data','painel_principal')" />
                </div><!--Botão Voltar END-->
                
                <!--Botao Avançar-->
                <div class="col-sm-5 col-sm-offset-1 col-md-5 col-md-offset-1">
                    <br>
                    <input type="button" value="Continuar >>" class="btn btn-sm col-sm-12 col-md-6 col-md-offset-6" style="color:#FFF;font-size:14px;" onclick="proximoSlide('painel_data','painel_foto')" />
                </div><!--Botao Avançar END-->
            </div><!--Botões de Controle END-->
        </div><!--DIAS E HORÁRIOS DO EVENTO - PAINEL DATA END-->
        
        
        
        <!--FOTOS DO EVENTO-->
        <div id="painel_foto" class="col-sm-12 col-md-12" style="display: none;">
            <!--Título-->
            <div class="col-sm-12 col-md-12">
                <h3>
                    <b><u>Cadastro de Fotos</u></b>&nbsp;<br>
                    <span style="font-size:12px;">
                        Aqui é possível cadastrar algumas fotos de divulgação do seu evento.
                        <b>Não é obrigatório</b> o cadastro das fotos <b>PORÉM, AS FOTOS ATRAEM MUITO MAIS visitantes</b>!!!
                    </span>
                </h3>                
            </div><!--Título END-->
            
            <!--Foto de Perfil-->
            <div class="col-sm-12 col-md-12" style="background:#222222;margin-top: 10px;">
                <div class="col-sm-12 col-md-12" style="text-align: center; height: 30px; background:rgba(73,0,0,0.7);">
                    <b>FOTO DE PERFIL</b> - Foto de capa do evento, é a foto de chamada do seu evento (aparecerá na tela inicial):
                </div>
                
                <!--Imagem -  Foto de Capa-->
                <div class="col-sm-5 col-md-4">
                    <img src="<?php echo '/storage/agenda/no-photo.png" ';?>" width="170px"/>
                </div><!--Imagem END-->
                
                <!--Input de Foto-->
                <div class="col-sm-offset-1 col-sm-6 col-md-offset-1 col-md-7">
                    <br>
                        Clique no botão abaixo e selecione sua foto:
                    <br>
                    <input type="file" id="img_profile_evento" name="img_evento" value="Enviar Foto">
                </div><!--Input de Foto END-->
            </div><!--Foto de Perfil END-->
            
             <!--Botões de Controle-->
            <div class="col-sm-12 col-md-12" style="background:#424242;">
                <!--Botão Voltar-->
                <div class="col-sm-6 col-md-6">
                    <br><input type="button" value="<< Voltar" class="btn btn-sm col-sm-12 col-md-6" style="color:#FFF;font-size:14px;" onclick="voltarSlide('painel_foto','painel_data')" />
                </div><!--Botão Voltar END-->
                
                <!--Botao Avançar-->
                <div class="col-sm-5 col-sm-offset-1 col-md-5 col-md-offset-1">
                    <br>
                    <input type="button" value="Cadastrar Evento" class="btn btn-sm col-sm-12 col-md-6 col-md-offset-6" style="color:#FFF;font-size:14px;" />
                </div><!--Botao Avançar END-->
            </div><!--Botões de Controle END-->
        </div><!--FOTOS DO EVENTO END-->
        
    </div><!--Content END-->
    
    
</div><!--Div de Conteúdo END-->