<!--Scripts JS-->
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/agenda/novo.js'; ?>"></script>
<!--Scripts JS END-->

<!--Div de Conteúdo-->
<div class="col-sm-12 col-md-12 col-lg-12">
    <!--Header-->
    <div class="col-sm-12 col-md-12 text-center" >
        <h4><!-- Page Title -->
            <b>Cadastrando Novo Evento na Agenda</b>
        </h4><!-- /Page Title -->
    </div><!--Header END-->
        
    
    
</div><!--Div de Conteúdo END-->