<!--Style-->
<style type="text/css">    
    .header-tab li a{        
        color: #424242 !important;
        background: #BFBDBD !important;
    }
    .header-tab li a .text-muted{        
        color: #424242 !important;        
    }
    .header-tab li.active a{        
        color: #EDE8E8 !important;
        font-weight: bold;
        background: #545252 !important;
    }    
    .header-tab li.active a .text-muted{
        color: #FFF !important;
    }        
    .content-tab{
        background: #4C4C4C;
    }
</style>

<!--Div de Conteúdo-->
<div class="col-sm-12 col-md-12 col-lg-12">
    <!--Tab Header-->
    <div class="clearfix tab-header">
        <ul class="nav nav-tabs pull-left header-tab"> 
            <li class="active"><a href="#tab-pendentes" data-toggle="tab"><i class="fa fa-eye"></i>&nbsp;<span class="text-muted">PENDENTES (p/ aprovação)</span></a></li>
            <li><a href="#tabs-eventos" data-toggle="tab"><i class="fa fa-book"></i>&nbsp;<span class="text-muted">MEUS EVENTOS</span></a></li>
            <li><a href="#tabs-novo" data-toggle="tab"><i class="fa fa-plus"></i>&nbsp;<span class="text-muted">NOVO EVENTO</span></a></li>
            <li><a href="#tabs-vencidos" data-toggle="tab"><i class="fa fa-bookmark"></i>&nbsp;<span class="text-muted">VENCIDOS / REJEITADOS (fora do prazo)</span></a></li>
        </ul>
    </div><!--Tab Header END-->
    
    <!--Tab Body-->
    <div class="clearfix tab-body profile-tabs content-tab">
        <!-- tabs content -->
        <div class="tab-content transparent body-tab">
              <div id="tab-pendentes" class="tab-pane active">
                  <h4 class="titulo col-sm-12 col-md-12 col-lg-12 text-center text-black"><b>Lista de Eventos Pendentes - Aguardando Aprovação</b></h4>
                  <table class="table table-bordered col-sm-12 col-md-12 col-lg-12" style="margin: 0px auto;">                      
                      <tr>
                          <th class="text-center" style="width:25%;">Solicitante</th>
                          <th class="text-center" style="width:40%;">Evento</th>
                          <th class="text-center" style="width:20%;">Período</th>
                          <th class="text-center" style="width:15%;">Ações</th>
                      </tr>                   
                    <?php
                        $listaPendentes ='';
                        if(count($this->arrayEventosPendentes) >0){
                            //lista os eventos pendentes
                            foreach ($this->arrayEventosPendentes as $dadosPendentes) {
                                $listaPendentes .= '<tr>';
                                $listaPendentes .= '<td>'.$dadosPendentes['solicitante'].'</td>';
                                $listaPendentes .= '<td>'.$dadosPendentes['titulo'].'</td>';
                                $listaPendentes .= '<td class="text-center"><b>'.$dadosPendentes['data_inicio'].'</b> à <b>'.$dadosPendentes['data_final'].'</b></td>';
                                $listaPendentes .= '<td class="text-center">'.$dadosPendentes['id_evento'].'</td>';
                                $listaPendentes .= '</tr>';
                            }//foreach lista de eventos
                        }else{
                            //Não existem eventos pendentes
                            $listaPendentes .= '<tr><td colspan="4" style="font-weight:bold; text-align:center;">Não existem eventos pendentes para aprovação.</td></tr>';
                        }                

                        echo $listaPendentes;
                    ?>
                 </table>
              </div>
            
              <div id="tabs-eventos" class="tab-pane">
                <p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
              </div>
            
              <div id="tabs-novo" class="tab-pane">
                <p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
                <p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
              </div>
            
              <div id="tabs-vencidos" class="tab-pane">
                <p>mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
                <p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
              </div>
        </div><!-- tabs content End-->    
    </div><!--Tab Body End-->
    
    
</div><!--Div de Conteúdo END-->