<?php if (count($this->lista) > 0) : ?>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered" width="99%">
        <thead>
            <tr>
                <th width="25" colspan="2"><span class="fa fa-gears"></span> Ações</th>
                <th>Nome do Cliente</th>
                <th>Tipo do Pagamento</th>
                <th>Plano</th>
                <th>Situação</th>
                <th>Pagamento</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <?php if (isset($this->lista)) : ?>
                <?php foreach ($this->lista as $lista) : ?>
            
                    <?php if ($lista['tpCliente'] == 1) : ?>
                    <?php   $Anunciante = $this->dadosAnuncianteHelper($lista['idCliente']); ?>
                    <?php   $noCliente = $lista['noCliente'] . " - <i>(" . $Anunciante['noArtistico'] . ")</i>"; ?>
                    <?php else: ?>
                    <?php   $noCliente = $lista['noCliente']; ?>
                    <?php endif; ?>
            
                    <tr>
                        <td style="text-align:center;">
                            <span onclick="selecionarPagamento(<?php echo $lista['idPagamento']; ?>);" title="Editar Pagamento" class="glyphicon glyphicon-pencil" style="cursor: pointer;"></span>
                        </td>
                        <td style="text-align:center;">
                            <span onclick="confirmarExcluirPagamento(<?php echo $lista['idPagamento']; ?>);" title="Remover Pagamento" class="glyphicon glyphicon-trash" style="cursor: pointer;"></span>
                        </td>
                        <td><?php echo $noCliente; ?></td>
                        <td><?php echo $this->masterHelper()->tpPagamento($lista['tpPagamento']); ?></td>
                        <td><?php echo $this->masterHelper()->tpPlano($lista['tpPlano']); ?></td>
                        <td><?php echo $this->masterHelper()->stPagamento($lista['stPagamento']); ?></td>
                        <td><?php echo $lista['dtPagamento'] ? $lista['dtPagamento']->format('d/m/Y') : ""; ?></td>
                        <td align="right"><?php echo "R$ " . str_replace('.', ',', $lista['vlPagamento']); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->lista, 'Sliding', 'partials/paginator', array('url' => 'pagamento/pesquisar/', 'parametros' => $this->parametros)); ?>
<?php endif; ?>

<?php if (count($this->lista) == 0) : ?>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered" width="99%">
        <tr>
            <td align="center">
                <strong>Nenhum registro foi encontrado!</strong>
            </td>
        </tr>
    </table>
    &nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;
<?php endif; ?>