<script type="text/javascript" src="<?php echo $this->basePath() . '/js/caracteristicas/caracteristicas.js'; ?>"></script>
<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <!-- breadcrumb -->
            <ul class="breadcrumb">
                <li><a href="<?php echo $this->basePath() . '/caracteristicas/' ?>">Administração</a></li>
                <li class="active">Parametros</li>
            </ul>
            <!-- /breadcrumb -->

            <!-- Page Title -->
            <h2>Controle de Características</h2>
            <!-- /Page Title -->
        </header>
    </div>
</section>
<!-- /PAGE TOP -->
<br />
<?php echo $this->partial('cad-caracteristicas'); ?>