<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/album.js'; ?>"></script>
<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">

        <header>

            <ul class="breadcrumb"><!-- breadcrumb -->
                <li class="active">Acompanhante</li>
                <li class="active">Meus Albúns</li>
            </ul><!-- /breadcrumb -->

            <h2><!-- Page Title -->
                Galeria de Fotos
            </h2><!-- /Page Title -->

        </header>

    </div>			
</section>
<!-- /PAGE TOP -->




<!-- CONTENT -->
<section>
    <div class="container">


        <h3><strong>Beauty</strong> View</h3><!-- grouped gallery - images only -->
        <div class="row lightbox" data-plugin-options='{"delegate": "a", "gallery": {"enabled": true}}'>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/a1.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/thumb/a1.jpg" alt="" />
                    </a>
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/a2.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/thumb/a2.jpg" alt="" />
                    </a>
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/a3.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/thumb/a3.jpg" alt="" />
                    </a>
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/a4.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/portfolio/thumb/a4.jpg" alt="" />
                    </a>
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/people/9.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/people/fixed-height/9.jpg" alt="" />
                    </a>
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/people/10.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/people/fixed-height/10.jpg" alt="" />
                    </a>
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/people/11.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/people/fixed-height/11.jpg" alt="" />
                    </a>
                </div>
            </div>

            <div class="col-sm-3 col-md-3">
                <div class="box-content thumbnail text-center">
                    <a href="<?php echo $this->basePath(); ?>/epona/images/demo/people/13.jpg" class="item-image">
                        <img class="img-responsive" src="<?php echo $this->basePath(); ?>/epona/images/demo/people/fixed-height/13.jpg" alt="" />
                    </a>
                </div>
            </div>

        </div>


        <hr class="half-margins invisible"/>

    </div>
</section>
<!-- /CONTENT -->