<?php

namespace Contato\Entity\Repository;

use Contato\Entity\AssuntoEntity;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

/**
 * AssuntoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssuntoRepository extends EntityRepository
{
    
    public function inserirAssunto($param = array()) 
    {
        $entity = new AssuntoEntity($param);
        
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }
    
    public function editarAssunto($param = array()) 
    {
        $entity = $this->getEntityManager()->getReference('Contato\Entity\AssuntoEntity', $param['id']);
        (new Hydrator\ClassMethods())->hydrate($param, $entity);
        
        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }
    
    public function excluirAssunto($repository) 
    {
        $this->getEntityManager()->remove($repository);
        $this->getEntityManager()->flush();
        return $repository;
    }
    
    public function selecionarAssunto($id) 
    {
        $repository = $this->find($id);
        return $repository;
    }
    
    public function selecionarAssuntoBy($param) 
    {
        $repository = $this->findBy($param);
        return $repository;
    }
    
    public function listarAssuntos($param = array(), $pagina = 1, $itens = 10) 
    {
        $queryCreate = $this->criarConsultaAssuntos($param);
        $paginado = new ORMPaginator($queryCreate->getQuery());
        $paginado->setUseOutputWalkers(FALSE);
        $adapter = new DoctrineAdapter($paginado);
        
        $paginator = new Paginator($adapter);
        $paginator->setDefaultItemCountPerPage($itens);
        $paginator->setCurrentPageNumber($pagina);
        return $paginator;
    }
    
    private function criarConsultaAssuntos($param = array()) 
    {
        $query = $this->getEntityManager()->createQueryBuilder();
        $query->select(array(
            'usu.id', 'usu.nome',
            'usu.email', 'usu.assunto'))
            ->from('Contato\Entity\AssuntoEntity', 'usu');
        if (!empty($param['nomePsq'])) {
            $query->andWhere("usu.nome LIKE :nome")
                    ->setParameter('nome', "{$param['nomePsq']}%");
        }
        if (!empty($param['emailPsq'])) {
            $query->andWhere("usu.email LIKE :email")
                    ->setParameter('email', "{$param['emailPsq']}%");
        }
        $query->addOrderBy('usu.registrado', 'DESC');
        
        return $query;
    }

}