<!-- CONTENT -->
<div id="cadCliente">

    <div class="container">

        <div class="row">
            <!-- LEFT -->
            <div class="col-lg-3 col-md-4">
                <!-- MENU -->
                <?php echo $this->partial('menu-vertical-cliente'); ?>
                <!-- /MENU -->
            </div>

            <!-- RIGHT -->
            <div class="col-lg-9 col-md-8">
                <div class="tab-content transparent">

                    <!-- SETTINGS TAB 1 -->
                    <div id="tab-s1" class="tab-pane active">
                        <?php echo $this->partial('cad-cliente'); ?>
                    </div>
                    <!-- /SETTINGS TAB 1 -->

                    <!-- SETTINGS TAB 2 -->
                    <div id="tab-s2" class="tab-pane">
                        <?php echo $this->partial('form-cad-anunciante'); ?>
                    </div>
                    <!-- /SETTINGS TAB 2 -->

                    <!-- SETTINGS TAB 3 -->
                    <div id="tab-s3" class="tab-pane">
                        <?php echo $this->partial('form-cad-cliente-caracteristica'); ?>
                    </div>
                    <!-- /SETTINGS TAB 3 -->

                    <!-- SETTINGS TAB 4 -->
                    <div id="tab-s4" class="tab-pane">
                        <?php echo $this->partial('form-config-pagina-cliente'); ?>
                    </div>
                    <!-- /SETTINGS TAB 4 -->

                    <!-- SETTINGS TAB 5 -->
                    <div id="tab-s5" class="tab-pane">
                        <?php echo $this->partial('form-cad-album-principal'); ?>
                    </div>
                    <!-- /SETTINGS TAB 5 -->

                    <!-- SETTINGS TAB 6 -->
                    <div id="tab-s6" class="tab-pane">
                        <?php echo $this->partial('form-cad-video'); ?>
                    </div>
                    <!-- /SETTINGS TAB 6 -->

                    <!-- SETTINGS TAB 7 -->
                    <div id="tab-s7" class="tab-pane">
                        <?php echo $this->partial('form-cad-cache'); ?>
                    </div>
                    <!-- /SETTINGS TAB 7 -->

                    <!-- SETTINGS TAB 8 -->
                    <div id="tab-s8" class="tab-pane">
                        <?php echo $this->partial('form-cad-pagamento-cliente'); ?>
                    </div>
                    <!-- /SETTINGS TAB 8 -->

                    <!-- SETTINGS TAB 9 -->
                    <div id="tab-s9" class="tab-pane">
                        <?php echo $this->partial('form-cad-depoimento'); ?>
                    </div>
                    <!-- /SETTINGS TAB 9 -->

                    <!-- SETTINGS TAB 10 -->
                    <div id="tab-s10" class="tab-pane">
                        <?php echo $this->partial('form-cad-album'); ?>
                    </div>
                    <!-- /SETTINGS TAB 10 -->

                    <?php if ($this->idClientePerfil != "") : ?>
                    <!-- SETTINGS TAB 11 -->
                    <div id="tab-s11" class="tab-pane">
                        <?php echo $this->partial('form-foto-perfil'); ?>
                    </div>
                    <!-- /SETTINGS TAB 11 -->

                    <!-- SETTINGS TAB 12 -->
                    <div id="tab-s12" class="tab-pane">
                        <?php echo $this->partial('form-alterar-senha'); ?>
                    </div>
                    <!-- /SETTINGS TAB 13 -->

                    <!-- SETTINGS TAB 14 -->
                    <div id="tab-s13" class="tab-pane">
                        <?php echo $this->partial('form-config-pagina-perfil'); ?>
                    </div>
                    <!-- /SETTINGS TAB 14 -->
                    <?php endif; ?>

                </div>

            </div>

        </div>

    </div>

</div>