<!-- CONTENT -->
<div id="psqCliente">

    <?php $formPsqCliente = $this->formPsqCliente; ?>
    <?php $formPsqCliente->prepare(); ?>

    <div class="container">

        <?php echo $this->form()->openTag($formPsqCliente); ?>

        <!-- BASIC FORM -->
        <div class="panel panel-light margin-bottom8">

            <div class="panel-heading">
                <h3 class="panel-title bold"> Pesquisar e Listar Clientes</h3>
            </div>

            <div class="panel-body">

                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" for="tpClientePsq">Tipo:</label>
                        <?php echo $this->formElement($formPsqCliente->get('tpClientePsq')); ?>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label" for="stClientePsq">Situação:</label>
                        <?php echo $this->formElement($formPsqCliente->get('stClientePsq')); ?>
                    </div>
                </div>

                <div class="row">
                    
                    <div class="form-group col-md-6">
                        <label class="control-label">Nome:</label>
                        <div class="input-group">
                            <?php echo $this->formElement($formPsqCliente->get('noClientePsq')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-user"></span>
                            </span>
                        </div>
                    </div>
                    
                    <div class="form-group col-md-6">
                        <label class="control-label">CPF:</label>
                        <div class="input-group">
                            <?php echo $this->formElement($formPsqCliente->get('nuCpfPsq')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-tag"></span>
                            </span>
                        </div>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label">UF:</label>
                        <?php echo $this->formElement($formPsqCliente->get('sgUfPsq')); ?>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label">Vencimento:</label>
                        <div class="input-group">
                            <?php echo $this->formElement($formPsqCliente->get('dtVencimentoPsq')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <?php echo $this->formButton()->openTag($formPsqCliente->get('btnPesquisarCliente')); ?>
                        <?php echo '<i class="fa fa-search"></i>' . $formPsqCliente->get('btnPesquisarCliente')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>

                        <?php echo $this->formButton()->openTag($formPsqCliente->get('btnNovoCliente')); ?>
                        <?php echo '<i class="fa fa-plus"></i>' . $formPsqCliente->get('btnNovoCliente')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>

                        <?php echo $this->formButton()->openTag($formPsqCliente->get('btnVoltarCliente')); ?>
                        <?php echo '<i class="fa fa-arrow-left"></i>' . $formPsqCliente->get('btnVoltarCliente')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>
                    </div>
                </div>
                <!-- end cut -->

            </div>

        </div>
        <!-- /BASIC FORM -->

        <div id="tableClientes"></div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
    <!-- /CONTENT -->

</div>