<script>
    $(document).ready(function () {
        $('#header').hide();
        $('#menu-horizontal').hide();
        $('#banner-principal').hide();
        $('#footer').hide();
    });
</script>

<!-- REVOLUTION SLIDER -->
<div class="slider fullwidthbanner-container roundedcorners">
    <div class="fullwidthbanner thumb-small">
        <ul class="hide">

            <!-- SLIDE  1-->
            <li data-transition="fade" data-slotamount="14"  data-masterspeed="300" data-delay="10000" data-thumb="<?php echo $this->basePath() . '/storage/fotos/2/3/fd9443c0e12bad2dc3ab045194f87835.jpg' ?>">

                <img src="../../epona/images/1x1.png" data-lazyload="<?php echo $this->basePath() . '/storage/fotos/2/3/fd9443c0e12bad2dc3ab045194f87835.jpg' ?>" alt="" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />

                <div class="tp-caption medium_text lfl stl"
                     data-x="60"
                     data-y="200"
                     data-speed="300"
                     data-start="500"
                     data-easing="easeOutExpo">DO YOU NEED A NEW
                </div>

                <div class="tp-caption large_bold_white sft stb"
                     data-x="60"
                     data-y="223"
                     data-speed="300"
                     data-start="1000"
                     data-easing="easeOutExpo">WEB DESIGN?
                </div>

                <div class="tp-caption small_light_white sft stb"
                     data-x="76"
                     data-y="286"
                     data-speed="500"
                     data-start="2000"
                     data-easing="easeOutExpo">Check Epona included features and options
                </div>

                <div class="tp-caption sft medium_light_white" 
                     data-x="600" 
                     data-y="60" 
                     data-speed="600" 
                     data-start="1500" 
                     data-easing="easeOutExpo"><img src="../../epona/images/demo/desktop_slider.png" alt="" />
                </div>
            </li>

            <!-- SLIDE  2 -->
            <li data-transition="fade" data-slotamount="14"  data-masterspeed="300" data-delay="10000" data-thumb="<?php echo $this->basePath() . '/storage/fotos/3/2/83ee1d8a2409ccec9e3d42ba2423747c.jpg' ?>">

                <img src="../../epona/images/1x1.png" data-lazyload="<?php echo $this->basePath() . '/storage/fotos/3/2/83ee1d8a2409ccec9e3d42ba2423747c.jpg' ?>" alt="" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />

                <div class="tp-caption lft boxshadow" 
                     data-x="70" 
                     data-y="70" 
                     data-speed="900" 
                     data-start="500" 
                     data-easing="easeOutBack">
                    <iframe src='http://player.vimeo.com/video/93972085?title=0&amp;byline=0&amp;portrait=0;api=1' width='640' height='360'></iframe>
                </div>

                <div class="tp-caption sft large_bold_white" 
                     data-x="750" 
                     data-y="57" 
                     data-speed="300" 
                     data-start="1200" 
                     data-easing="easeOutExpo">THE FUTURE
                </div>

                <div class="tp-caption lfb medium_light_white" 
                     data-x="750" 
                     data-y="180" 
                     data-speed="300" 
                     data-start="1400" 
                     data-easing="easeOutExpo">&bull; Revolution Slider <span class="line-through">$14</span>
                </div>

                <div class="tp-caption lfb medium_light_white" 
                     data-x="750" 
                     data-y="214" 
                     data-speed="300" 
                     data-start="1700" 
                     data-easing="easeOutExpo">&bull; Layer Slider <span class="line-through">$12</span>
                </div>

                <div class="tp-caption lfb medium_light_white" 
                     data-x="750" 
                     data-y="254" 
                     data-speed="300" 
                     data-start="2000" 
                     data-easing="easeOutExpo">&bull; Sky Forms <span class="line-through">$5</span>
                </div>

                <div class="tp-caption lfb medium_bg_darkblue" 
                     data-x="750" 
                     data-y="390" 
                     data-speed="300" 
                     data-start="2300" 
                     data-easing="easeOutExpo"><i class="fa fa-road"></i>
                </div>

                <div class="tp-caption lfb medium_bg_asbestos" 
                     data-x="791" 
                     data-y="390" 
                     data-speed="300" 
                     data-start="1600" 
                     data-easing="easeOutExpo">YOU KNOW YOU WANT IT
                </div>
            </li>

            <!-- SLIDE 3  -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-link="http://www.stepofweb.com/" data-target="_blank" data-saveperformance="off" data-thumb="<?php echo $this->basePath() . '/storage/fotos/1/1/banner-mulher-melao.png' ?>">

                <img src="../../epona/images/1x1.png" data-lazyload="<?php echo $this->basePath() . '/storage/fotos/1/1/banner-mulher-melao.png' ?>" alt="" data-bgfit="cover" data-bgposition="center bottom" data-bgrepeat="no-repeat" />

                <div class="tp-caption sft medium_light_white" 
                     data-x="right" 
                     data-y="bottom" data-voffset="100"
                     data-speed="1000" 
                     data-start="1000" 
                     data-easing="easeOutExpo"><img src="http://theme.stepofweb.com/Epona/v1.3/HTML/assets/images/demo/layerslider/slide-b-4.png" alt="" />
                </div>

                <div class="tp-caption sft medium_light_white" 
                     data-x="right"  data-hoffset="-145"
                     data-y="430" 
                     data-speed="1000" 
                     data-start="1500" 
                     data-easing="easeOutExpo"><img src="http://theme.stepofweb.com/Epona/v1.3/HTML/assets/images/demo/layerslider/bi-colored-butterfly-source_ijc.gif" alt="" />
                </div>

                <div class="tp-caption block_black sfl tp-resizeme" 
                     data-x="70" 
                     data-y="272" 
                     data-speed="750" 
                     data-start="1000" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Epona Multipurpose Template
                </div>

                <div class="tp-caption block_black sfl tp-resizeme" 
                     data-x="70" 
                     data-y="316" 
                     data-speed="750" 
                     data-start="1400" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Loaded With Options, And Is Simply A Joy To Use
                </div>

                <div class="tp-caption block_black sfr tp-resizeme" 
                     data-x="70" 
                     data-y="360" 
                     data-speed="750" 
                     data-start="1800" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Premium Sliders That Are Easy To Use With Any Content
                </div>

            </li>

            <!-- SLIDE 4  -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-saveperformance="off" data-thumb="../../epona/images/demo/flickr_37.jpg">

                <img src="../../epona/images/1x1.png" data-lazyload="../../epona/images/demo/flickr_37.jpg" alt="" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat" />

                <div class="tp-caption mediumlarge_light_white lfb tp-resizeme" 
                     data-x="left" data-hoffset="70"
                     data-y="133" 
                     data-speed="1000" 
                     data-start="1400" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">+ Amazing Layouts
                </div>

                <div class="tp-caption mediumlarge_light_white lft tp-resizeme" 
                     data-x="left" data-hoffset="70"
                     data-y="85" 
                     data-speed="1000" 
                     data-start="1200" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">+ Awesome  Sliders
                </div>

                <div class="tp-caption block_black sfl tp-resizeme" 
                     data-x="70" 
                     data-y="216" 
                     data-speed="750" 
                     data-start="1900" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Premium Sliders That Are Easy To Use With Any Content
                </div>

                <div class="tp-caption block_black sfr tp-resizeme" 
                     data-x="70" 
                     data-y="260" 
                     data-speed="750" 
                     data-start="2200" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Loaded With Options, And Is Simply A Joy To Use
                </div>

            </li>

            <!-- SLIDE 5  -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-link="http://www.stepofweb.com/" data-target="_blank" data-saveperformance="off" >

                <img src="../../epona/images/1x1.png" data-lazyload="../../epona/images/demo/flickr_9.jpg" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" />

                <div class="tp-caption block_black sfl tp-resizeme" 
                     data-x="70" 
                     data-y="172" 
                     data-speed="750" 
                     data-start="1000" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Epona Multipurpose Template
                </div>

                <div class="tp-caption block_black sfl tp-resizeme" 
                     data-x="70" 
                     data-y="216" 
                     data-speed="750" 
                     data-start="1400" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Loaded With Options, And Is Simply A Joy To Use
                </div>

                <div class="tp-caption block_black sfr tp-resizeme" 
                     data-x="70" 
                     data-y="260" 
                     data-speed="750" 
                     data-start="1800" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">Premium Sliders That Are Easy To Use With Any Content
                </div>

            </li>

            <!-- SLIDE 6 -->
            <li data-transition="fade" data-slotamount="14"  data-masterspeed="300" data-delay="10000">

                <img src="../../epona/images/1x1.png" data-lazyload="../../epona/images/demo/blue.jpg" alt="" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />

                <div class="tp-caption medium_text lfl stl"
                     data-x="60"
                     data-y="200"
                     data-speed="300"
                     data-start="500"
                     data-easing="easeOutExpo">DO YOU NEED A NEW
                </div>

                <div class="tp-caption large_bold_white sft stb"
                     data-x="60"
                     data-y="223"
                     data-speed="300"
                     data-start="1000"
                     data-easing="easeOutExpo">WEB DESIGN?
                </div>

                <div class="tp-caption small_light_white sft stb"
                     data-x="76"
                     data-y="286"
                     data-speed="500"
                     data-start="2000"
                     data-easing="easeOutExpo">Check Epona included features and options
                </div>

                <div class="tp-caption sft medium_light_white" 
                     data-x="600" 
                     data-y="60" 
                     data-speed="600" 
                     data-start="1500" 
                     data-easing="easeOutExpo"><img src="../../epona/images/demo/desktop_slider.png" alt="" />
                </div>

            </li>

            <!-- SLIDE 7 -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-saveperformance="off" >

                <img src="../../epona/images/1x1.png" data-lazyload="../../epona/images/demo/wall.jpg" alt="" data-bgfit="cover" data-bgposition="center top" data-bgrepeat="no-repeat" />

                <div class="tp-caption block_black lfb tp-resizeme" 
                     data-x="center"
                     data-y="80"  
                     data-speed="1000" 
                     data-start="500" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">EPONA INCLUDES
                </div>

                <div class="tp-caption block_huge text-white lfb tp-resizeme" 
                     data-x="center"
                     data-y="130"  
                     data-speed="1000" 
                     data-start="800" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">EVERYTHING 
                </div>

                <div class="tp-caption block_black lfb tp-resizeme" 
                     data-x="center"
                     data-y="280"  
                     data-speed="1000" 
                     data-start="1200" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300">you need to build incredible page layouts 
                </div>

                <div class="tp-caption lfb tp-resizeme" 
                     data-x="center"
                     data-y="350"  
                     data-speed="1200" 
                     data-start="2000" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300"><a href="#purchase" class="btn btn-primary">PURCHASE NOW</a>
                </div>

            </li>

            <!-- SLIDE 8 -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off" >

                <img src="../../epona/images/1x1.png" data-lazyload="../../epona/images/demo/wall2.jpg" alt="" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />

                <div class="tp-caption lfr" 
                     data-x="left" data-hoffset="60"
                     data-y="25" 
                     data-speed="1500" 
                     data-start="500" 
                     data-easing="easeOutExpo" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 2;">
                    <img src="../../epona/images/1x1.png" alt="" data-lazyload="<?php echo $this->basePath() . '/epona/images/demo/ipad.png' ?>">
                </div>

                <div class="tp-caption block_black sft" 
                     data-x="right" data-hoffset="-70"
                     data-y="87" 
                     data-speed="750" 
                     data-start="1100" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;">Epona Template
                </div>

                <div class="tp-caption block_black sfb" 
                     data-x="right" data-hoffset="-70" 
                     data-y="126" 
                     data-speed="750" 
                     data-start="1400" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 4; max-width: auto; max-height: auto; white-space: nowrap;">100% Fully Responisve
                </div>

                <div class="tp-caption block_styleColor sft" 
                     data-x="right"  data-hoffset="-70"
                     data-y="189" 
                     data-speed="750" 
                     data-start="1700" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 5; max-width: auto; max-height: auto; white-space: nowrap;">With Incredible
                </div>

                <div class="tp-caption block_styleColor sfb" 
                     data-x="right"  data-hoffset="-70"
                     data-y="228" 
                     data-speed="750" 
                     data-start="2000" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 6; max-width: auto; max-height: auto; white-space: nowrap;">Additions &amp; Optimizations
                </div>

                <div class="tp-caption block_black sft" 
                     data-x="right"  data-hoffset="-70"
                     data-y="290" 
                     data-speed="750" 
                     data-start="2300" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 7; max-width: auto; max-height: auto; white-space: nowrap;">For Your Next Projects
                </div>
            </li>

            <!-- SLIDE 09 -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-link="http://www.stepofweb.com/" data-target="_blank" data-saveperformance="off" >

                <img src="../../epona/images/1x1.png" data-lazyload="../../epona/images/demo/wall2.jpg" alt="" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />

                <div class="tp-caption lfb" 
                     data-x="right"
                     data-y="40" 
                     data-speed="2000" 
                     data-start="500" 
                     data-easing="easeOutExpo" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 2;">
                    <img src="../../epona/images/1x1.png" alt="" data-lazyload="<?php echo $this->basePath() . '/epona/images/demo/desktop.png' ?>">
                </div>

                <div class="tp-caption medium_thin_grey lfb tp-resizeme" 
                     data-x="left" data-hoffset="70"
                     data-y="133" 
                     data-speed="1000" 
                     data-start="1400" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;">+ Amazing Layouts
                </div>

                <div class="tp-caption medium_thin_grey lft tp-resizeme" 
                     data-x="left" data-hoffset="150"
                     data-y="85" 
                     data-speed="1000" 
                     data-start="1200" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 4; max-width: auto; max-height: auto; white-space: nowrap;">+ Awesome  Sliders
                </div>

                <div class="tp-caption block_black sfl tp-resizeme" 
                     data-x="70" 
                     data-y="216" 
                     data-speed="750" 
                     data-start="1900" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 5; max-width: auto; max-height: auto; white-space: nowrap;">100% Fully Responsive
                </div>

                <div class="tp-caption block_styleColor sfr tp-resizeme" 
                     data-x="120" 
                     data-y="260" 
                     data-speed="750" 
                     data-start="2200" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 6; max-width: auto; max-height: auto; white-space: nowrap;">And Simply A Joy To Use
                </div>

                <div class="tp-caption block_black sfb tp-resizeme" 
                     data-x="170" 
                     data-y="306" 
                     data-speed="750" 
                     data-start="2500" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 7; max-width: auto; max-height: auto; white-space: nowrap;">Why Not Buy Epona?
                </div>
            </li>

            <!-- SLIDE 10 -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-link="http://www.stepofweb.com/" data-target="_blank" data-saveperformance="off" >

                <img src="../../epona/images/1x1.png" data-lazyload="../../epona/images/demo/wall.jpg" alt="" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />

                <div class="tp-caption lfb" 
                     data-x="right" data-hoffset="-70" 
                     data-y="70" 
                     data-speed="2000" 
                     data-start="500" 
                     data-easing="easeOutExpo" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 2;">
                    <img src="../../epona/images/1x1.png" alt="" data-lazyload="../../epona/images/demo/desktop_slider.png">
                </div>

                <div class="tp-caption mediumlarge_light_white lfb tp-resizeme" 
                     data-x="left" data-hoffset="150"
                     data-y="133" 
                     data-speed="1000" 
                     data-start="1400" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 3; max-width: auto; max-height: auto; white-space: nowrap;">+ Amazing Layouts
                </div>

                <div class="tp-caption mediumlarge_light_white lft tp-resizeme" 
                     data-x="left" data-hoffset="70"
                     data-y="85" 
                     data-speed="1000" 
                     data-start="1200" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 4; max-width: auto; max-height: auto; white-space: nowrap;">+ Awesome  Sliders
                </div>

                <div class="tp-caption block_white sfl tp-resizeme" 
                     data-x="70" 
                     data-y="216" 
                     data-speed="750" 
                     data-start="1900" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 5; max-width: auto; max-height: auto; white-space: nowrap;">100% Fully Responsive
                </div>

                <div class="tp-caption block_styleColor sfr tp-resizeme" 
                     data-x="120" 
                     data-y="260" 
                     data-speed="750" 
                     data-start="2200" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 6; max-width: auto; max-height: auto; white-space: nowrap;">And Simply A Joy To Use
                </div>

                <div class="tp-caption block_white sfb tp-resizeme" 
                     data-x="170" 
                     data-y="306" 
                     data-speed="750" 
                     data-start="2500" 
                     data-easing="easeOutExpo" 
                     data-splitin="none" 
                     data-splitout="none" 
                     data-elementdelay="0.1" 
                     data-endelementdelay="0.1" 
                     data-endspeed="300" 
                     style="z-index: 7; max-width: auto; max-height: auto; white-space: nowrap;">Why Not Buy Epona?
                </div>
            </li>                                                

        </ul>
        <div class="tp-bannertimer"></div>
    </div>
</div>
<!-- /REVOLUTION SLIDER -->

<div class="container">

    <div class="row">
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner01.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 01</a>
        </div>
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner06.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 06</a>
        </div>
        
    </div>
    
    <div class="row">
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner02.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 02</a>
        </div>
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner07.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 07</a>
        </div>
        
    </div>
    
    <div class="row">
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner03.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 03</a>
        </div>
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner08.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 08</a>
        </div>
        
    </div>
    
    <div class="row">
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner04.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 04</a>
        </div>
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner09.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 09</a>
        </div>
        
    </div>
    
    <div class="row">
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner05.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 05</a>
        </div>
        
        <div class="col col-md-6 text-center">
            <a href="../../txt/banner10.txt" target="_blank"><i class="fa fa-desktop"></i>&nbsp;Código Banner 10</a>
        </div>
        
    </div>
    
</div>