<script>
    top.idCliente = '<?php echo $this->idCliente; ?>';
</script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/simpleUpload.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/banner/banner.js'; ?>"></script>

<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="<?php echo $this->basePath() . '/perfil/' ?>">Administração</a></li>
                <li class="active">Banners</li>
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                Controle de Banners
            </h2><!-- /Page Title -->
        </header>
    </div>			
</section>
<!-- /PAGE TOP -->

<br />

<div class="container">
    <?php echo $this->partial('psq-banner'); ?>
    <?php echo $this->partial('cad-banner'); ?>
</div>