<!--CLASSES DE EVENTOS-->
<style type="text/css">    
    /********************************************************************
     ********************** Layout Esquerdo *****************************
     ********************************************************************/
    .layout_esquerdo{
        width: 100%;
        margin: 10px auto auto 10px;
        padding: 10px;
    }
    .layout_esquerdo .titulo{
        width: 100%;
        height: 30px;
        font-weight: bold;
        text-align: center;        
        margin-bottom: 10px;
        padding: 5px;     
        
        border-radius: 30px 30px 0px 0px;
        -moz-border-radius: 30px 30px 0px 0px;
        -webkit-border-radius: 30px 30px 0px 0px; 
        
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#1e5799+10,1e5799+12,2989d8+53,1e5799+80&0+0,0.8+0,1+19,1+81,0.8+99,0+100 */
        background: -moz-linear-gradient(top,  rgba(30,87,153,0.8) 0%, rgba(30,87,153,0.91) 10%, rgba(30,87,153,0.93) 12%, rgba(32,96,164,1) 19%, rgba(41,137,216,1) 53%, rgba(30,87,153,1) 80%, rgba(30,87,153,1) 81%, rgba(30,87,153,0.8) 99%, rgba(30,87,153,0) 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top,  rgba(30,87,153,0.8) 0%,rgba(30,87,153,0.91) 10%,rgba(30,87,153,0.93) 12%,rgba(32,96,164,1) 19%,rgba(41,137,216,1) 53%,rgba(30,87,153,1) 80%,rgba(30,87,153,1) 81%,rgba(30,87,153,0.8) 99%,rgba(30,87,153,0) 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom,  rgba(30,87,153,0.8) 0%,rgba(30,87,153,0.91) 10%,rgba(30,87,153,0.93) 12%,rgba(32,96,164,1) 19%,rgba(41,137,216,1) 53%,rgba(30,87,153,1) 80%,rgba(30,87,153,1) 81%,rgba(30,87,153,0.8) 99%,rgba(30,87,153,0) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#cc1e5799', endColorstr='#001e5799',GradientType=0 ); /* IE6-9 */
    }
    .layout_esquerdo .foto{
        float: left;
        width: 20%;
        margin-right:10px;         
        text-align: center;
    }
    .layout_esquerdo .foto img{         
        overflow: hidden;        
        border-radius: 0px 30px 0px 30px;
        -moz-border-radius: 0px 30px 0px 30px;
        -webkit-border-radius: 0px 30px 0px 30px;
    }
    .layout_esquerdo .descricao{
        float: right;
        width: 45%;        
        font-size: 14px;
        text-align: center;
        font-family: monospace;
        
        background: rgba(73,39,119, 0.7);
        border-radius: 0% 0% 26% 26%/50% 50% 26% 26%; 
        -webkit-border-radius: 0% 0% 26% 26%/50% 50% 26% 26%; 
        -moz-border-radius: 0% 0% 26% 26%/50% 50% 26% 26%;
    }
   .layout_esquerdo .datas{
        float: left;
        width: 30%;        
        font-size: 12px; 
        text-align: left;
        margin-top: 15px;
    }
    .layout_esquerdo .datas table tr th{               
        text-align: center;
        background: #A0A0A0;
        color: #000;
        width: 40px;
        font-size: 14px;
    }  
   .layout_esquerdo .rodape{
        width: 100%;
        font-size: 14px;
        text-align: center;
        padding: 5px;
        margin: 10px auto;
        font-weight: bold;
        color: #000 !important;
        
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#1e5799+10,1e5799+12,2989d8+53,1e5799+80&0+0,0.8+0,1+19,1+81,0.8+99,0+100 */
        background: -moz-linear-gradient(top,  rgba(30,87,153,0.8) 0%, rgba(30,87,153,0.91) 10%, rgba(30,87,153,0.93) 12%, rgba(32,96,164,1) 19%, rgba(41,137,216,1) 53%, rgba(30,87,153,1) 80%, rgba(30,87,153,1) 81%, rgba(30,87,153,0.8) 99%, rgba(30,87,153,0) 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top,  rgba(30,87,153,0.8) 0%,rgba(30,87,153,0.91) 10%,rgba(30,87,153,0.93) 12%,rgba(32,96,164,1) 19%,rgba(41,137,216,1) 53%,rgba(30,87,153,1) 80%,rgba(30,87,153,1) 81%,rgba(30,87,153,0.8) 99%,rgba(30,87,153,0) 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom,  rgba(30,87,153,0.8) 0%,rgba(30,87,153,0.91) 10%,rgba(30,87,153,0.93) 12%,rgba(32,96,164,1) 19%,rgba(41,137,216,1) 53%,rgba(30,87,153,1) 80%,rgba(30,87,153,1) 81%,rgba(30,87,153,0.8) 99%,rgba(30,87,153,0) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#cc1e5799', endColorstr='#001e5799',GradientType=0 ); /* IE6-9 */
        
        border-radius: 0px 0px 30px 30px;
        -moz-border-radius: 0px 0px 30px 30px;
        -webkit-border-radius: 0px 0px 30px 30px;
    }
    .layout_esquerdo .rodape a:hover
    {
        color: #F9A2A2 !important;
        text-decoration: none;       
    }   
    
    
    /********************************************************************
     ********************** Layout Direito ******************************
     ********************************************************************/
    .layout_direito{
        width: 100%;
        margin: 10px 10px auto auto;
        padding: 10px;        
    }
    .layout_direito .titulo{
        width: 100%;
        height: 30px;
        font-weight: bold;
        text-align: center;        
        margin-bottom: 10px;
        padding: 5px;        
        
        /*Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f3c5bd+0,e86c57+50,ea2803+51,ff6600+75,c72200+100;Red+Gloss */
        /*background: #f3c5bd; /* Old browsers */
        /*background: -moz-linear-gradient(top, #f3c5bd 0%, #e86c57 50%, #ea2803 51%, #ff6600 75%, #c72200 100%); /* FF3.6-15 */
        /*background: -webkit-linear-gradient(top, #f3c5bd 0%,#e86c57 50%,#ea2803 51%,#ff6600 75%,#c72200 100%); /* Chrome10-25,Safari5.1-6 */
        /*background: linear-gradient(to bottom, #f3c5bd 0%,#e86c57 50%,#ea2803 51%,#ff6600 75%,#c72200 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        /*filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3c5bd', endColorstr='#c72200',GradientType=0 ); /* IE6-9 */
        
        border-radius: 30px 30px 0px 0px;
        -moz-border-radius: 30px 30px 0px 0px;
        -webkit-border-radius: 30px 30px 0px 0px;        
        
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0b7a1+0,8c3310+50,752201+51,bf6e4e+100;Brown+Gloss */
        background: #f0b7a1; /* Old browsers */
        background: -moz-linear-gradient(top,  #f0b7a1 0%, #8c3310 50%, #752201 51%, #bf6e4e 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top,  #f0b7a1 0%,#8c3310 50%,#752201 51%,#bf6e4e 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom,  #f0b7a1 0%,#8c3310 50%,#752201 51%,#bf6e4e 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0b7a1', endColorstr='#bf6e4e',GradientType=0 ); /* IE6-9 */
    }    
    .layout_direito .foto{
        float: right;
        width: 20%;
        margin-left:10px; 
        text-align: center;       
    }
    .layout_direito .foto img{         
        overflow: hidden;        
        border-radius: 0px 30px 0px 30px;
        -moz-border-radius: 0px 30px 0px 30px;
        -webkit-border-radius: 0px 30px 0px 30px;
    }
    .layout_direito .descricao{
        float: left;
        width: 45%;         
        font-size: 14px;
        text-align: center;
        font-family: monospace;
        
        background: rgba(73,39,119, 0.7);
        border-radius: 0% 0% 26% 26%/50% 50% 26% 26%; 
        -webkit-border-radius: 0% 0% 26% 26%/50% 50% 26% 26%; 
        -moz-border-radius: 0% 0% 26% 26%/50% 50% 26% 26%;
    }        
    .layout_direito .datas{
        float: right;
        width: 30%;        
        font-size: 12px; 
        text-align: center;
        margin-top: 15px;
    }
    .layout_direito .datas table tr th{               
        text-align: center;
        background: #A0A0A0;
        color: #000;
        width: 40px;
        font-size: 14px;
    }  
    .layout_direito .rodape{
        width: 100%;
        font-size: 14px;
        text-align: center;
        padding: 5px;
        margin: 10px auto;
        font-weight: bold;
        color: #000 !important;
        
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f3c5bd+0,e86c57+50,ea2803+51,ff6600+75,c72200+100;Red+Gloss */
        /*background: #f3c5bd; /* Old browsers */
        /*background: -moz-linear-gradient(top, #f3c5bd 0%, #e86c57 50%, #ea2803 51%, #ff6600 75%, #c72200 100%); /* FF3.6-15 */
        /*background: -webkit-linear-gradient(top, #f3c5bd 0%,#e86c57 50%,#ea2803 51%,#ff6600 75%,#c72200 100%); /* Chrome10-25,Safari5.1-6 */
        /*background: linear-gradient(to bottom, #f3c5bd 0%,#e86c57 50%,#ea2803 51%,#ff6600 75%,#c72200 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        /*filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f3c5bd', endColorstr='#c72200',GradientType=0 ); /* IE6-9 */

        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0b7a1+0,8c3310+50,752201+51,bf6e4e+100;Brown+Gloss */
        background: #f0b7a1; /* Old browsers */
        background: -moz-linear-gradient(top,  #f0b7a1 0%, #8c3310 50%, #752201 51%, #bf6e4e 100%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top,  #f0b7a1 0%,#8c3310 50%,#752201 51%,#bf6e4e 100%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom,  #f0b7a1 0%,#8c3310 50%,#752201 51%,#bf6e4e 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0b7a1', endColorstr='#bf6e4e',GradientType=0 ); /* IE6-9 */
        
        border-radius: 0px 0px 30px 30px;
        -moz-border-radius: 0px 0px 30px 30px;
        -webkit-border-radius: 0px 0px 30px 30px;
    }
    .layout_direito .rodape a:hover
    {
        color: #F9A2A2 !important;
        text-decoration: none;       
    }   
    
    /***************************************************************************
     ********** Link para Ver o Evento com Detalhes ****************************
     **************************************************************************/    
    .font_link 
    {
        color: rgb(255,255,255);
        font-size: 20px;
        text-shadow: rgb(255,255,255) 1px 1px 0px;
    }      
    
    /***************************************************************************
     ************ Borda para Separar os eventos ********************************
     **************************************************************************/
    .borda_separar{
         border: 1px solid #FFF;
         text-shadow: #000000 0px;
    }
</style>


<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li>Agenda de Eventos</li>                
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                <b>Agenda de Eventos</b> - Modelos & Parceiros Clube Luxúria
            </h2><!-- /Page Title -->
        </header>        
        
        <!--Lista de Eventos-->
        <div class="col-sm-12">
            
            <?php 
            //Lista de eventos a serem mostrados
            if(count($this->arrayEventos) > 0){
                $layout = 'esquerdo';
                foreach ($this->arrayEventos as $dados) {
                    $layout = $layout == 'esquerdo' ? 'direito' : 'esquerdo';
                    
                    //Bloco de informação da Agenda
                    echo '<div class="layout_'.$layout.'">';
                    
                    //Título do Evento
                    echo '<div class="titulo"><div class="font_link">'.$dados["titulo"].'</div></div>';
                    
                    //Foto
                    $arrayFotos = $dados['fotos'];
                    $foto = count($arrayFotos)>0 ? $arrayFotos['nome'] : 'no-photo.png';
                    echo '<div class="foto">';
                    echo '<img src="/storage/agenda/'.$foto.'" width="170px"/>';
                    echo '</div>';
                                 
                    //Descrição do Evento
                    echo '<div class="descricao">';
                    $tamMaxString = 250;
                    echo '<br>'.(strlen($dados['descricao']) > $tamMaxString ? substr($dados['descricao'],0,$tamMaxString).'...' : $dados['descricao']).'<br><br><br>';
                    echo '</div>';//End descrição

                    //Dias do evento
                    //Datas do Evento
                    echo '<div class="datas">';
                    $arrayData = $dados['datas'] ;                                                            
                    if(count($arrayData) >0){
                        echo '<table style="width:100%;"><tr>';
                        echo '<th style="border:1px solid #FFF;" colspan="3">Dias e Horários do Evento</th>';
                        echo '</tr>';
                        foreach($arrayData as $dadosData){
                            echo '<tr style="border:1px solid #FFF;"><td style="width:33%;border-right:1px solid #FFF;">'.$dadosData['mes'].'</td>';
                            echo '<td style="width:33%; border-right:1px solid #FFF;">'.$dadosData['semana'].'</td>';
                            echo '<td style="width:34%;">'.$dadosData['hora_ini'].' - '.$dadosData['hora_fim'].'</td></tr>';
                        }//foreach Data                        
                        echo '</table>';
                    }//if data               
                    echo '</div>';//End Datas
                    
                    //Retirando os floats
                    echo '<div style="clear: both;"></div>';
                    
                    //Rodapé
                    echo '<div class="rodape"><a href="agenda/ver-envento/" title=".::Clique e Saiba Mais::.">>> VER MAIS DETALHES DO EVENTO <<</a></div>';
                    
                    //Finalizando bloco                    
                    echo '</div>';//Bloco do Evento END                                                               
                    //echo '<div style="clear: both;"></div>';
                   
                    echo '<div class="borda_separar"></div>';
                    
                }//foreach array de eventos
            }else{
                echo '<div style="width:100%;text-align:center;padding:10px;">Nenhum evento cadastrado na agenda.</div>';
            }//if / else array de eventos
            ?>
      
        </div><!--Lista de Eventos-->
        
        
    </div>			
</section>
<!-- /PAGE TOP -->




