<!--CLASSES DE EVENTOS-->
<style type="text/css">
    /*
     * Layout Esquerdo
     */
    .layout_esquerdo{
        width: 100%;
        margin: 10px auto auto 10px;
        padding: 10px;
    }
    .layout_esquerdo .titulo{
        width: 80%;
        height: 30px;
        font-weight: bold;
        text-align: center;
        color: #8E8D8D;
        font-size: 18px;
    }
    .layout_esquerdo .foto{
        float: left;
        width: 20%;
        margin-right:10px;         
        text-align: left;
    }
    .layout_esquerdo .descricao{
        float: right;
        width: 70%;
        margin-right:10px; 
        font-size: 12px;
        text-align: center;
    }
    .layout_esquerdo .descricao table{
        margin-top:15px;
        font-size: 11px;
    }
   .layout_esquerdo .descricao table tr th{               
        text-align: center;
        background: #A0A0A0;
        color: #000;
        width: 40px;
        font-size: 14px;
    }
    .layout_esquerdo .descricao table tr td{        
        text-align: center;
    }
    
    /*
     * Layout Direito
     */
    .layout_direito{
        width: 100%;
        margin: 10px 10px auto auto;
        padding: 10px;        
    }
    .layout_direito .titulo{
        width: 80%;
        height: 30px;
        font-weight: bold;
        text-align: center;
        color: #8E8D8D;   
        font-size: 18px;
    }
    .layout_direito .foto{
        float: right;
        width: 20%;
        margin-left:10px; 
        text-align: center;       
    }
    .layout_direito .foto img{         
        overflow: hidden;
        border-radius: 0px 30px 0px 30px;
        -moz-border-radius: 0px 30px 0px 30px;
        -webkit-border-radius: 0px 30px 0px 30px;
        border: 1px solid #5E0000;
    }
    .layout_direito .descricao{
        float: left;
        width: 45%;         
        font-size: 12px;
        text-align: center;
    }    
    .layout_direito .descricao table tr td{               
        text-align: center;
    }
    .layout_direito .datas{
        float: right;
        width: 30%;        
        font-size: 12px; 
        text-align: center;
        margin-top: 15px;
    }
    .layout_direito .datas table tr th{               
        text-align: center;
        background: #A0A0A0;
        color: #000;
        width: 40px;
        font-size: 14px;
    }    
    
    /*
     * Borda para Separar os eventos
     */
    .borda_separar{
         border: 1px solid #FFF;
    }
</style>


<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li>Agenda de Eventos</li>                
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                <b>Agenda de Eventos</b> - Modelos & Parceiros Clube Luxúria
            </h2><!-- /Page Title -->
        </header>        
        
        <!--Lista de Eventos-->
        <div class="col-sm-12">
            
            <?php 
            //Lista de eventos a serem mostrados
            if(count($this->arrayEventos) > 0){
                $layout = 'esquerdo';
                foreach ($this->arrayEventos as $dados) {
                    $layout = $layout == 'esquerdo' ? 'direito' : 'esquerdo';
                    
                    //Bloco de informação da Agenda
                    echo '<div class="layout_'.$layout.'">';
                    
                    //Título do Evento
                    echo '<div class="titulo">'.$dados["titulo"].'</div>';
                    
                    //Foto
                    $arrayFotos = $dados['fotos'];
                    $foto = count($arrayFotos)>0 ? $arrayFotos['nome'] : 'no-photo.png';
                    echo '<div class="foto">';
                    echo '<img src="/storage/agenda/'.$foto.'" width="170px"/>';
                    echo '</div>';
                                 
                    //Descrição do Evento
                    echo '<div class="descricao">';
                    echo '<br>'.$dados['descricao'].'<br>';                     
                    echo '</div>';//End descrição

                    //Dias do evento
                    //Datas do Evento
                    echo '<div class="datas">';
                    $arrayData = $dados['datas'] ;                                                            
                    if(count($arrayData) >0){
                        echo '<table style="width:100%;"><tr>';
                        echo '<th style="border:1px solid #FFF;" colspan="3">Dias e Horários do Evento</th>';
                        echo '</tr>';
                        foreach($arrayData as $dadosData){
                            echo '<tr style="border:1px solid #FFF;"><td style="width:33%;border-right:1px solid #FFF;">'.$dadosData['mes'].'</td>';
                            echo '<td style="width:33%; border-right:1px solid #FFF;">'.$dadosData['semana'].'</td>';
                            echo '<td style="width:34%;">'.$dadosData['hora_ini'].' - '.$dadosData['hora_fim'].'</td></tr>';
                        }//foreach Data                        
                        echo '</table>';
                    }//if data               
                    echo '</div>';//End Datas
                    
                    //Finalizando bloco
                    echo '<div style="clear: both;"></div>';
                    echo '</div>';//Bloco do Evento END                                                               
                    //echo '<div style="clear: both;"></div>';
                   
                    echo '<div class="borda_separar"></div>';
                    
                }//foreach array de eventos
            }else{
                echo '<div style="width:100%;text-align:center;padding:10px;">Nenhum evento cadastrado na agenda.</div>';
            }//if / else array de eventos
            ?>
      
        </div><!--Lista de Eventos-->
        
        
    </div>			
</section>
<!-- /PAGE TOP -->




