
<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li>Agenda de Eventos</li>                
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                <b>Agenda de Eventos</b> - Cadastro/Solicitação de Novo Evento
            </h2><!-- /Page Title -->
        </header>        
        
        <!--Tela de Cadastro -->
        <div class="col-sm-12 col-md-12">            
            <?php echo $this->partial('novo'); ?>
        </div><!--Tela de Cadastro End -->
    </div>			
</section>
<!-- /PAGE TOP -->
