
<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li>Agenda de Eventos</li>                
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                <b>Agenda de Eventos</b> - Visualizando Evento Detalhado
            </h2><!-- /Page Title -->
        </header>        
        
        <!--Lista de Eventos-->
        <div class="col-sm-12">
            
           
            
            <div style="width:100%;text-align:center;padding:10px;border:2px dotted #FFF;margin:10px auto 15px auto;">
                <br>
                <b>DIVULGUE</b> seu evento!!!<br>É <b>DE GRAÇA</b>, tá esperando o que???<br/><br/>
            </div>
        </div><!--Lista de Eventos-->
    </div>			
</section>
<!-- /PAGE TOP -->
