<script type="text/javascript" src="<?php echo $this->basePath() . '/js/contato/contato.js'; ?>"></script>
<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="<?php echo $this->basePath() . '/contato' ?>">Administração</a></li>
                <li class="active">Contatos</li>
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                Controle de Contatos
            </h2><!-- /Page Title -->
        </header>
    </div>			
</section>
<!-- /PAGE TOP -->

<br />

<?php echo $this->partial('Contato/index/psq-contato.phtml'); ?>
<?php echo $this->partial('Contato/index/cad-contato.phtml'); ?>