<script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/simpleUpload.min.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/anunciante/anunciante.js'; ?>"></script>

<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="<?php echo $this->basePath() . '/perfil/' ?>">Administração</a></li>
                <li class="active">Anunciantes</li>
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                Controle de Anunciantes
            </h2><!-- /Page Title -->
        </header>
    </div>			
</section>
<!-- /PAGE TOP -->

<br />

<?php echo $this->partial('psq-anunciante'); ?>
<?php echo $this->partial('form-cad-cliente'); ?>