<?php

namespace ConfigPaginaCliente\Entity\Repository;

use ConfigPaginaCliente\Entity\ConfigPaginaClienteEntity;
use Doctrine\ORM\EntityRepository;
use Zend\Stdlib\Hydrator;

/**
 * ConfigPaginaClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigPaginaClienteRepository extends EntityRepository {

    public function inserirConfigPaginaCliente($param = array()) {
        $entity = new ConfigPaginaClienteEntity($param);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function editarConfigPaginaCliente($param = array()) {
        $entity = $this->getEntityManager()->getReference('ConfigPaginaCliente\Entity\ConfigPaginaClienteEntity', $param['idConfigPaginaCliente']);
        (new Hydrator\ClassMethods())->hydrate($param, $entity);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function selecionarConfigPaginaCliente($id) {
        $repository = $this->find($id);
        return $repository;
    }

    public function selecionarConfigPaginaClienteBy($param) {
        $repository = $this->findBy($param);
        return $repository;
    }

}
