<!-- CONTENT -->
<div id="psqBanner">

    <?php $formPsqBanner = $this->formPsqBanner; ?>
    <?php $formPsqBanner->prepare(); ?>

    <?php echo $this->form()->openTag($formPsqBanner); ?>

    <!-- BASIC FORM -->
    <div class="panel panel-light margin-bottom8">

        <div class="panel-heading">
            <h3 id="tituloBannerPsq" class="panel-title bold"></h3>
        </div>

        <div class="panel-body">

            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label">Nome do Cliente:</label>
                    <div class="input-group">
                        <?php echo $this->formElement($formPsqBanner->get('noClientePsq')); ?>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-user"></span>
                        </span>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label" for="tpClientePsq">Tipo do Banner:</label>
                    <?php echo $this->formElement($formPsqBanner->get('tpBannerPsq')); ?>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12">
                    <?php echo $this->formButton()->openTag($formPsqBanner->get('btnPesquisarBanner')); ?>
                    <?php echo '<i class="fa fa-search"></i>' . $formPsqBanner->get('btnPesquisarBanner')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsqBanner->get('btnNovoBanner')); ?>
                    <?php echo '<i class="fa fa-plus"></i>' . $formPsqBanner->get('btnNovoBanner')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsqBanner->get('btnVoltarBanner')); ?>
                    <?php echo '<i class="fa fa-arrow-left"></i>' . $formPsqBanner->get('btnVoltarBanner')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>
                </div>
            </div>
            <!-- end cut -->

        </div>

    </div>
    <!-- /BASIC FORM -->

    <div id="tableBanners"></div>

    <?php echo $this->form()->closeTag(); ?>

</div>