<script type="text/javascript" src="<?php echo $this->basePath() . '/js/application/index/cabecalho.js'; ?>"></script>
<!-- Top Bar -->
<header id="topBar">
    
    <div class="container">
        
        <!-- Logo -->
        <div class="logo-container pull-left">
            <br />
            <span class="font-metropolian-text" style="font-size: 32px;">
                <img src="<?php echo $this->basePath() . '/img/logo.png' ?>" width="50" height="50" alt="" title="Acompanhantes Clube Luxúria"/>
                <a href="<?php echo $this->basePath() . "/application/index/home"; ?>">
                    <i>Acompanhantes Clube Luxúria</i>
                </a>
            </span><br />&nbsp;
        </div>
        
        <div id="barMain">
            <nav class="nav-second hide_mobile">
                <ul class="nav nav-pills nav-second">                                                      
                    <div class="block text-right">
                        <div class="call-us fsize13 pull-righ">
                            <?php if ($this->identity()) : ?>
                            <a href="<?php echo $this->basePath() . '/perfil' ?>"><i class="fa fa-user"></i> <?php echo $this->identity()->getLogin(); ?></a>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <a href="#" data-container="body" data-toggle="popover" data-placement="bottom" data-content="
        <ul class='comment list-unstyled'>
            <li class='comment'>
                <!-- avatar -->
                <img class='avatar' src='/epona/images/demo/fashion/thumb/3.jpg' width='50' height='50' alt='avatar' />
                <!-- comment body -->
                <div class='comment-body'> 
                    <a href='#' class='comment-author'>
                        <small class='text-muted pull-right'> 12 Minutes ago </small>
                        <span class='text-muted'>Melisa Doe</span>
                    </a>
                    <p class='text-muted'>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                        euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet 
                        dolore magna aliquam tincidunt erat volutpat.  
                    </p>
                </div><!-- /comment body -->
                <!-- options -->
                <ul class='list-inline fsize11'>
                    <li>
                        <a href='#'><span class='text-muted'><i class='fa fa-reply'></i> Reply</span></a>
                    </li>
                    <li>
                        <a href='#'><span class='text-muted'><i class='fa fa-thumbs-up'></i> Like</span></a>
                    </li>
                    <li>
                        <a href='#'><span class='text-muted'>Show All Comments (36)</span></a>
                    </li>
                    <li class='pull-right'>
                        <a href='#'><span class='text-muted'>Delete</span></a>
                    </li>
                    <li class='pull-right'>
                        <a href='#'><span class='text-muted'>Edit</span></a>
                    </li>
                </ul>
            </li><!-- /options -->

            <li class='comment'>
                <!-- avatar -->
                <img class='avatar' src='/epona/images/demo/fashion/thumb/1.jpg' width='50' height='50' alt='avatar' />
                <!-- comment body -->
                <div class='comment-body'> 
                    <a href='#' class='comment-author'>
                        <small class='text-muted pull-right'> 12 Minutes ago </small>
                        <span class='text-muted'>Melisa Doe</span>
                    </a>
                    <p class='text-muted'>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                        euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet 
                        dolore magna aliquam tincidunt erat volutpat.  
                    </p>
                </div><!-- /comment body -->
                <!-- options -->
                <ul class='list-inline fsize11'>
                    <li>
                        <a href='#'><span class='text-muted'><i class='fa fa-reply'></i> Reply</span></a>
                    </li>
                    <li>
                        <a href='#'><span class='text-muted'><i class='fa fa-thumbs-up'></i> Like</span></a>
                    </li>
                    <li>
                        <a href='#'><span class='text-muted'>Show All Comments (36)</span></a>
                    </li>
                    <li class='pull-right'>
                        <a href='#'><span class='text-muted'>Delete</span></a>
                    </li>
                    <li class='pull-right'>
                        <a href='#'><span class='text-muted'>Edit</span></a>
                    </li>
                </ul>
            </li><!-- /options -->

            <li class='comment'>
                <!-- avatar -->
                <img class='avatar' src='/epona/images/demo/fashion/thumb/2.jpg' width='50' height='50' alt='avatar' />
                <!-- comment body -->
                <div class='comment-body'> 
                    <a href='#' class='comment-author'>
                        <small class='text-muted pull-right'> 12 Minutes ago </small>
                        <span class='text-muted'>Melisa Doe</span>
                    </a>
                    <p class='text-muted'>
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                        euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet 
                        dolore magna aliquam tincidunt erat volutpat.  
                    </p>
                </div><!-- /comment body -->
                <!-- options -->
                <ul class='list-inline fsize11'>
                    <li>
                        <a href='#'><span class='text-muted'><i class='fa fa-reply'></i> Reply</span></a>
                    </li>
                    <li>
                        <a href='#'><span class='text-muted'><i class='fa fa-thumbs-up'></i> Like</span></a>
                    </li>
                    <li>
                        <a href='#'><span class='text-muted'>Show All Comments (36)</span></a>
                    </li>
                    <li class='pull-right'>
                        <a href='#'><span class='text-muted'>Delete</span></a>
                    </li>
                    <li class='pull-right'>
                        <a href='#'><span class='text-muted'>Edit</span></a>
                    </li>
                </ul>
            </li><!-- /options -->
        </ul>
    " data-original-title="Notificações" title="<span class='text-muted'>Notificações</span>"><i class="fa fa-globe"></i> Notificações</a>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <a href="#" onclick="abrirDisfarce()"><i class="fa fa-eye-slash"></i> Disfarce (Fake)</a>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <a href="<?php echo $this->basePath() . '/login/logout' ?>"><i class="fa fa-power-off"></i> Sair</a>
                            <?php else: ?>
                            <a href="<?php echo $this->basePath() . '/login' ?>"><i class="fa fa-sign-in"></i> Entrar - Área Restrita</a>
                            &nbsp;&nbsp;|&nbsp;&nbsp;
                            <a href="<?php echo $this->basePath() . '/application/index/cadastre-se' ?>"><i class="fa fa-pencil-square-o"></i> Cadastre-se</a>
                            <?php endif; ?>&nbsp;
                        </div>                                                          
                    </div>
                </ul>
            </nav>
        </div>

    </div><!-- /.container -->
    
</header>
<!-- /Top Bar -->
