<!-- Top Nav -->
<header id="topNav" class="dark-header">
    <div class="container">

        <!-- Mobile Menu Button -->
        <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
            <i class="fa fa-bars"></i>
        </button>

        <!-- Top Nav -->
        <div class="navbar-collapse nav-main-collapse collapse dark-body">
            <nav class="nav-main text-center">

                <ul id="topMain" class="nav nav-pills nav-main text-center dark-header">
                    <li class="dropdown" id="areaRestrita">
                        <?php if (!$this->identity()) : ?>
                        <li class="nav-main active" id="home">
                            <a class="nav-main" href="<?php echo $this->basePath() . "/application/index/home"; ?>">
                                HOME<span>Bem Vindo</span>
                            </a>                                                                    
                        </li>
                        <?php else : ?>
                            <a class="dropdown" href="<?php echo $this->basePath() . '/perfil' ?>">
                                PERFIL <span>Minha Página</span>
                            </a>
                        <?php endif; ?>
                    </li>
                    <li class="dropdown" id="diarios">
                        <a class="dropdown" href="<?php echo $this->basePath() . "/agenda"; ?>">
                            AGENDA<span>de Eventos</span>
                        </a>
                    </li>
                    <li class="dropdown" id="rotas">
                        <a class="nav-main" href="<?php echo $this->basePath() . "/application/index/mapa"; ?>">
                            ROTA GP<span>Localize sua Garota</span>
                        </a>
                    </li>
                    <li class="dropdown" id="guiagp">
                        <a class="nav-main" href="<?php echo $this->basePath() . '/application/index/guia' ?>">
                            GUIA GP <span>Tests Drives</span>
                        </a>
                    </li>
                    <li class="dropdown" id="anuncie">
                        <a class="dropdown-toggle" href="<?php echo $this->basePath() . "/application/index/anuncie"; ?>">
                            ANUNCIE <span>Seja um Anunciante</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->basePath() . "/application/index/anuncie"; ?>">Como Anunciar - <span>Experimente 30 dias Grátis!</span></a></li>
                            <li><a href="<?php echo $this->basePath() . "/application/index/regras-publicidade"; ?>">Regras de Publicidade</a></li>
                        </ul>
                    </li>
                    <li class="dropdown" id="cadastrese">
                        <a class="nav-main" href="<?php echo $this->basePath() . '/application/index/cadastre-se' ?>">
                            CADASTRE-SE <span>Seja Sócio do Clube</span>
                        </a>
                    </li>
                    <li class="dropdown" id="contato">
                        <a class="nav-main" href="<?php echo $this->basePath() . '/contato/formulario' ?>">
                            CONTATO <span>Fale Conosco</span>
                        </a>
                    </li>
                </ul>

            </nav>
        </div>
        <!-- /Top Nav -->
        
    </div><!-- /.container -->
    
</header>
<!-- /Top Nav -->