<hr />
<div class="copyright">
    <div class="container text-center fsize12">
        O Portal Clube Luxúria conta com acompanhantes de luxo e garotas de programa das cidades de Brasília, Guará, Taguatinga, Bandeirante e também do entorno do Distrito Federal. Este portal é, única e exclusivamente, um veículo de comunicação entre pessoas e, não tem nenhum vínculo com seus anunciantes, que são os únicos responsáveis pelas informações contidas nos seus respectivos anúncios. O site Clube Luxúria NÃO É AGÊNCIA e não assume nenhuma responsabilidade pelo conteúdo dos anúncios ou pelas respostas a qualquer um deles.<br />
        Todos os Direitos Reservados a <a href="http://www.clubeluxuria.com.br/application/index/home" target="_blank" title="Clube Luxúria" class="copyright">Clube Luxúria</a> &copy; 2015 &bull; Desenvolvido por <a href="http://www.lefdevelopers.com.br" target="_blank" title="L&F Developers" class="copyright">L&F Developers <img class="fa" src="<?php echo $this->basePath() . '/img/icons/leflogo32.png'; ?>"/></a> &nbsp;
        <br> <a href="<?php echo $this->basePath() . "/application/index/politica-privacidade"; ?>" class="fsize11">Privacy Policy</a> &bull; 
        <a href="<?php echo $this->basePath() . "/application/index/termos-servico"; ?>" class="fsize11">Terms of Service</a>
    </div>
</div>