<script type="text/javascript" src="<?php echo $this->basePath() . '/js/cliente/caracteristicas/cliente-caracteristica.js'; ?>"></script>

<!-- registration form -->
<?php $formCadClienteCaracteristica = $this->formCadClienteCaracteristica; ?>
<?php $formCadClienteCaracteristica->prepare(); ?>

<?php echo $this->form()->openTag($formCadClienteCaracteristica); ?>

<!-- BASIC FORM -->
<div class="panel panel-light margin-bottom8">

    <div class="panel-heading">
        <h3 id="tituloCaracteristicasCliente" class="panel-title bold"></h3>
    </div>

    <div class="panel-body">

        <?php echo $this->formElement($formCadClienteCaracteristica->get('idClienteCaracteristica')); ?>

        <div class="row">

            <div class="col col-md-4">

                <fieldset>
                    <section>
                        <label class="label">Características do Serviço</label>
                        <div class="row" style="overflow: auto;height: 350px;border: 1px solid;border-color: white;">
                            <div id="CaracteristicaServico" class="col-md-12"></div>
                        </div>
                    </section>

                </fieldset>                        

            </div>


            <div class="col col-md-4">

                <fieldset>
                    <section>
                        <label class="label">Características do Atendimento</label>
                        <div class="row" style="overflow: auto;height: 350px;border: 1px solid;border-color: white;">
                            <div id="CaracteristicaAtendimento" class="col-md-12"></div>
                        </div>
                    </section>

                </fieldset>                        

            </div>

            <div class="col col-md-4">

                <fieldset>
                    <section>
                        <label class="label">Cartões Aceitos</label>
                        <div class="row" style="overflow: auto;height: 350px;border: 1px solid;border-color: white;">
                            <div id="CaracteristicaCartoes" class="col-md-12"></div>
                        </div>
                    </section>

                </fieldset>                        

            </div>

        </div>

        <div class="row">
            <div class="col col-md-12">
                <?php echo $this->formButton()->openTag($formCadClienteCaracteristica->get('btnGravarClienteCaracteristica')); ?>
                <?php echo '<i class="fa fa-save"></i>' . $formCadClienteCaracteristica->get('btnGravarClienteCaracteristica')->getLabel(); ?>
                <?php echo $this->formButton()->closeTag(); ?>
            </div>
        </div>

    </div>
    <!-- end cut -->

</div>
<!-- /BASIC FORM -->

<?php echo $this->form()->closeTag($formCadClienteCaracteristica); ?>