<script type="text/javascript">
    $(document).ready(function () {
        $('#sgUfPsq').on('change', function () {
            $('#carregando').show();
            $('#formPsqAnuncianteHome').submit();
        });
        $('#idCidadePsq').on('change', function () {
            $('#carregando').show();
            $('#formPsqAnuncianteHome').submit();
        });
        
        $("#sgUfPsq").val('<?php echo $this->sgUfPsq; ?>');
        $('#idCidadePsq').val('<?php echo $this->idCidadePsq; ?>');
    });
</script>
<?php $formPsqAnunciantes = $this->formPsqAnunciantes; ?>
<?php $formPsqAnunciantes->prepare(); ?>
<?php echo $this->form()->openTag($formPsqAnunciantes); ?>
<ul class="nav nav-pills isotope-filter isotope-filter" data-sort-id="isotope-list" data-option-key="filter">
    <li data-option-value="*" class="active"><a href="#"><i class="fa fa-users"></i>&nbsp;Todas Garotas</a></li>
    <li data-option-value=".loiras"><a href="#"><i class="fa fa-user"></i>&nbsp;Loiras</a></li>
    <li data-option-value=".morenas"><a href="#"><i class="fa fa-user"></i>&nbsp;Morenas</a></li>
    <li data-option-value=".negras"><a href="#"><i class="fa fa-user"></i>&nbsp;Negras</a></li>
    <li data-option-value=".ruivas"><a href="#"><i class="fa fa-user"></i>&nbsp;Ruivas</a></li>
    <li data-option-value=".stAceitaCartao"><a href="#"><i class="fa fa-credit-card"></i>&nbsp;Aceita Cartão</a></li>
    <li><?php echo $this->formElement($formPsqAnunciantes->get('sgUfPsq')); ?></li>
    <li><?php echo $this->formElement($formPsqAnunciantes->get('idCidadePsq')); ?></li>
</ul>
<?php echo $this->form()->closeTag(); ?>

<ul class="sort-destination isotope" data-sort-id="isotope-list">

    <?php if (isset($this->lista)) : ?>
        <?php foreach ($this->lista as $lista) : ?>

        <?php $dsArquivo = $this->mostrarFotoPerfilHelper($lista['idCliente']); ?>

        <li class="isotope-item col-sm-6 col-md-3 col-lg-3 text-center <?php echo strtolower($this->masterHelper()->tpCabeloCor($lista['tpCabeloCor'])) . "s"; ?> <?php if ($lista['stAceitaCartao'] == 1) : ?>stAceitaCartao<?php endif; ?>">
            <div class="box-content thumbnail">
                <a href="<?php echo $this->basePath() . "/acompanhante/index/" . $lista['idCliente']; ?>" class="item-image">
                    <img class="img-responsive" src="<?php echo $dsArquivo; ?>" alt="" />
                    <h3>
                        <span><?php echo $lista['noArtistico']; ?></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br />
                        <?php if ($lista['stAnunciante'] == 1) : ?>
                        <small><?php echo $lista['nuTelefone']; ?></small>
                        <?php endif; ?>
                        <?php if ($lista['stAnunciante'] == 3) : ?>
                        <small><i class="fa fa-plane"></i> Viajando!</small>
                        <?php endif; ?>
                        <?php if ($lista['stAnunciante'] == 4) : ?>
                        <small><i class="fa fa-calendar"></i> Curtindo Férias!</small>
                        <?php endif; ?>
                    </h3>
                </a>
                <span class="label label-warning">
                    <i class="fa fa-map-marker"></i>&nbsp;<?php echo $lista['noCidade']; ?>
                </span>&nbsp;
                <span class="label label-warning">
                    <i class="fa fa-user"></i>&nbsp;<?php echo $this->masterHelper()->tpCabeloCor($lista['tpCabeloCor']); ?>
                </span>&nbsp;
                <?php if ($lista['stAceitaCartao'] == 1) : ?>
                <span class="label label-warning">
                    <i class="fa fa-credit-card"></i>&nbsp;Aceita Cartão
                </span>
                <?php endif; ?>
            </div>
        </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>