<script type="text/javascript" src="<?php echo $this->basePath() . '/js/anunciante/form-cad-anunciante.js'; ?>"></script>
<!-- registration form -->
<?php $formCadAnunciante = $this->formCadAnunciante; ?>
<?php $formCadAnunciante->prepare(); ?>

<?php echo $this->form()->openTag($formCadAnunciante); ?>

<!-- BASIC FORM -->
<div class="panel panel-light margin-bottom8">

    <div class="panel-heading">
        <h3 id="tituloAnunciante" class="panel-title bold"></h3>
    </div>

    <div class="panel-body">

        <?php echo $this->formElement($formCadAnunciante->get('idAnunciante')); ?>
        <?php echo $this->formElement($formCadAnunciante->get('idClienteAnunciante')); ?>

        <div class="row">
            <div class="col col-md-6">
                Tipo*:
                <label class="input">
                    <?php echo $this->formElement($formCadAnunciante->get('tpAnunciante')); ?>
                </label>
            </div>
            <div class="col col-md-6">
                Situação:
                <label class="input">
                    <?php echo $this->formElement($formCadAnunciante->get('stAnunciante')); ?>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-6">
                Nome Artístico*:
                <label class="input">
                    <i class="icon-append fa fa-pencil"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('noArtistico')); ?>
                    <b class="tooltip tooltip-bottom-right">(*) Obrigatório</b>
                </label>
            </div>
            <div class="col col-md-6">
                Telefone:
                <label class="input">
                    <i class="icon-append fa fa-phone"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('nuTelefoneAnunciante')); ?>
                    <b class="tooltip tooltip-bottom-right">(*) Obrigatório</b>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-6">
                Cabelo/Cor*:<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?php echo $this->formElement($formCadAnunciante->get('tpCabeloCor')); ?>
            </div>
            <div class="col col-md-6">
                Aceita Cartão?*<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?php echo $this->formElement($formCadAnunciante->get('stAceitaCartao')); ?>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-6">
                Website Url:
                <label class="input">
                    <i class="icon-append fa fa-globe"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('dsUrlSite')); ?>
                </label>
            </div>
            <div class="col col-md-2">
                UF*:
                <label class="input">
                    <?php echo $this->formElement($formCadAnunciante->get('sgUfAnunciante')); ?>
                </label>
            </div>
            <div class="col col-md-4">
                Cidade*:
                <label class="input">
                    <?php echo $this->formElement($formCadAnunciante->get('idCidadeAnunciante')); ?>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-6">
                Latitude:
                <label class="input">
                    <i class="icon-append fa fa-map-marker"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('nuLatitude')); ?>
                </label>
            </div>
            <div class="col col-md-6">
                Longitude:
                <label class="input">
                    <i class="icon-append fa fa-map-marker"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('nuLongitude')); ?>
                </label>
            </div>
        </div>
            
        <div class="row">
            <div class="col col-md-6">
                Frase de Chamada 01:
                <label class="input">
                    <i class="icon-append fa fa-tag"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('dsFrase1')); ?>
                    <b class="tooltip tooltip-bottom-right">(*) Obrigatório</b>
                </label>
            </div>
            <div class="col col-md-6">
                Frase de Chamada 02:
                <label class="input">
                    <i class="icon-append fa fa-tag"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('dsFrase2')); ?>
                    <b class="tooltip tooltip-bottom-right">(*) Obrigatório</b>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 col-md-12">
                Descrição da Anunciante:
                <label class="textarea">
                    <i class="icon-append fa fa-comment"></i>
                    <?php echo $this->formElement($formCadAnunciante->get('dsFrase3')); ?>
                    <b class="tooltip tooltip-bottom-right">(*) Obrigatório</b>
                </label>
            </div>
        </div>

        <div class="row">
            <div class="col col-md-12">
                <?php echo $this->formButton()->openTag($formCadAnunciante->get('btnGravarAnunciante')); ?>
                <?php echo '<i class="fa fa-save"></i>' . $formCadAnunciante->get('btnGravarAnunciante')->getLabel(); ?>
                <?php echo $this->formButton()->closeTag(); ?>
            </div>
        </div>

    </div>
    <!-- end cut -->

</div>
<!-- /BASIC FORM -->

<?php echo $this->form()->closeTag($formCadAnunciante); ?>