<!-- CONTENT -->
<div id="psqAnunciante">

    <?php $formPsqAnunciante = $this->formPsqAnunciante; ?>
    <?php $formPsqAnunciante->prepare(); ?>

    <div class="container">

        <?php echo $this->form()->openTag($formPsqAnunciante); ?>

        <!-- BASIC FORM -->
        <div class="panel panel-light margin-bottom8">

            <div class="panel-heading">
                <h3 class="panel-title bold"> Pesquisar e Listar Anunciantes</h3>
            </div>

            <div class="panel-body">

                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label" for="tpAnunciantePsq">Tipo:</label>
                        <?php echo $this->formElement($formPsqAnunciante->get('tpAnunciantePsq')); ?>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label" for="stAnunciantePsq">Situação:</label>
                        <?php echo $this->formElement($formPsqAnunciante->get('stAnunciantePsq')); ?>
                    </div>
                </div>

                <div class="row">
                    
                    <div class="form-group col-md-6">
                        <label class="control-label">Nome:</label>
                        <div class="input-group">
                            <?php echo $this->formElement($formPsqAnunciante->get('noArtisticoPsq')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-user"></span>
                            </span>
                        </div>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        <label class="control-label">UF:</label>
                        <?php echo $this->formElement($formPsqAnunciante->get('sgUfPsq')); ?>
                    </div>
                    <div class="form-group col-md-6">
                        <label class="control-label">Vencimento:</label>
                        <div class="input-group">
                            <?php echo $this->formElement($formPsqAnunciante->get('dtVencimentoPsq')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <?php echo $this->formButton()->openTag($formPsqAnunciante->get('btnPesquisarAnunciante')); ?>
                        <?php echo '<i class="fa fa-search"></i>' . $formPsqAnunciante->get('btnPesquisarAnunciante')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>

                        <?php echo $this->formButton()->openTag($formPsqAnunciante->get('btnVoltarAnunciante')); ?>
                        <?php echo '<i class="fa fa-arrow-left"></i>' . $formPsqAnunciante->get('btnVoltarAnunciante')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>
                    </div>
                </div>
                <!-- end cut -->

            </div>

        </div>
        <!-- /BASIC FORM -->

        <div id="tableAnunciantes"></div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
    <!-- /CONTENT -->

</div>