<?php if ($this->identity()) : ?>
<!-- COMMENT -->
<ul class="comment list-unstyled">
    <li class="comment">

        <!-- avatar -->
        <img class="avatar" src="<?php echo $this->basePath(); ?>/epona/images/demo/fashion/thumb/3.jpg" width="50" height="50" alt="avatar" />

        <!-- comment body -->
        <div class="comment-body"> 
            <a href="#" class="comment-author">
                <small class="text-muted pull-right"> 12 Minutes ago </small>
                <span>Melisa Doe</span>
            </a>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet 
                dolore magna aliquam tincidunt erat volutpat.  
            </p>
        </div><!-- /comment body -->

        <!-- options -->
        <ul class="list-inline fsize11">
            <li>
                <a href="#" class="text-info"><i class="fa fa-reply"></i> Reply</a>
            </li>
            <li>
                <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Like</a>
            </li>
            <li>
                <a href="#" class="text-muted">Show All Comments (36)</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-danger">Delete</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-primary">Edit</a>
            </li>
        </ul>
    </li><!-- /options -->

    <li class="comment comment-reply">

        <!-- avatar -->
        <img class="avatar" src="<?php echo $this->basePath(); ?>/epona/images/demo/fashion/thumb/1.jpg" width="35" height="35" alt="avatar" />

        <!-- comment body -->
        <div class="comment-body"> 
            <a href="#" class="comment-author">
                <small class="text-muted pull-right"> 4 Minutes ago </small>
                <span>Ioana Doe</span>
            </a>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
            </p>
        </div><!-- /comment body -->

        <!-- options -->
        <ul class="list-inline fsize11">
            <li>
                <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Like</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-danger">Delete</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-primary">Edit</a>
            </li>
        </ul><!-- /options -->

    </li>

    <li class="comment comment-reply">

        <!-- avatar -->
        <img class="avatar" src="<?php echo $this->basePath(); ?>/epona/images/demo/fashion/thumb/2.jpg" width="35" height="35" alt="avatar" />

        <!-- comment body -->
        <div class="comment-body"> 
            <a href="#" class="comment-author">
                <small class="text-muted pull-right"> a moment ago </small>
                <span>Simona Doe</span>
            </a>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
            </p>
        </div><!-- /comment body -->

        <!-- options -->
        <ul class="list-inline fsize11">
            <li>
                <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Like</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-danger">Delete</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-primary">Edit</a>
            </li>
        </ul><!-- /options -->

    </li>
</ul>
<!-- /COMMENT -->

<!-- COMMENT -->
<ul class="comment list-unstyled">
    <li class="comment">

        <!-- avatar -->
        <img class="avatar" src="<?php echo $this->basePath(); ?>/epona/images/demo/fashion/thumb/4.jpg" width="50" height="50" alt="avatar" />

        <!-- comment body -->
        <div class="comment-body"> 
            <a href="#" class="comment-author">
                <small class="text-muted pull-right"> 12 Minutes ago </small>
                <span>Melisa Doe</span>
            </a>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh 
                euismod tincidunt laoreet dolore magna aliquam tincidunt erat volutpat laoreet 
                dolore magna aliquam tincidunt erat volutpat.  
            </p>
        </div><!-- /comment body -->

        <!-- options -->
        <ul class="list-inline fsize11">
            <li>
                <a href="#" class="text-info"><i class="fa fa-reply"></i> Reply</a>
            </li>
            <li>
                <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Like</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-danger">Delete</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-primary">Edit</a>
            </li>
        </ul>
    </li><!-- /options -->

    <li class="comment comment-reply">

        <!-- avatar -->
        <img class="avatar" src="<?php echo $this->basePath(); ?>/epona/images/demo/fashion/thumb/3.jpg" width="35" height="35" alt="avatar" />

        <!-- comment body -->
        <div class="comment-body"> 
            <a href="#" class="comment-author">
                <small class="text-muted pull-right"> 4 Minutes ago </small>
                <span>Ioana Doe</span>
            </a>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
            </p>
        </div><!-- /comment body -->

        <!-- options -->
        <ul class="list-inline fsize11">
            <li>
                <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Like</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-danger">Delete</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-primary">Edit</a>
            </li>
        </ul><!-- /options -->

    </li>

    <li class="comment comment-reply">

        <!-- avatar -->
        <img class="avatar" src="<?php echo $this->basePath(); ?>/epona/images/demo/fashion/thumb/5.jpg" width="35" height="35" alt="avatar" />

        <!-- comment body -->
        <div class="comment-body"> 
            <a href="#" class="comment-author">
                <small class="text-muted pull-right"> a moment ago </small>
                <span>Simona Doe</span>
            </a>
            <p>
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy! <i class="fa fa-smile-o green"></i> 
            </p>
        </div><!-- /comment body -->

        <!-- options -->
        <ul class="list-inline fsize11">
            <li>
                <a href="#" class="text-success"><i class="fa fa-thumbs-up"></i> Like</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-danger">Delete</a>
            </li>
            <li class="pull-right">
                <a href="#" class="text-primary">Edit</a>
            </li>
        </ul><!-- /options -->

    </li>
    <li>
        <div class="input-group">
            <input id="btn-input" type="text" class="form-control" placeholder="Type your message...">
            <span class="input-group-btn">
                <button class="btn btn-primary" id="btn-chat">
                    <i class="fa fa-reply"></i> Reply
                </button> 
            </span>
        </div>
    </li>
</ul>
<!-- /COMMENT -->
<?php else: ?>

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            <h2 class="text-muted"><center>Acesso Restrito</center></h2>
            Caro visitante,<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Este conteúdo é exclusivo para os 
            <strong>Sócios Clube Luxúria</strong>. Se deseja visualizar, curtir e comentar as 
            histórias <i>calientes</i> de <strong><?php echo $this->noArtistico; ?></strong> 
            em seu "Meu Diário" faça parte do clube e desfrute de todos os conteúdos restritos 
            do site.<br />
            &nbsp;<br />
            <center>
                Sou Sócio. Quero acessar! <a href="<?php echo $this->basePath(); ?>/application/index/cadastre-se">Clique aqui</a>. | Não sou Sócio. Quero acessar! <a href="<?php echo $this->basePath(); ?>/application/index/cadastre-se">Clique aqui</a>.
            </center><br />
            &nbsp;
        </div>
    </div>
</div>

<?php endif; ?>