<form class="sky-form boxed"></form>
<?php if ($this->identity()) : ?>

    <div class="row">
        <div class="col-md-4">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <td colspan="2" align="center">Meus Dados</td>
                    </tr>
                    <tr>
                        <td>Nome:</td>
                        <td><i><?php echo $this->noArtistico; ?></i></td>
                    </tr>
                    <?php if ($this->dsIdade != "") : ?>
                    <tr>
                        <td>Idade:</td>
                        <td><i><?php echo $this->dsIdade; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsApelido != "") : ?>
                    <tr>
                        <td>Apelido:</td>
                        <td><i><?php echo $this->dsApelido; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsCabelos != "") : ?>
                    <tr>
                        <td>Cabelos:</td>
                        <td><i><?php echo $this->dsCabelos; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsOlhos != "") : ?>
                    <tr>
                        <td>Olhos:</td>
                        <td><i><?php echo $this->dsOlhos; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsLabios != "") : ?>
                    <tr>
                        <td>Lábios:</td>
                        <td><i><?php echo $this->dsLabios; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsAltura != "") : ?>
                    <tr>
                        <td>Altura:</td>
                        <td><i><?php echo $this->dsAltura; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsPeso != "") : ?>
                    <tr>
                        <td>Peso:</td>
                        <td><i><?php echo $this->dsPeso; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsBusto != "") : ?>
                    <tr>
                        <td>Busto:</td>
                        <td><?php echo $this->dsBusto; ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsCintura != "") : ?>
                    <tr>
                        <td>Cintura:</td>
                        <td><?php echo $this->dsCintura; ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsQuadril != "") : ?>
                    <tr>
                        <td>Quadril:</td>
                        <td><?php echo $this->dsQuadril; ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsHobby != "") : ?>
                    <tr>
                        <td>Hobbys:</td>
                        <td><i><?php echo $this->dsHobby; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsComidas != "") : ?>
                    <tr>
                        <td>Comidas:</td>
                        <td><i><?php echo $this->dsComidas; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsBebidas != "") : ?>
                    <tr>
                        <td>Bebidas:</td>
                        <td><i><?php echo $this->dsBebidas; ?></i></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ($this->dsFrase != "") : ?>
                    <tr>
                        <td>Frase:</td>
                        <td><i>"<?php echo $this->dsFrase; ?>"</i></td>
                    </tr>
                    <?php endif; ?>
                </tbody>
            </table>
            
        </div>
        
        <?php $dsArquivo = $this->mostrarFotoPerfilHelper($this->idCliente); ?>
        <div class="col-md-8">
            <figure class="default-gradient bg-silver text-center margin-bottom8">
                <img class="img-responsive" src="<?php echo $this->basePath() . $dsArquivo; ?>" alt="" />
            </figure>
        </div>
        
    </div>


<?php else: ?>

    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <h2 class="text-muted"><center>Acesso Restrito</center></h2>
                Caro visitante,<br />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Este conteúdo é exclusivo para os 
                <strong>Sócios Clube Luxúria</strong>. Se deseja visualizar, curtir e comentar as 
                histórias <i>calientes</i> de <strong><?php echo $this->noArtistico; ?></strong> 
                em seu "Meu Diário" faça parte do clube e desfrute de todos os conteúdos restritos 
                do site.<br />
                &nbsp;<br />
                <center>
                    Sou Sócio. Quero acessar! <a href="<?php echo $this->basePath(); ?>/application/index/cadastre-se">Clique aqui</a>. | Não sou Sócio. Quero acessar! <a href="<?php echo $this->basePath(); ?>/application/index/cadastre-se">Clique aqui</a>.
                </center><br />
                &nbsp;
            </div>
        </div>
    </div>

<?php endif; ?>