<?php if (count($this->lista) > 0) : ?>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered" width="99%">
        <thead>
            <tr>
                <th width="25" colspan="2"><span class="fa fa-gears"></span> Ações</th>
                <th>Nome do Cachê</th>
                <th>Descrição do Cachê</th>
                <th>Valor do Cachê</th>
            </tr>
        </thead>
        <tbody>
            <?php if (isset($this->lista)) : ?>
                <?php foreach ($this->lista as $lista) : ?>
                    <tr>
                        <td style="text-align:center;">
                            <span onclick="selecionarCache(<?php echo $lista['idCache']; ?>);" title="Editar Cachê" class="glyphicon glyphicon-pencil" style="cursor: pointer;"></span>
                        </td>
                        <td style="text-align:center;">
                            <span onclick="confirmarExcluirCache(<?php echo $lista['idCache']; ?>);" title="Remover Cachê" class="glyphicon glyphicon-trash" style="cursor: pointer;"></span>
                        </td>
                        <td><?php echo $lista['noCache']; ?></td>
                        <td><?php echo $lista['dsCache']; ?></td>
                        <td><?php echo $lista['dsValor']; ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
        </tbody>
    </table>
    <?php echo $this->paginationControl($this->lista, 'Sliding', 'partials/paginator', array('url' => 'cache/pesquisar/', 'parametros' => $this->parametros)); ?>
<?php endif; ?>

<?php if (count($this->lista) == 0) : ?>
    <table cellpadding="0" cellspacing="0" border="0" class="table table-bordered" width="99%">
        <tr>
            <td align="center">
                <strong>Nenhum registro foi encontrado!</strong>
            </td>
        </tr>
    </table>
    &nbsp;<br />&nbsp;<br />&nbsp;<br />&nbsp;
<?php endif; ?>