<?php echo $this->doctype(); ?>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?php 
        if ($this->placeholder('titleType', 'APPEND') == 'SET') {
            echo $this->headTitle()->setAutoEscape(false);
        } else {
            echo $this->headTitle('Acompanhantes Clube Luxúria', $this->placeholder('titleType', 'APPEND'))
                    ->setSeparator(' - ')->setAutoEscape(false);
        }
        ?>
        
        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        
        <meta name="description" content="Acompanhantes Clube Luxúria o melhor site de Acompanhantes do Brasil. Confira as mais belas e gostosas acompanhantes!">
        <meta name="keywords" content="Acompanhantes, Gostosas, Garotas, Gatas de Programa, GP, Sexo, Prazer">
        <meta name="author" content="Clube Luxúria">
        <!--<meta name="google-site-verification" content="p5mfU_2mZ4ufUiowMqxroI2bM7X8t10vNh3Zq2a96G8" />-->
        <meta name="google-site-verification" content="5mHILd546UFWhYvLnh5l57sS6-QyMtp-X_YN4y5wghE" /><!-- Registrado pelo clubeluxuriabr@gmail.com-->
        
        <!-- WEB FONTS -->      
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&amp;subset=latin,latin-ext" rel="stylesheet" type="text/css" />

        <!-- Favicon -->
        <!--<link rel="shortcut icon" href="<?php // echo $this->basePath() . '/epona/images/demo/favicon.ico'; ?>" />-->
        
        <link rel="apple-touch-icon" sizes="57x57" href="<?php echo $this->basePath().'/img/favicon';?>'/apple-icon-57x57.png">
        <link rel="apple-touch-icon" sizes="60x60" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-60x60.png">
        <link rel="apple-touch-icon" sizes="72x72" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-72x72.png">
        <link rel="apple-touch-icon" sizes="76x76" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-76x76.png">
        <link rel="apple-touch-icon" sizes="114x114" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-114x114.png">
        <link rel="apple-touch-icon" sizes="120x120" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-120x120.png">
        <link rel="apple-touch-icon" sizes="144x144" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-144x144.png">
        <link rel="apple-touch-icon" sizes="152x152" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-152x152.png">
        <link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->basePath().'/img/favicon';?>/apple-icon-180x180.png">
        <link rel="icon" type="image/png" sizes="192x192"  href="<?php echo $this->basePath().'/img/favicon';?>/android-icon-192x192.png">
        <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $this->basePath().'/img/favicon';?>/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $this->basePath().'/img/favicon';?>/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $this->basePath().'/img/favicon';?>/favicon-16x16.png">
        <link rel="manifest" href="<?php echo $this->basePath().'/img/favicon';?>/manifest.json">
        <meta name="msapplication-TileColor" content="#ffffff">
        <meta name="msapplication-TileImage" content="<?php echo $this->basePath().'/img/favicon';?>/ms-icon-144x144.png">
        <meta name="theme-color" content="#ffffff">

        <link href="<?php echo $this->basePath() . '/css/slideheader.css'; ?>" rel="stylesheet" type="text/css" />     

        <!-- CORE CSS -->
        <link href="<?php echo $this->basePath() . '/epona/css/bootstrap.css'; ?>" rel="stylesheet" type="text/css" />     
        <link href="<?php echo $this->basePath() . '/epona/css/bootstrap.min.css'; ?>" rel="stylesheet" type="text/css" />     
        <link href="<?php echo $this->basePath() . '/epona/css/font-awesome.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/sky-forms.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/weather-icons.min.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/line-icons.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/plugins/owl-carousel/owl.pack.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/plugins/magnific-popup/magnific-popup.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/animate.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/flexslider.css'; ?>" rel="stylesheet" type="text/css" />

        <!--REVOLUTION SLIDER-->   
        <link href="<?php echo $this->basePath() . '/epona/css/revolution-slider.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/layerslider.css'; ?>" rel="stylesheet" type="text/css" />
        
	<!-- BLOG -->
        <link href="<?php echo $this->basePath(); ?>/epona/css/layout-blog.css" rel="stylesheet" type="text/css" />        

        <!--THEME CSS -->   
        <link href="<?php echo $this->basePath() . '/epona/css/essentials.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/layout.css'; ?>" rel="stylesheet" type="text/css" />       
        <link href="<?php echo $this->basePath() . '/epona/css/header-default.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/epona/css/footer-default.css'; ?>" rel="stylesheet" type="text/css" />
       <!-- <link href="<?php //echo $this->basePath() . '/epona/css/color_scheme/lightgrey.css'; ?>" rel="stylesheet" type="text/css" />-->
        <link href="<?php echo $this->basePath() . '/epona/css/layout-dark.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/css/personal-web.css'; ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath() . '/css/custom.css'; ?>" rel="stylesheet" type="text/css" />
        
        <!-- SCRIPTS -->    
        <!-- Slide Header  --> 
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/jquery-2.1.1.min.js'; ?>"></script>        
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/slideheader.js'; ?>"></script>  

        <!-- Modernizr -->         
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/modernizr.min.js'; ?>"></script>   

        <!-- jQwidgets -->        
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/js/jqwidgets/styles/jqx.base.css'; ?>" type="text/css"/>

        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/modernizr.min.js'; ?>"></script>   
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jqwidgets/jqxcore.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jqwidgets/jqxdatetimeinput.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jqwidgets/jqxcalendar.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jqwidgets/jqxtooltip.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jqwidgets/jqxtabs.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jqwidgets/globalization/globalize.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jsgeneralfunctions.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/componentes.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/jquery.maskedinput.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/js/guiMoneyMask.js'; ?>"></script>

        <script type="text/javascript">
            top.basePath = '<?php echo $this->basePath(); ?>';
            $(document).ready(function () {
                //Setando as Variaveis de datepicker - bootstrap
                $.fn.datepicker.dates['en'] = {
                   days: ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado" ],
                   daysShort: [ "Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sab" ],
                   daysMin: [ "D", "S", "T", "Q", "Q", "S", "S" ],
                   months: [ "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
                   monthsShort: [ "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
                   today: "Hoje",
                   clear: "Limpar",
                   titleFormat: "MM yyyy", /* Leverages same syntax as 'format' */
                   weekStart: 0       
                };//Datepicker Bootsrap
            });
        </script>        
    </head>
	
    <!-- 
            Available body classes: 
                    smoothscroll			= enable chrome browser smooth scroll
                    grey 				= grey content background
                    boxed 				= boxed style
                    pattern1 ... pattern11 	= background pattern

            Background Image - add to body: 
                    data-background="assets/images/boxed_background/1.jpg"

            Examples: 
                    <body class="smoothscroll grey boxed pattern3">
                    <body class="smoothscroll boxed" data-background="assets/images/boxed_background/1.jpg">
    -->
    <?php 
    $tpPlanoFundo = null;
    if ($this->identity()) {
        $tpPlanoFundo = $this->pegarTpPlanoFundoPerfil($this->identity()->getIdUsuario());
    }
    switch ($tpPlanoFundo) {
        case 1:
            $dsPlanoFundo = $this->basePath() . "/epona/images/boxed_background/12.jpg";
            break;
        case 2:
            $dsPlanoFundo = $this->basePath() . "/epona/images/boxed_background/7.jpg";
            break;
        case 3:
            $dsPlanoFundo = $this->basePath() . "/epona/images/boxed_background/8.jpg";
            break;
        default:
            $dsPlanoFundo = $this->basePath() . "/epona/images/boxed_background/12.jpg";
            break;
    }
    ?>
    <body class="boxed pattern11" data-background="<?php echo $dsPlanoFundo; ?>">

        <div id="wrapper">

            <!-- CABEÇALHO PRINCIPAL -->
            <div id="header"><!-- class="sticky" for sticky menu -->
                <?php echo $this->render('partials/cabecalho.phtml'); ?>
            </div>
            <!-- /CABEÇALHO PRINCIPAL -->
            
            <!-- MENU -->
            <div id="menu-horizontal">
                <?php echo $this->render('partials/menu-horizontal.phtml'); ?>
            </div>
            <!-- /MENU -->
            
            <!-- BANNER PRINCIPAL -->
            <div id="banner-principal">
                <?php echo $this->partial('banner-principal'); ?>
            </div>
            <!-- /BANNER PRINCIPAL -->
            
            <!-- CONTENT -->
            <div class="content">
                <?php echo $this->content; ?>
            </div>                 
            <!-- /CONTENT -->

        </div><!-- /#wrapper -->
        
        
        <div id="wrapper">
            <!-- FOOTER -->
            <footer id="footer">
                <?php echo $this->render('partials/rodape.phtml'); ?>
            </footer>
            <!-- /FOOTER -->
            <a href="#" id="toTop"></a>
        </div><!-- /#wrapper -->



        <div id="disfarce" style="display: none;">


		<div class="maintenance">

			<h1>MAINTENANCE MODE</h1>
			<p>

				<!-- custom text -->
				The site is undergoing some <strong>scheduled</strong> maintenance. <strong>Please</strong> come back <strong>later</strong>!
				<!-- /custom text -->

			</p>

			<hr class="half-margins" />

			<!-- progress bars -->
			<div class="container">
				<div class="row text-left">
					<div class="col-md-8 col-md-offset-2">

						<div class="progress-bars">
							<div class="progress-label">
								<span>Migrating Data</span>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-warning" data-appear-progress-animation="100%" data-appear-animation-delay="300">
									<span class="progress-bar-tooltip">100%</span>
								</div>
							</div>
							<div class="progress-label">
								<span>Testing</span>
							</div>
							<div class="progress">
								<div class="progress-bar progress-bar-primary" data-appear-progress-animation="81%" data-appear-animation-delay="300">
									<span class="progress-bar-tooltip">81%</span>
								</div>
							</div>
						</div>


					</div>
				</div>
			</div>
			<!-- /progress bars -->

			<hr class="half-margins" />

			<!-- socials -->
			<a href="#" class="social fa fa-facebook"></a>
			<a href="#" class="social fa fa-twitter"></a>
			<a href="#" class="social fa fa-google-plus"></a>
			<a href="#" class="social fa fa-linkedin"></a>
			<a href="#" class="social fa fa-pinterest"></a>
			<a href="#" class="social fa fa-youtube-square"></a>
			<a href="#" class="social fa fa-vimeo-square"></a>
			<a href="#" class="social fa fa-flickr"></a>
                        <a href="#" class="fa fa-times" onclick="fecharDisfarce();"></a>
			<!-- /socials -->
			
			
		</div><!-- /maintenance -->
                
        </div>

        <div id="carregando" style="display: none;">
            <div id="conteudoCarregando">
                <div>
                    <i class="fa fa-spin fa-spinner"></i> Processando...
                </div>

                <div class="progress progress-striped active">
                    <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                </div>
            </div>
        </div>

        <!-- Modal Alerta -->
        <div id="modalAlerta" style="display: none;" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalAlertaLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm" style="width: 35%;">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span>
                            <span class="sr-only">Fechar</span>
                        </button>
                        <h4 class="modal-title" id="modalAlertaLabel">
                            <i class="fa fa-exclamation-triangle"></i> Alerta
                        </h4>
                    </div>
                    
                    <div class="modal-body">
                        <div class="row">
                            
                            <div id="conteudoModalAlerta" style="color: #000000;"></div>
                            
                            <div class="col-lg-6 col-md-6 center">
                                <button id="btnOk" type="submit" class="btn btn-primary">
                                    <i class="fa fa-check"></i>Ok
                                </button>
                            </div>
                            
                        </div>
                        
                    </div>
                    
                </div><!-- /.modal-content -->
                
            </div><!-- /.modal-dialog -->
        </div>
        <!-- Fim Modal -->
        
        <!-- Modal Confirmacao -->
        <div id="modalConfirmacao" style="display: none;" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modalConfirmacaoLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm" style="width: 35%;">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">×</span>
                            <span class="sr-only">Fechar</span>
                        </button>
                        <h4 class="modal-title" id="modalConfirmacaoLabel">
                            <i class="fa fa-exclamation-triangle"></i> Confirmação
                        </h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            
                            <div id="conteudoModalConfirmacao" style="color: #000000;"></div>
                            
                            <div class="col-lg-6 col-md-6" style="text-align: center;">
                                <button id="btnSim" type="submit" class="btn btn-primary"><i class="fa fa-check"></i>Sim</button>
                            </div>
                            <div class="col-lg-6 col-md-6" style="text-align: center;">
                                <button id="btnNao" type="submit" class="btn btn-danger"><i class="fa fa-times"></i>Não</button>
                            </div>
                            
                        </div>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div>
        <!-- Fim Modal -->
        
        <!-- JAVASCRIPT FILES -->        
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/jquery.isotope.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/masonry.js'; ?>"></script>          
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/js/bootstrap.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/magnific-popup/jquery.magnific-popup.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/owl-carousel/owl.carousel.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/knob/js/jquery.knob.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/flexslider/jquery.flexslider-min.js'; ?>"></script>

        <!-- REVOLUTION SLIDER -->
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/revolution-slider/js/jquery.themepunch.plugins.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/plugins/revolution-slider/js/jquery.themepunch.revolution.min.js'; ?>"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/js/revolution_slider.js'; ?>"></script>                 

        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/js/jquery.easing.js'; ?>"></script>   
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/js/jquery.easing.min.js'; ?>"></script>  
        <!--  <script type="text/javascript" src="<?php //echo $this->basePath() . '/epona/js/easing.compatibility.js';   ?>"></script>    
        
         
          App -->         
        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/js/app.js'; ?>"></script>   

        <script type="text/javascript" src="<?php echo $this->basePath() . '/epona/js/script.js'; ?>"></script>
        <!-- <script type="text/javascript" src="<?php //echo $this->basePath() . '/epona/plugins/styleswitcher/styleswitcher.js';   ?>"></script> -->

    </body>
</html>
