<style>
    #uploads .block {
        /*display: inline-block;*/
        /*vertical-align: top;*/
        /*        width: 100px;
                height: 100px;*/
        /*        margin-right: 20px;
                margin-bottom: 20px;
                padding: 10px;*/
        /*        background-color: white;*/
        /*border: 1px solid #CCCCCC;*/
    }

    #uploads .block .progressBar {
        background-color: #3E6FAD;
        width: 0px;
        height: 5px;
        margin-top: 47px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        -o-border-radius: 5px;
        border-radius: 5px;
        -moz-transition: .25s ease-out;
        -webkit-transition: .25s ease-out;
        -o-transition: .25s ease-out;
        transition: .25s ease-out;
    }

    #uploads .block .error {
        text-align: left;
        font-size: 14px;
        color: red;
    }
</style>

<label>Fotos Horizontais</label>
<div class="toggle-content">
    <!-- registration form -->
    <?php $formCadFotoHorizontal = $this->formCadFotoHorizontal; ?>
    <?php $formCadFotoHorizontal->prepare(); ?>


    <?php echo $this->form()->openTag($formCadFotoHorizontal); ?>


    <?php echo $this->formElement($formCadFotoHorizontal->get('idFotoHorizontal')); ?>
    <?php echo $this->formElement($formCadFotoHorizontal->get('idAlbumFotoHorizontal')); ?>
    <?php echo $this->formElement($formCadFotoHorizontal->get('tpFotoHorizontal')); ?>
    <?php echo $this->formElement($formCadFotoHorizontal->get('stFotoHorizontal')); ?>
    <?php echo $this->formElement($formCadFotoHorizontal->get('stComentarioFotoHorizontal')); ?>
    <?php echo $this->formElement($formCadFotoHorizontal->get('dsLegendaFotoHorizontal')); ?>
    <?php echo $this->formElement($formCadFotoHorizontal->get('dsArquivoFotoHorizontal')); ?>

    <div class="form-group">

        <div class="row">

            <div class="col-lg-12 col-md-12 col-sm-12">
                <div id="uploads"></div>
            </div>
        </div>

        <div class="row">

            <div class="col-lg-9 col-md-9 col-sm-12">

                <div id="divFileFotoHorizontal" class="sky-form nomargin">
                    <label class="label">Selecione os arquivos:</label>
                    <label for="fileFotoHorizontal" class="input input-file">
                        <div class="button">
                            <input type="file" id="fileFotoHorizontal" onchange="this.parentNode.nextSibling.value = this.value" multiple>Procurar...
                        </div>
                        <input type="text" readonly>
                    </label>
                </div>

                <div id="divNotaFotoHorizontal" class="clearfix margin-top20">
                    <span class="label label-warning">NOTA! </span>
                    <p>
                        Adicionar Fotos de Qualidade<br />
                        Extensão: JPG ou PNG.<br />
                        Tamanho mínimo: 500 x 335 pixels ou maior
                    </p>
                </div>

            </div>

        </div>

    </div>

    <?php echo $this->form()->closeTag($formCadFotoHorizontal); ?>

</div>