<style>
    #uploadsVertical .blockVertical {
        /*display: inline-block;*/
        /*vertical-align: top;*/
        /*        width: 100px;
                height: 100px;*/
        /*        margin-right: 20px;
                margin-bottom: 20px;
                padding: 10px;*/
        /*        background-color: white;*/
        /*border: 1px solid #CCCCCC;*/
    }

    #uploadsVertical .blockVertical .progressBar {
        background-color: #3E6FAD;
        width: 0px;
        height: 5px;
        margin-top: 47px;
        -moz-border-radius: 5px;
        -webkit-border-radius: 5px;
        -o-border-radius: 5px;
        border-radius: 5px;
        -moz-transition: .25s ease-out;
        -webkit-transition: .25s ease-out;
        -o-transition: .25s ease-out;
        transition: .25s ease-out;
    }

    #uploadsVertical .blockVertical .error {
        text-align: left;
        font-size: 14px;
        color: red;
    }
</style>

<label>Fotos Verticais</label>
<div class="toggle-content">
    
    <?php $formCadFotoVertical = $this->formCadFotoVertical; ?>
    <?php $formCadFotoVertical->prepare(); ?>
    <?php echo $this->form()->openTag($formCadFotoVertical); ?>
    <?php echo $this->formElement($formCadFotoVertical->get('idFotoVertical')); ?>
    <?php echo $this->formElement($formCadFotoVertical->get('idAlbumFotoVertical')); ?>
    <?php echo $this->formElement($formCadFotoVertical->get('tpFotoVertical')); ?>
    <?php echo $this->formElement($formCadFotoVertical->get('stFotoVertical')); ?>
    <?php echo $this->formElement($formCadFotoVertical->get('stComentarioFotoVertical')); ?>
    <?php echo $this->formElement($formCadFotoVertical->get('dsLegendaFotoVertical')); ?>
    <?php echo $this->formElement($formCadFotoVertical->get('dsArquivoFotoVertical')); ?>

    <div class="form-group">

        <div class="row">

            <div class="col-lg-12 col-md-12 col-sm-12">
                <div id="uploadsVertical"></div>
            </div>
        </div>

        <div class="row">

            <div class="col-lg-9 col-md-9 col-sm-12">

                <div id="divFileFotoVertical" class="sky-form nomargin">
                    <label class="label">Selecione os arquivos:</label>
                    <label for="fileFotoVertical" class="input input-file">
                        <div class="button">
                            <input type="file" id="fileFotoVertical" onchange="this.parentNode.nextSibling.value = this.value" multiple>Browse
                        </div>
                        <input type="text" readonly>
                    </label>
                </div>

                <div id="divNotaFotoVertical" class="clearfix margin-top20">
                    <span class="label label-warning">NOTA! </span>
                    <p>
                        Adicionar Fotos de Qualidade<br />
                        Extensão: JPG ou PNG.<br />
                        Tamanho mínimo: 335 x 500 pixels ou maior
                    </p>
                </div>

            </div>

        </div>

    </div>

    <?php echo $this->form()->closeTag($formCadFotoVertical); ?>

</div>