<!-- CONTENT -->
<div id="cadAlbum">
    <!-- registration form -->
    <?php $formCadAlbum = $this->formCadAlbum; ?>
    <?php $formCadAlbum->prepare(); ?>

    <?php echo $this->form()->openTag($formCadAlbum); ?>

    <!-- BASIC FORM -->
    <div class="panel panel-light margin-bottom8">

        <div class="panel-heading">
            <h3 id="tituloAlbum" class="panel-title bold"></h3>
        </div>

        <div class="panel-body">

            <?php echo $this->formElement($formCadAlbum->get('idAlbum')); ?>
            <?php echo $this->formElement($formCadAlbum->get('idClienteAlbum')); ?>

            <div class="row">

                <div class="col col-md-6">
                    Cliente:
                    <label class="input">
                        <?php echo $this->formElement($formCadAlbum->get('idClienteSelectAlbum')); ?>
                    </label>
                </div>

                <div class="col col-md-6">
                    Situação:
                    <label class="input">
                        <?php echo $this->formElement($formCadAlbum->get('stAlbum')); ?>
                    </label>
                </div>

            </div>

            <div class="row">
                
                <div class="col col-md-6">
                    Nome do Album:
                    <label class="input">
                        <i class="icon-append fa fa-pencil"></i>    
                        <?php echo $this->formElement($formCadAlbum->get('noAlbum')); ?>
                    </label>
                </div>
                
                <div class="col col-md-6">
                    Tipo:
                    <label class="input">
                        <?php echo $this->formElement($formCadAlbum->get('tpAlbum')); ?>
                    </label>
                </div>
            </div>
            
            <div class="row">
                <div class="col col-md-12">
                    Descrição do Album:
                    <label class="textarea">
                        <?php echo $this->formElement($formCadAlbum->get('dsAlbum')); ?>
                    </label>
                </div>
            </div>
            
            <div class="row">
                <div class="col col-md-4">
                    <label class="checkbox">
                        <?php echo $this->formElement($formCadAlbum->get('stComentarioAlbum')); ?><i></i> Permitir comentários do album
                    </label>
                </div>
            </div>
            
            <?php echo $this->form()->closeTag($formCadAlbum); ?>
            
            <div id="divCadFotoInfo" class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <i class="fa fa-info-circle"></i> Para adicionar as fotos é necessário criar o Album clicando no botão "Salvar"!
                </div>
            </div>
            
            <div id="divCadFoto" class="row">
                <?php echo $this->partial('cad-foto'); ?>
            </div>
            
            <div class="row">

                <div class="col col-md-12">

                    <div id="divBtnEditar" style="float: left;">
                        <?php echo $this->formButton()->openTag($formCadAlbum->get('btnNovoCadAlbum')); ?>
                        <?php echo '<i class="fa fa-plus"></i>' . $formCadAlbum->get('btnNovoCadAlbum')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>
                    </div>

                    <?php echo $this->formButton()->openTag($formCadAlbum->get('btnGravarAlbum')); ?>
                    <?php echo '<i class="fa fa-save"></i>' . $formCadAlbum->get('btnGravarAlbum')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formCadAlbum->get('btnVoltarCadAlbum')); ?>
                    <?php echo '<i class="fa fa-arrow-left"></i>' . $formCadAlbum->get('btnVoltarCadAlbum')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>
                </div>

            </div>
            
        </div>
        <!-- end cut -->

    </div>
    <!-- /BASIC FORM -->


</div>