<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/album-principal.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/foto-perfil.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/foto-capa.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/foto-horizontal.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/foto-vertical.js'; ?>"></script>

<?php echo $this->partial('cad-album-principal'); ?>
<!-- BASIC FORM -->
<div class="panel panel-light margin-bottom8">
    <div class="panel-heading">
        <h3 id="tituloAlbumPrincipalPsq" class="panel-title bold"></h3>
    </div>
    <!-- TOGGLE -->
    <div class="toggle toggle toggle-accordion">

        <div class="toggle toggle active">
            <?php echo $this->partial('cad-foto-perfil'); ?>
        </div>

        <div class="toggle toggle">
            <?php echo $this->partial('cad-foto-capa'); ?>
        </div>

        <div class="toggle toggle">
            <?php echo $this->partial('cad-foto-horizontal'); ?>
        </div>

        <div class="toggle toggle">
            <?php echo $this->partial('cad-foto-vertical'); ?>
        </div>

    </div>
    <!-- /TOGGLE -->
</div>