<script>
    top.idClientePsq = '<?php echo $this->idCliente; ?>';
</script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/psq-meus-albuns.js'; ?>"></script>
<?php $formPsqMeusAlbuns = $this->formPsqMeusAlbuns; ?>
<?php $formPsqMeusAlbuns->prepare(); ?>
<?php echo $this->form()->openTag($formPsqMeusAlbuns); ?>
<?php echo $this->formElement($formPsqMeusAlbuns->get('idClientePsqMeusAlbuns')); ?>
<div style="display: none;">
    <?php echo $this->formButton()->openTag($formPsqMeusAlbuns->get('btnPesquisarMeusAlbuns')); ?>
    <?php echo '<i class="fa fa-search"></i>' . $formPsqMeusAlbuns->get('btnPesquisarMeusAlbuns')->getLabel(); ?>
    <?php echo $this->formButton()->closeTag(); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
<div id="tableMeusAlbuns"></div>