<script type="text/javascript" src="<?php echo $this->basePath() . '/js/album-foto/psq-minhas-fotos.js'; ?>"></script>
<?php $formPsqMinhasFotos = $this->formPsqMinhasFotos; ?>
<?php $formPsqMinhasFotos->prepare(); ?>
<?php echo $this->form()->openTag($formPsqMinhasFotos); ?>
<?php echo $this->formElement($formPsqMinhasFotos->get('idClientePsq')); ?>
<div style="display: none;">
    <?php echo $this->formButton()->openTag($formPsqMinhasFotos->get('btnPesquisarMinhasFotos')); ?>
    <?php echo '<i class="fa fa-search"></i>' . $formPsqMinhasFotos->get('btnPesquisarMinhasFotos')->getLabel(); ?>
    <?php echo $this->formButton()->closeTag(); ?>
</div>
<?php echo $this->form()->closeTag(); ?>
<div id="tableMinhasFotos"></div>