<!-- CONTENT -->
<div id="psqAlbum">

    <?php $formPsqAlbum = $this->formPsqAlbum; ?>
    <?php $formPsqAlbum->prepare(); ?>

        
        <?php echo $this->form()->openTag($formPsqAlbum); ?>

        <!-- BASIC FORM -->
        <div class="panel panel-light margin-bottom8">

            <div class="panel-heading">
                <h3 id="tituloAlbumPsq" class="panel-title bold"></h3>
            </div>

            <?php echo $this->formElement($formPsqAlbum->get('idClientePsqAlbum')); ?>
            
            <div class="panel-body">

                <div class="row">

                    <div class="col col-md-6">
                        Cliente:
                        <label class="input">
                            <?php echo $this->formElement($formPsqAlbum->get('idClienteSelectPsqAlbum')); ?>
                        </label>
                    </div>
                    
                    <div class="col col-md-6">
                        Situação:
                        <label class="input">
                            <?php echo $this->formElement($formPsqAlbum->get('stAlbumPsq')); ?>
                        </label>
                    </div>

                </div>

                <div class="row">

                    <div class="col col-md-6">
                        Tipo:
                        <label class="input">
                            <?php echo $this->formElement($formPsqAlbum->get('tpAlbumPsq')); ?>
                        </label>
                    </div>

                    <div class="col col-md-6">
                        Nome do Album:
                        <label class="input">
                            <i class="icon-append fa fa-pencil"></i>    
                            <?php echo $this->formElement($formPsqAlbum->get('noAlbumPsq')); ?>
                        </label>
                    </div>

                </div>

                <div class="row">
                    <?php echo $this->formButton()->openTag($formPsqAlbum->get('btnPesquisarAlbum')); ?>
                    <?php echo '<i class="fa fa-search"></i>' . $formPsqAlbum->get('btnPesquisarAlbum')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsqAlbum->get('btnNovoAlbum')); ?>
                    <?php echo '<i class="fa fa-plus"></i>' . $formPsqAlbum->get('btnNovoAlbum')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>
                </div>
                <!-- end cut -->

            </div>

        </div>
        <!-- /BASIC FORM -->

        <div id="tableAlbums"></div>

        <?php echo $this->form()->closeTag(); ?>

    <br />
    &nbsp;
    <br />
    &nbsp;

</div>