<?php

namespace ConfigPaginaPerfil\Entity\Repository;

use ConfigPaginaPerfil\Entity\ConfigPaginaPerfilEntity;
use Doctrine\ORM\EntityRepository;
use Zend\Stdlib\Hydrator;

/**
 * ConfigPaginaPerfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigPaginaPerfilRepository extends EntityRepository {

    public function inserirConfigPaginaPerfil($param = array()) {
        $entity = new ConfigPaginaPerfilEntity($param);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function editarConfigPaginaPerfil($param = array()) {
        $entity = $this->getEntityManager()->getReference('ConfigPaginaPerfil\Entity\ConfigPaginaPerfilEntity', $param['idConfigPaginaPerfil']);
        (new Hydrator\ClassMethods())->hydrate($param, $entity);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function selecionarConfigPaginaPerfil($id) {
        $repository = $this->find($id);
        return $repository;
    }

    public function selecionarConfigPaginaPerfilBy($param) {
        $repository = $this->findBy($param);
        return $repository;
    }

}
