<?php

namespace Avaliacao\Entity\Repository;

use Avaliacao\Entity\AvaliacaoEntity;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

/**
 * AvaliacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvaliacaoRepository extends EntityRepository {

    public function verificarNomeExistente($param) {
        $banner = $this->createQueryBuilder('a')
                        ->innerJoin('a.idCliente', 'b')
                        ->andWhere('a.idCliente = :idCliente')
                        ->setParameter('idCliente', $param['idCliente'])
                        ->andWhere('a.dsAvaliacao LIKE :dsAvaliacao')
                        ->setParameter('dsAvaliacao', $param['dsAvaliacao'])
                        ->getQuery()->getOneOrNullResult();
        if (!is_null($banner)) {
            if ($param['idAvaliacao'] != $banner->getIdAvaliacao()) {
                return $banner;
            }
        }
        return false;
    }

    public function inserirAvaliacao($param = array()) {
        $entity = new AvaliacaoEntity($param);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function editarAvaliacao($param = array()) {
        $entity = $this->getEntityManager()->getReference('Avaliacao\Entity\AvaliacaoEntity', $param['idAvaliacao']);
        (new Hydrator\ClassMethods())->hydrate($param, $entity);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function selecionarAvaliacao($id) {
        $repository = $this->find($id);
        return $repository;
    }

    public function selecionarAvaliacaoBy($param) {
        $repository = $this->findBy($param);
        return $repository;
    }

    public function listarAvaliacaosPaginado($param = array(), $pagina = 1, $itens = 10) {
        $queryCreate = $this->criarConsultaAvaliacaos($param);

        $paginado = new ORMPaginator($queryCreate->getQuery());
        $paginado->setUseOutputWalkers(FALSE);

        $adapter = new DoctrineAdapter($paginado);

        $paginator = new Paginator($adapter);
        $paginator->setDefaultItemCountPerPage($itens);
        $paginator->setCurrentPageNumber($pagina);

        return $paginator;
    }

    private function criarConsultaAvaliacaos($param = array()) {
        $query = $this->getEntityManager()->createQueryBuilder();
        $query->select(array('a.idAvaliacao', 'a.tpAvaliacao',
                    'a.dtInicio', 'a.dtFim', 'b.idCliente', 'b.noCliente'))
                ->from('Avaliacao\Entity\AvaliacaoEntity', 'a')
                ->innerJoin('a.idCliente', 'b');
        if (!empty($param['noClientePsq'])) {
            $query->andWhere("b.noCliente LIKE :noCliente")
                    ->setParameter('noCliente', "%{$param['noClientePsq']}%");
        }
        if ($param['tpAvaliacaoPsq'] != "T") {
            $query->andWhere("a.tpAvaliacao = :tpAvaliacaoPsq")
                    ->setParameter('tpAvaliacaoPsq', $param['tpAvaliacaoPsq']);
        }
        $query->addOrderBy('a.idAvaliacao', 'DESC');
        return $query;
    }

    public function excluirAvaliacao($repository) {
        $this->getEntityManager()->remove($repository);
        $this->getEntityManager()->flush();
        return $repository;
    }

}
