<!--Scripts JS-->
<script type="text/javascript" src="<?php echo $this->basePath() . '/js/agenda/configuracoes.js'; ?>"></script>
<!--Scripts JS END-->


<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="<?php echo $this->basePath() . '/perfil' ?>">Administração</a></li>
                <li class="active">Agenda</li>
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                Controle de Eventos da Agenda
            </h2><!-- /Page Title -->
        </header>
    </div>			
</section>
<!-- /PAGE TOP -->

<div class="container">
    <?php echo $this->partial('tela-inicio',array('arrayEventosPendentes'=>$this->arrayEventosPendentes)); ?>
</div>