<?php

namespace Video\Entity\Repository;

use Video\Entity\VideoEntity;
use Doctrine\ORM\EntityRepository;
use DoctrineORMModule\Paginator\Adapter\DoctrinePaginator as DoctrineAdapter;
use Doctrine\ORM\Tools\Pagination\Paginator as ORMPaginator;
use Zend\Paginator\Paginator;
use Zend\Stdlib\Hydrator;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository {

    public function verificarNomeExistente($param) {
        /**
         * @var $cache \Video\Entity\VideoEntity
         */
        $cache = $this->createQueryBuilder('a')
                        ->innerJoin('a.idCliente', 'b')
                        ->andWhere('a.idCliente = :idCliente')
                        ->setParameter('idCliente', $param['idCliente'])
                        ->andWhere('a.dsVideo LIKE :dsVideo')
                        ->setParameter('dsVideo', $param['dsVideo'])
                        ->getQuery()->getOneOrNullResult();
        if (!is_null($cache)) {
            if ($param['idVideo'] != $cache->getIdVideo()) {
                return $cache;
            }
        }
        return false;
    }

    public function inserirVideo($param = array()) {
        $entity = new VideoEntity($param);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function editarVideo($param = array()) {
        $entity = $this->getEntityManager()->getReference('Video\Entity\VideoEntity', $param['idVideo']);
        (new Hydrator\ClassMethods())->hydrate($param, $entity);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();

        return $entity;
    }

    public function selecionarVideo($id) {
        $repository = $this->find($id);
        return $repository;
    }

    public function selecionarVideoBy($param) {
        $repository = $this->findBy($param);
        return $repository;
    }

    public function listarVideosPaginado($param = array(), $pagina = 1, $itens = 10) {
        $queryCreate = $this->criarConsultaVideos($param);

        $paginado = new ORMPaginator($queryCreate->getQuery());
        $paginado->setUseOutputWalkers(FALSE);

        $adapter = new DoctrineAdapter($paginado);

        $paginator = new Paginator($adapter);
        $paginator->setDefaultItemCountPerPage($itens);
        $paginator->setCurrentPageNumber($pagina);

        return $paginator;
    }

    private function criarConsultaVideos($param = array()) {
        $query = $this->getEntityManager()->createQueryBuilder();
        $query->select(array('a.idVideo', 'a.dsVideo', 'a.tiVideo', 'a.tpVideo', 'b.idCliente'))
                ->from('Video\Entity\VideoEntity', 'a')
                ->innerJoin('a.idCliente', 'b');
        if ($param['idClientePsq'] != "") {
            $query->andWhere("a.idCliente = :idClientePsq")
                    ->setParameter('idClientePsq', $param['idClientePsq']);
        }
        if ($param['tpVideoPsq'] != "T") {
            $query->andWhere("a.tpVideo = :tpVideoPsq")
                    ->setParameter('tpVideoPsq', $param['tpVideoPsq']);
        }
        if (!empty($param['dsVideoPsq'])) {
            $query->andWhere("a.dsVideo LIKE :dsVideoPsq")
                    ->setParameter('dsVideoPsq', "{$param['dsVideoPsq']}%");
        }
        $query->addOrderBy('a.idVideo', 'DESC');

//        echo '<pre/>';
//        print_r($query->getQuery()->getSQL());
//        die;

        return $query;
    }

    public function excluirVideo($repository) {
        $this->getEntityManager()->remove($repository);
        $this->getEntityManager()->flush();
        return $repository;
    }

}
