<!-- CONTENT -->
<div id="psqUsuario">

    <?php $formPsqUsuario = $this->formPsqUsuario; ?>
    <?php $formPsqUsuario->prepare(); ?>

    <div class="container">

        <?php echo $this->form()->openTag($formPsqUsuario); ?>

        <!-- BASIC FORM -->
        <div class="panel panel-light margin-bottom8">

            <div class="panel-heading">
                <h3 id="tituloUsuarioPsq" class="panel-title bold"></h3>
            </div>

            <div class="panel-body">

                <div class="row">

                    <div class="form-group col-md-6">
                        <label class="control-label" for="loginPsq">Login:</label>
                        <div class="input-group">
                            <?php echo $this->formElement($formPsqUsuario->get('loginPsq')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-user"></span>
                            </span>
                        </div>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="control-label" for="emailPsq">Email:</label>
                        <div class="input-group">
                            <?php echo $this->formElement($formPsqUsuario->get('emailPsq')); ?>
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-envelope"></span>
                            </span>
                        </div>
                    </div>

                </div>

                <div class="row">

                    <div class="form-group col-md-6">
                        <label class="control-label" for="tpUsuarioPsq">Perfil:</label>
                        <?php echo $this->formElement($formPsqUsuario->get('tpUsuarioPsq')); ?>
                    </div>

                    <div class="form-group col-md-6">
                        <label class="control-label" for="stUsuarioPsq">Situação:</label>
                        <?php echo $this->formElement($formPsqUsuario->get('stUsuarioPsq')); ?>
                    </div>

                </div>

                <div class="row">
                    <div class="form-group col-md-12">
                        <?php echo $this->formButton()->openTag($formPsqUsuario->get('btnPesquisar')); ?>
                        <?php echo '<i class="glyphicon glyphicon-search"></i> ' . $formPsqUsuario->get('btnPesquisar')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>

                        <?php echo $this->formButton()->openTag($formPsqUsuario->get('btnNovo')); ?>
                        <?php echo '<i class="glyphicon glyphicon-plus"></i> ' . $formPsqUsuario->get('btnNovo')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>

                        <?php echo $this->formButton()->openTag($formPsqUsuario->get('btnVoltar')); ?>
                        <?php echo '<i class="fa fa-arrow-left"></i>' . $formPsqUsuario->get('btnVoltar')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>
                    </div>
                </div>

            </div>
            <!-- end cut -->

        </div>
        <!-- /BASIC FORM -->

        <div id="tableUsuarios"></div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
    <!-- /CONTENT -->

</div>