<?php

namespace Visualizacao\Entity\Repository;

use Visualizacao\Entity\VisualizacaoEntity;
use Doctrine\ORM\EntityRepository;

/**
 * VisualizacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisualizacaoRepository extends EntityRepository {

    public function inserirVisualizacao($param = array()) {
        $entity = new VisualizacaoEntity($param);

        $this->getEntityManager()->persist($entity);
        $this->getEntityManager()->flush();
        return $entity;
    }

}
