<!-- CONTENT -->
<div id="cadContato">
    <!-- registration form -->
    <?php $formCad = $this->formCad; ?>
    <?php $formCad->prepare(); ?>

    <div class="container">

        <?php echo $this->form()->openTag($formCad); ?>

        <!-- BASIC FORM -->
        <div class="panel panel-light margin-bottom8">

            <div class="panel-heading">
                <h3 id="tituloContato" class="panel-title bold"></h3>
            </div>

            <div class="panel-body">

                <?php echo $this->formElement($formCad->get('idContato')); ?>

                <div class="row">
                    
                    <div class="col col-md-6">
                            Assunto:
                        <label class="input">
                            <?php echo $this->formElement($formCad->get('idAssunto')); ?>
                        </label>
                    </div>
                    
                    <div class="col col-md-6">
                            Status:
                        <label class="input">
                            <?php echo $this->formElement($formCad->get('status')); ?>
                        </label>
                    </div>
                    
                </div>
                
                <div class="row">

                    <div class="col col-md-6">
                        Nome:
                        <label class="input">
                            <i class="icon-append fa fa-user"></i>
                            <?php echo $this->formElement($formCad->get('nome')); ?>
                            <b class="tooltip tooltip-bottom-right">(*) Obrigatório</b>
                        </label>
                    </div>

                    <div class="col col-md-6">
                        Email:
                        <label class="input">
                            <i class="icon-append fa fa-envelope"></i>
                            <?php echo $this->formElement($formCad->get('email')); ?>
                            <b class="tooltip tooltip-bottom-right">(*) Obrigatório - Informação sigilosa.</b>
                        </label>
                    </div>
                    
                </div>

                <div class="row">
                    <div class="col col-md-12">
                        Assunto:
                        <label class="input">
                            <i class="icon-append fa fa-pencil"></i>
                            <?php echo $this->formElement($formCad->get('assunto')); ?>
                            <b class="tooltip tooltip-bottom-right">(*) Obrigatório</b>
                        </label>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col col-md-12">
                        Mensagem:
                        <label class="input">
                            <textarea required maxlength="5000" data-msg-required="Please enter your message." rows="7" class="form-control" name="mensagem" id="mensagem"></textarea>
                        </label>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col col-md-12">
                        <?php echo $this->formButton()->openTag($formCad->get('btnGravar')); ?>
                        <?php echo '<i class="fa fa-save"></i>' . $formCad->get('btnGravar')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>
                        
                        <?php echo $this->formButton()->openTag($formCad->get('btnVoltarCad')); ?>
                        <?php echo '<i class="fa fa-arrow-left"></i>' . $formCad->get('btnVoltarCad')->getLabel(); ?>
                        <?php echo $this->formButton()->closeTag(); ?>
                    </div>
                </div>


            </div>
            <!-- end cut -->

        </div>
        <!-- /BASIC FORM -->

    </div>
    
    <?php echo $this->form()->closeTag($formCad); ?>

</div>