<!-- CONTENT -->
<div id="psqContato">

    <?php $formPsq = $this->formPsq; ?>
    <?php $formPsq->prepare(); ?>

    <div class="container">
        
        <?php echo $this->form()->openTag($formPsq); ?>

        <!-- BASIC FORM -->
        <div class="panel panel-light margin-bottom8">

            <div class="panel-heading">
                <h3 class="panel-title bold"> Pesquisar Contatos</h3>
            </div>

            <div class="panel-body">

                <div class="row">
                    <section class="col col-md-6">
                        <label class="input">
                            <i class="icon-append fa fa-user"></i>    
                            <?php echo $this->formElement($formPsq->get('nomePsq')); ?>
                        </label>
                    </section>
                    <section class="col col-md-6">
                        <label class="input">
                            <i class="icon-append fa fa-envelope"></i>
                            <?php echo $this->formElement($formPsq->get('emailPsq')); ?>
                        </label>
                    </section>
                </div>

                <div class="row">
                    <?php echo $this->formButton()->openTag($formPsq->get('btnPesquisar')); ?>
                    <?php echo '<i class="fa fa-search"></i>' . $formPsq->get('btnPesquisar')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsq->get('btnNovo')); ?>
                    <?php echo '<i class="fa fa-plus"></i>' . $formPsq->get('btnNovo')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsq->get('btnVoltar')); ?>
                    <?php echo '<i class="fa fa-arrow-left"></i>' . $formPsq->get('btnVoltar')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>
                </div>
                <!-- end cut -->

            </div>

        </div>
        <!-- /BASIC FORM -->

        <div id="tableContatos"></div>

        <?php echo $this->form()->closeTag(); ?>

    </div>
    <!-- /CONTENT -->
    
    <br />
    &nbsp;
    <br />
    &nbsp;

</div>