<script type="text/javascript" src="<?php echo $this->basePath() . '/js/config-pagina-perfil/config-pagina-perfil.js'; ?>"></script>
<!-- registration form -->
<?php $formCadConfigPaginaPerfil = $this->formCadConfigPaginaPerfil; ?>
<?php $formCadConfigPaginaPerfil->prepare(); ?>
<?php echo $this->form()->openTag($formCadConfigPaginaPerfil); ?>

<!-- BASIC FORM -->
<div class="panel panel-light margin-bottom8">

    <div class="panel-heading">
        <h3 id="tituloConfigPaginaPerfil" class="panel-title bold"></h3>
    </div>

    <div class="panel-body">

        <?php echo $this->formElement($formCadConfigPaginaPerfil->get('idConfigPaginaPerfil')); ?>
        <?php echo $this->formElement($formCadConfigPaginaPerfil->get('idUsuarioConfigPaginaPerfil')); ?>
        
        <div class="row">

            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <td>Exibir Banner Principal na página de Perfil?</td>
                        <td>
                            <section>
                                <div class="inline-group">
                                    <label class="radio"><input type="radio" name="stBannerPrincipal" value="1" checked><i></i>Sim</label>
                                    <label class="radio"><input type="radio" name="stBannerPrincipal" value="2"><i></i>Não</label>
                                </div>
                            </section>	
                        </td>
                    </tr>
                    <tr>
                        <td>Exibir Informações do Usuário na página de Perfil?</td>
                        <td>
                            <section>
                                <div class="inline-group">
                                    <label class="radio"><input type="radio" name="stInfoUsuario" value="1" checked><i></i>Sim</label>
                                    <label class="radio"><input type="radio" name="stInfoUsuario" value="2"><i></i>Não</label>
                                </div>
                            </section>	
                        </td>
                    </tr>
                    <tr>
                        <td>Exibir quadro "Minhas Favoritas" na página de Perfil?</td>
                        <td>
                            <section>
                                <div class="inline-group">
                                    <label class="radio"><input type="radio" name="stMinhasFavoritas" value="1" checked><i></i>Sim</label>
                                    <label class="radio"><input type="radio" name="stMinhasFavoritas" value="2"><i></i>Não</label>
                                </div>
                            </section>	
                        </td>
                    </tr>
                    <tr>
                        <td>Exibir quadro "Destaques Clube Luxúria" na página de Perfil?</td>
                        <td>
                            <section>
                                <div class="inline-group">
                                    <label class="radio"><input type="radio" name="stDestaques" value="1" checked><i></i>Sim</label>
                                    <label class="radio"><input type="radio" name="stDestaques" value="2"><i></i>Não</label>
                                </div>
                            </section>	
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">Escolher Plano de Fundo do Site</td>
                    </tr>
                </tbody>
            </table>

        </div>
            
        <div class="row">
            
            <div class="col-md-4">
                <label class="radio nomargin">
                    <input type="radio" name="tpPlanoFundo" value="1" checked><i></i> <img id="imgPlanoFundo" class="img-responsive" src="<?php echo $this->basePath() . '/epona/images/boxed_background/12.png' ?>" alt="" />
                </label>
            </div>

            <div class="col-md-4">
                <label class="radio nomargin">
                    <input type="radio" name="tpPlanoFundo" value="2"><i></i> <img id="imgPlanoFundo" class="img-responsive" src="<?php echo $this->basePath() . '/epona/images/boxed_background/7.jpg' ?>" alt="" />
                </label>
            </div>

            <div class="col-md-4">
                <label class="radio nomargin">
                    <input type="radio" name="tpPlanoFundo" value="3"><i></i> <img id="imgPlanoFundo" class="img-responsive" src="<?php echo $this->basePath() . '/epona/images/boxed_background/8.jpg' ?>" alt="" />
                </label>
            </div>

        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <?php echo $this->formButton()->openTag($formCadConfigPaginaPerfil->get('btnGravarConfigPaginaPerfil')); ?>
                <?php echo '<i class="glyphicon glyphicon-floppy-disk"></i> ' . $formCadConfigPaginaPerfil->get('btnGravarConfigPaginaPerfil')->getLabel(); ?>
                <?php echo $this->formButton()->closeTag(); ?>
            </div>
        </div>
    </div>
    <!-- end cut -->

</div>
<!-- /BASIC FORM -->

<?php echo $this->form()->closeTag($formCadConfigPaginaPerfil); ?>