<!-- CONTENT -->
<div id="psqPagamento">

    <?php $formPsqPagamento = $this->formPsqPagamento; ?>
    <?php $formPsqPagamento->prepare(); ?>

    <?php echo $this->form()->openTag($formPsqPagamento); ?>

    <!-- BASIC FORM -->
    <div class="panel panel-light margin-bottom8">

        <div class="panel-heading">
            <h3 id="tituloPagamentoPsq" class="panel-title bold"></h3>
        </div>

        <div class="panel-body">

            <div class="row">
                <div class="form-group col-md-12">
                    <label class="control-label">Nome do Cliente:</label>
                    <div class="input-group">
                        <?php echo $this->formElement($formPsqPagamento->get('noClientePsq')); ?>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-user"></span>
                        </span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label" for="tpClientePsq">Tipo do Pagamento:</label>
                    <?php echo $this->formElement($formPsqPagamento->get('tpPagamentoPsq')); ?>
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label" for="stPagamentoPsq">Situação do Pagamento:</label>
                    <?php echo $this->formElement($formPsqPagamento->get('stPagamentoPsq')); ?>
                </div>
            </div>
            
            <div class="row">
                <div class="form-group col-md-6">
                    <label class="control-label">Data Inicio:</label>
                    <div class="input-group">
                        <?php echo $this->formElement($formPsqPagamento->get('dtInicioPsq')); ?>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label">Data Final:</label>
                    <div class="input-group">
                        <?php echo $this->formElement($formPsqPagamento->get('dtFimPsq')); ?>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-12">
                    <?php echo $this->formButton()->openTag($formPsqPagamento->get('btnPesquisarPagamento')); ?>
                    <?php echo '<i class="fa fa-search"></i>' . $formPsqPagamento->get('btnPesquisarPagamento')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsqPagamento->get('btnNovoPagamento')); ?>
                    <?php echo '<i class="fa fa-plus"></i>' . $formPsqPagamento->get('btnNovoPagamento')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsqPagamento->get('btnVoltarPagamento')); ?>
                    <?php echo '<i class="fa fa-arrow-left"></i>' . $formPsqPagamento->get('btnVoltarPagamento')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>
                </div>
            </div>
            <!-- end cut -->

        </div>

    </div>
    <!-- /BASIC FORM -->

    <div id="tablePagamentos"></div>

    <?php echo $this->form()->closeTag(); ?>

</div>