<!-- BANNER SECUNDÁRIO 01 -->
<div class="callout dark">
    <div class="container">
        <?php if (!$this->identity()) : ?>
        <div class="row">
            <div class="col-md-9"><!-- title + shortdesc -->
                <h3>Cadastre-se e seja <strong>Sócio</strong> Clube Luxúria</h3>
                <p>Como sócio você pode curtir fotos, ver videos, fazer comentários, traçar a rotas e muito mais...</p>
            </div>
            <div class="col-md-3"><!-- button -->
                <a href="<?php echo $this->basePath() . "/login"; ?>" rel="nofollow" target="_self" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i>&nbsp;Cadastre-se aqui</a>
            </div>
        </div>
        <?php else: ?>
        <div class="row">
            <div class="col-md-9"><!-- title + shortdesc -->
                <h3>Bem vindo <strong><?php echo $this->identity()->getNoUsuario(); ?></strong> (<?php echo $this->identity()->getLogin(); ?>)</h3>
                <p>Você pode curtir fotos, ver videos, fazer comentários, traçar a rotas e muito mais...</p>
            </div>
            <div class="col-md-3"><!-- button -->
                <a href="<?php echo $this->basePath() . "/perfil"; ?>" rel="nofollow" target="_self" class="btn btn-primary btn-sm"><i class="fa fa-user"></i>&nbsp;Abrir Minha Página</a>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
<!-- /BANNER SECUNDÁRIO 01 -->


<!-- SESSÃO 02 - NOVIDADES CLUBE LUXURIA -->
<section>
    <div class="container">
        <!-- LISTA NOVIDADES CLUBE LUXURIA -->
        <?php echo $this->partial('comp-anunciantes-novidades'); ?>
        <!-- /LISTA NOVIDADES CLUBE LUXURIA -->
    </div>
</section>
<!-- /SESSÃO 02 - NOVIDADES CLUBE LUXURIA -->


<?php
$imagem =  array(
    1 => ['src' => '/img/banners/banner-dubai-show.jpg', 'link' => '#'],
    2 => ['src' => '/img/banners/banner-controle-ejaculacao-precoce-01.jpg', 'link' => 'https://go.hotmart.com/G2789472L?ap=8ca1'],
    3 => ['src' => '/img/banners/banner-clinica-kiss.jpg', 'link' => '#'],
    4 => ['src' => '/img/banners/banner-controle-ejaculacao-precoce-02.jpg', 'link' => 'https://go.hotmart.com/G2789472L?ap=1a77'],
    5 => ['src' => '/img/banners/banner-controle-ejaculacao-precoce-03.jpg', 'link' => 'https://go.hotmart.com/G2789472L'],
);
$contador = count($imagem); // Criamos uma variavel para contar (count();) os dados que estão dentro do array.
$aleatorio = rand(1,$contador);
?>

<!-- CALLOUT -->
<div class="callout dark">
    <div class="container text-center">
        <a href="<?php echo $imagem[$aleatorio]['link']; ?>" target="_blank"><img src="<?php echo $this->basePath() . $imagem[$aleatorio]['src']; ?>" alt="" /></a>
    </div>
</div>
<!-- /CALLOUT -->
    
<!-- BANNER SECUNDÁRIO 02 -->
<!-- <div class="callout dark">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h3><i class="fa fa-map-marker"></i> Conheça as <strong>Rotas</strong> do Clube Luxúria</h3>
                <p>Localize no mapa a Garota mais perto de você. <strong>Obs.:</strong> Somente para usuários cadastrados.</p>
            </div>
            <div class="col-md-3">
                <a href="<?php //echo $this->basePath(); ?>/application/index/mapa" rel="nofollow" target="_self" class="btn btn-primary btn-sm"><i class="fa fa-map-marker"></i> Abrir Rotas Clube Luxúria</a>
            </div>
        </div>
    </div>
</div> -->
<!-- /BANNER SECUNDÁRIO 02 -->


<!-- SESSÃO 03 - LISTA DE ANUNCIANTES COM FILTRO DE CIDADE PARA PESQUISA -->
<section>
    <!-- LISTA DE ANUNCIANTES COM FILTRO -->
    <div class="container">
        <?php echo $this->partial('psq-anunciante-home'); ?>
    </div>
    <!-- /LISTA DE ANUNCIANTES COM FILTRO -->
</section>
<!-- /SESSAO 03 - LISTA DE ANUNCIANTES COM FILTRO DE CIDADE PARA PESQUISA -->


<?php
$contador1 = count($imagem); // Criamos uma variavel para contar (count();) os dados que estão dentro do array.
$aleatorio1 = rand(1,$contador1);
?>

<!-- CALLOUT -->
<div class="callout dark">
    <div class="container text-center">
        <a href="<?php echo $imagem[$aleatorio1]['link']; ?>" target="_blank"><img src="<?php echo $this->basePath() . $imagem[$aleatorio1]['src']; ?>" alt="" /></a>
    </div>
</div>
<!-- /CALLOUT -->
            
<!-- BANNER SECUNDÁRIO 03 -->
<!-- <div class="callout dark">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h3>Aumente seus ganhos e status profissional. Anuncie em nosso Portal</h3>
                <p>Experimente <strong>30 dias</strong> grátis!</p>
            </div>
            <div class="col-md-3">
                <a href="<?php //echo $this->basePath(); ?>/application/index/anuncie" rel="nofollow" target="_self" class="btn btn-primary btn-sm"><i class="fa fa-adn"></i> Anunciar no Portal</a>
            </div>
        </div>
    </div>
</div> -->
<!-- /BANNER SECUNDÁRIO 03 -->


<!-- SESSÃO 04 - LISTA DE ANUNCIANTES DESTAQUES -->
<section>
    <div class="container">
        <!-- LISTA DAS ANUNCIANTES DESTAQUES -->
        <?php echo $this->partial('banner-destaques'); ?>
        <!-- /LISTA DAS ANUNCIANTES DESTAQUE -->
    </div>
    <!-- /LISTA DE ANUNCIANTES DESTAQUES -->
</section>
<!-- /SESSAO 04 - LISTA DE ANUNCIANTES DESTAQUES -->
