
<!-- PREMIUM -->
<section class="alternate">
        <div class="container">

                <div class="row">
                        <div class="col-md-6">
                                <h2>Premium <strong>Features</strong></h2>
                                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing metus elit. Lorem ipsum dolor sit amet, consectetur adipiscing metus elit.</p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur imperdiet <em class="styleColor">hendrerit volutpat</em>. Sed in nunc nec ligula consectetur mollis in vel justo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent scelerisque volutpat turpis, eu hendrerit enim scel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent scelerisque volutpat turpis.</p>
                        </div>

                        <div class="col-md-6 text-center">
                                <img class="img-responsive animate_fade_in" src="<?php echo $this->basePath() . '/epona/images/demo/desktop.png';?>" alt="" />
                        </div>
                </div>

                <div class="row text-center countTo">
                        <div class="col-md-3 col-sm-6">
                                <span class="boxed radius3">
                                        <strong class="styleColor" data-to="13">13</strong>
                                        <label>Years Experience</label>
                                </span>
                        </div>

                        <div class="col-md-3 col-sm-6">
                                <span class="boxed radius3">
                                        <strong class="styleColor" data-to="12000">12000</strong>
                                        <label>Hours of Development</label>
                                </span>
                        </div>

                        <div class="col-md-3 col-sm-6">
                                <span class="boxed radius3">
                                        <strong class="styleColor" data-to="3890">3890</strong>
                                        <label>Happy Customers</label>
                                </span>
                        </div>

                        <div class="col-md-3 col-sm-6">
                                <span class="boxed radius3">
                                        <strong class="styleColor" data-to="11000">11000</strong>
                                        <label>Cups of Coffee</label>
                                </span>
                        </div>
                </div>

        </div>
</section>
<!-- /PREMIUM -->

<!-- DARK CALLOUT -->
<div class="callout dark arrow-down">
        <div class="container text-center">

                <h2>Epona Multipurpose Responsive Template</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas metus nulla, commodo a sodales sed, dignissim pretium nunc. Nam et lacus neque. Ut enim massa, sodales tempor convallis et.</p>

        </div>
</div>
<!-- /DARK CALLOUT -->

<section>
        <div class="container">

                <div class="text-center">
                        <img class="img-responsive animate_fade_in" src="<?php echo $this->basePath() . '/epona/images/demo/features.jpg'?>" alt="" />
                </div>

        </div><!-- /.container -->
</section>


<!-- DARK CALLOUT -->
<div class="callout dark arrow-up">
        <div class="container text-center">

                <h2>Explore Epona Best Included Features</h2>
                <p>Doesn't matter if you are a begginer or an advanced developer. Epona is based on <a href="http://getbootstrap.com/" target="_blank" rel="nofollow">Bootstrap</a> &ndash; tons of features for free.</p>

                <div class="divider half-margins hidden-xs"><!-- divider --></div>

                <div class="row text-left hidden-xs">
                        <div class="col-md-4 col-sm-4">
                                <ul class="list-icon spaced check-circle">
                                        <li>Fully Customizable Options</li>
                                        <li>Retina Ready For Enabled Devices</li>
                                        <li>Custom Backgrounds</li>
                                        <li>Awsome Main Menu</li>
                                        <li>Unlimited Colors / Skins</li>
                                        <li>Powerful Customization Options</li>
                                        <li>100% Valid HTML Markup</li>
                                        <li>Easy To Customize</li>
                                </ul>
                        </div>
                        <div class="col-md-4 col-sm-4">
                                <ul class="list-icon spaced check-circle">
                                        <li>One Page Parallax</li>
                                        <li>Eye-Catching CSS3 Animations</li>
                                        <li>Boxed or Wide</li>
                                        <li>Extensive Doc</li>
                                        <li>Top Notch Support Service</li>
                                        <li>Updates &amp; New Features</li>
                                        <li>Awsome Blog Design</li>
                                        <li>Awsome Shop Design</li>
                                </ul>
                        </div>
                        <div class="col-md-4 col-sm-4">
                                <ul class="list-icon spaced check-circle">
                                        <li>Custom Menu</li>
                                        <li>Font Awesome Icon Integration</li>
                                        <li>Advanced Typography</li>
                                        <li>Strong SEO Base Built In</li>
                                        <li>Unlimited Sidebar</li>
                                        <li>Multiple Widgets</li>
                                        <li>Awesome Sliders</li>
                                        <li>Fully Optimized For Speed</li>
                                </ul>
                        </div>
                </div>

        </div>
</div>
<!-- /DARK CALLOUT -->

<!-- CALLOUT -->
<div class="callout styleBackgroundColor"><!-- add "styleBackgroundColor" class for colored background and white text OR "dark" for a dark callout -->
        <div class="container">

                <div class="row">

                        <div class="col-md-9"><!-- title + shortdesc -->
                                <h3>Does Epona Convinced you?</h3>
                                <p>If so, click to buy now, including <strong>lifetime upgrade</strong> for free!</p>
                        </div>

                        <div class="col-md-3"><!-- button -->
                                <a href="#purchase" rel="nofollow" target="_blank" class="btn btn-primary btn-lg">Purchase Now</a>
                        </div>

                </div>

        </div>
</div>
<!-- /CALLOUT -->


<!-- TESTIMONIALS -->
<section>
        <div class="container">

                <header class="text-center">
                        <h2>Wow, Incredible Theme I've ever seen</h2>
                        <blockquote class="noborder nopadding nomargin">
                                <i>This is the Best Theme I have ever seen. I am a full time web dev, and this theme blows me away. I wanted to thank you for all your hard work. I am really looking forward to building my new site! I think you thought of everything and then some.</i>
                                <cite class="block">Dorin Grigoras</cite>
                        </blockquote>

                        <div class="divider half-margins"><!-- divider --></div>

                </header>

                <div class="row">
                        <div class="col-md-4">
                                <div class="testimonial classic female animate_from_bottom">
                                        <p>Praesent est laborum dolo rumes fugats untras. Etha rums ser quidem rerum facilis dolores nemis onis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                                        <cite><strong>John Doe</strong>, Customer</cite>
                                </div>
                        </div>
                        <div class="col-md-4">
                                <div class="testimonial classic male animate_from_bottom">
                                        <p>Praesent est laborum dolo rumes fugats untras. Etha rums ser quidem rerum facilis dolores nemis onis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                                        <cite><strong>John Doe</strong>, Customer</cite>
                                </div>
                        </div>
                        <div class="col-md-4">
                                <div class="testimonial classic male animate_from_bottom">
                                        <p>Praesent est laborum dolo rumes fugats untras. Etha rums ser quidem rerum facilis dolores nemis onis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                                        <cite><strong>John Doe</strong>, Customer</cite>
                                </div>
                        </div>
                </div>

                <div class="row">
                        <div class="col-md-6">
                                <div class="testimonial classic female animate_from_bottom">
                                        <p>Praesent est laborum dolo rumes fugats untras. Etha rums ser quidem rerum facilis dolores nemis onis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                                        <cite><strong>John Doe</strong>, Customer</cite>
                                </div>
                        </div>
                        <div class="col-md-6">
                                <div class="testimonial classic male animate_from_bottom">
                                        <p>Praesent est laborum dolo rumes fugats untras. Etha rums ser quidem rerum facilis dolores nemis onis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                                        <cite><strong>John Doe</strong>, Customer</cite>
                                </div>
                        </div>
                </div>

                <div class="owl-carousel animate_from_bottom text-center" data-plugin-options='{"items": 1, "singleItem": true, "navigation": false, "pagination": true, "autoPlay": true, "transitionStyle":"fadeUp"}'><!-- transitionStyle: fade, backSlide, goDown, fadeUp,  -->
                        <div class="testimonial">
                                <p>Praesent est laborum dolo rumes fugats untras. Etha rums ser quidem rerum facilis dolores nemis onis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                                <cite><strong>John Doe</strong>, Customer</cite>
                        </div>

                        <div class="testimonial">
                                <p>Donec tellus massa, tristique sit amet condim vel, facilisis quis sapien. Praesent id enim sit amet odio vulputate eleifend in in tortor. Donec tellus massa.</p>
                                <cite><strong>Jessica Doe</strong>, Customer</cite>
                        </div>

                        <div class="testimonial">
                                <p>Praesent est laborum dolo rumes fugats untras. Etha rums ser quidem rerum facilis dolores nemis onis fugats vitaes nemo minima rerums unsers sadips amets.</p>
                                <cite><strong>Dorin Doe</strong>, Customer</cite>
                        </div>

                        <div class="testimonial">
                                <p>Donec tellus massa, tristique sit amet condim vel, facilisis quis sapien. Praesent id enim sit amet odio vulputate eleifend in in tortor. Donec tellus massa.</p>
                                <cite><strong>Melissa Doe</strong>, Customer</cite>
                        </div>

                </div>

        </div>                
</section>
<!-- /TESTIMONIALS -->