<style>
    .TabelaPrecos{
        position:relative;float:left;width:Calc(50% - 20px);margin:10px;margin-bottom:25px
    }
    .TabelaPrecos table{
        width:100%;padding:5px;border-spacing:4px;border: 1px solid;
    }
    .TabelaPrecos table td{
        border: 1px solid;padding:5px
    }
    .TabelaPrecos table .Preco{
        text-align:center;width:160px
    }
    .TabelaPrecos > p,.obs{color:#808080;font-style:italic;font-size:14px;font-weight:bold}.obs{padding-left:30px}
</style>

<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="#">Anuncie</a></li>
                <li class="active">Seja uma Anunciante</li>
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                <strong>Regras de </strong> Publicidade
            </h2><!-- /Page Title -->
        </header>
    </div>
</section>
<!-- /PAGE TOP -->

<!-- PREMIUM -->
<section>
    <div class="container">

        <div class="row">
            <div class="col-md-12">

                <!--TITULOS-->
                <h2><strong>Políticas de anúncio que garantem um trabalho profissional</strong></h2>

                <p>Com o intuito de oferecer o melhor para os visitantes e anunciantes de nossa revista eletrônica, temos uma política de publicidade que garantem um trabalho profissional, ético e seguro. </p>
                <p>Com isso, oferecemos transparência a todos que usufruem do acesso e publicidade no site.</p>
                <p>As regras abaixo são aplicáveis a todos que desejam anunciar, não havendo de forma alguma qualquer tipo de exceção por qualquer motivo que seja.</p>
                <p>Veja também <a href="<?php echo $this->basePath(); ?>/application/index/anuncie" title="Veja como anunciar em nosso site">como Anunciar</a></p>

                <h3><strong>NOMES ARTÍSTICOS</strong></h3>
                <p>Não é permitida a utilização de adjetivos nem nomes artísticos de outras pessoas</p>

                <h3><strong>NÃO É PERMITIDO ANÚNCIOS DIFERENTES PARA MESMA PESSOA:</strong></h3>
                <p>O anúncio é realizado com base contratual individual relacionado a  um único CPF. </p>

                <h3><strong>PUBLICAÇÃO DE FOTOS SEM A PRESENÇA DA ANUNCIANTE</strong></h3>
                <p>Todo anuncio antes da publicação definitiva passa pela aprovação da anunciante, portanto, sem a presença da contratante a publicão não é realizada.</p>

                <h3><strong>PUBLICAÇÃO DE FOTOS SEM A APRESENTAÇÃO DO ROSTO:</strong></h3>
                <p>Não é feito a publicação do anuncio caso as fotos entregues que não tenham rosto a mostra para comprovar veracidade do ensaio. Após comprovação, faremos a remoção do rosto caso seja necessário.</p>

                <h3><strong>PUBLICAÇÃO DE ENSAIOS DIFERENTES</strong></h3>
                <p>As fotos dos anuncios são agrupadas por ensaios individualizados; não sendo permitida a mistura de fotos de ensaios diferentes em um único ensaio. Cada ensaio deve conter no mínimo 6 fotos profissionais não sendo aceito fotos caseiras amadoras.</p>

                <h3><strong>ANUNCIAR SEM RG OU CNH ORIGINAL EM MÃOS:</strong></h3>
                <p>Para publicação do anúncio é necessária alem da assinatura do contrato de publicidade a apresentação da documentação original, caso contrário não é realizada a publicação do anuncio.</p>

                <h3><strong>DEVOLUÇÃO DE VALOR PAGO PARA ANÚNCIOS:</strong></h3>
                <p>Anúncios mensais são sempre validos por 30 dias a contar da data de publicação, havendo desistência por parte da anunciante não haverá reembolso dos valores já pagos.</p>
                <p>Anúncios semanais são sempre validos por 7 dias a contar da data de publicação, havendo desistência por parte da anunciante não haverá reembolso dos valores já pagos.</p>

                <h3><strong>ACUMULO DE VALOR POR REMOÇÃO DE ANUNCIO ANTES DO VENCIMENTO:</strong></h3>
                <p>Não é aceito que acumule dias para outros meses ou semanas, caso a anunciante faça a remoção do anuncio no mês ou semana corrente.</p>

                <h3><strong>ATRASO DE MENSALIDADE:</strong></h3>
                <p>Havendo atraso da mensalidade, seu anuncio será removido, não existe  tolerância de dias, respeitando outras anunciantes que efetuaram o pagamento em seu devido vencimento. Caso o anuncio seja removido, para fazer nova publicação, os valores serão exatamente como de um novo anuncio. </p>

                <h3><strong>ENVIO/GRAVAÇÃO DE FOTOS:</strong></h3>
                <p>Não enviamos por e-mail ou qualquer outro meio, não gravamos em pendrives ou qualquer outra mídia fotos entregues para nossa equipe para publicação de anuncio. </p>

                <h3><strong>REATIVAÇÃO DE ANUNCIO SEM LIGAÇÃO DE TELEFONE CADASTRADO</strong></h3>
                <p>Caso queira reativar o anuncio com as mesmas fotos já postadas anteriormente, somente será permitido caso a anunciante faça a ligação de um dos telefones previamente cadastrados, fazendo as confirmações de seus dados pessoais.</p>

                <h3><strong>ALTERAÇÃO DE ANUNCIO SEM LIGAÇÃO DE TELEFONE CADASTRADO</strong></h3>
                <p>Caso queira alterar o anuncio, exceto fotos, somente será permitido caso a anunciante faça a ligação de um dos telefones previamente cadastrados, fazendo as confirmações de seus dados pessoais.</p>

                <h3><strong>CANCELAMENTO DE RESERVA DE ANUNCIO EM EVIDENCIA</strong></h3>
                <p>Caso faça o cancelamento de reserva sem antecedência de 7 dias, a anunciante perde o direito de novas reservas sem o pagamento antecipado da mesma.</p>

                <h3><strong>EXPRESSÕES RELATIVAS AO TRATAMENTO DE IMAGENS</strong></h3>
                <p>Expressões como "Pouco Photoshop", "Sem Photoshop", "Sem Tratamento" não podem ser utilizadas no anuncio. Prezamos pela igualdade de publicidade entre todas anunciantes e este tipo de expressão caracteriza diferenciação, fato que não pode ser comprovado pela equipe no ato da publicação</p>

                <h3><strong>FOTOS COM CARACTERES E/OU ÍCONES</strong></h3>
                <p>Não é permitido postagem de fotos com bandeiras de cartões de crédito e/ou débito e/ou palavras nas fotos dos anúncios.</p>

                <h3><strong>FOTOS DE CAPA, DESTAQUES EM PRETO E BRANCO E SEPHIA</strong></h3>
                <p>Para haver uma padronização de igualdade nos anuncios as fotos devem ser em cores. Nào é impedido que haja fotos com este perfil no ensaio</p>

                <h3><strong>FOTOS COM MONTAGENS OU RECORTES</strong></h3>
                <p>As fotos devem obedecer o mesmo padrão adotado no site em proporção retangular</p>

                <h3><strong>FOTOS COM TERCEIROS</strong></h3>
                <p>Não é permitido postagem de fotos com homens, ou mulheres que não tenham anuncio individual postado no site.</p>

            </div>
        </div>

        <div class="divider">
            <i class="fa fa-star"></i>
        </div>
        <!-- LISTA DAS ANUNCIANTES DESTAQUE -->
        <?php echo $this->partial('banner-destaques'); ?>
        <!-- /LISTA DAS ANUNCIANTES DESTAQUE -->
    </div>
</section>
<!-- /PREMIUM -->