<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">
        <header>
            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="#">Página</a></li>
                <li class="active">Termos de Serviço</li>
            </ul><!-- /breadcrumb -->
            <h2><!-- Page Title -->
                Termos de Serviço
            </h2><!-- /Page Title -->
        </header>
    </div>			
</section>
<!-- /PAGE TOP -->

<!-- CONTENT -->
<section>
    <div class="container">

        <div class="col-md-12"  style="background: rgba(0,0,0,0.5); vertical-align: top; margin-top: 20px;">
            <br>
            <h3 style="padding: 5px; text-align: center;"><b>Termos de Serviços & Políticas de Privacidade</b></h3>

            <div class="col-md-12"  style="margin-top: 20px;">
                <p class="col-md-12" style="text-align: justify;">
                    &nbsp;&nbsp;&nbsp;&nbsp; O site Clube Luxúria tem por objetivo divulgar os serviços de modelos cadastrado(a)s nesse site para,
                    qualquer interessado que esteja dentro das nossas regras de utilização do site como descritos nos "Termos de Serviços & Políticas de Privacidade". 
                    Este site apenas divulga os serviços nos maiores e melhores buscadores da internet. 
                </p>
                <p class="col-md-12" style="text-align: justify;">
                    &nbsp;&nbsp;&nbsp;&nbsp; O site não tem absolutamente nenhum tipo de envolvimento e/ou interferência nas atividades externas do(a)s modelos aqui anunciado(a)s 
                    dessa maneira, o site Clube Luxúria não agencia e não faz nenhum tipo de indicação, as informações aqui divulgadas são de total responsabilidade 
                    do(a) anunciante.
                </p>
                <p class="col-md-12" style="text-align: justify;">
                    &nbsp;&nbsp;&nbsp;&nbsp; Qualquer pessoa pode anunciar no site Clube Luxúria desde que, tenha 18 anos ou mais, possua documento válido com foto (CNH, Identidade e etc...)
                    e mantenha o pagamento do(s) serviço(s) prestado(s) em dia. Com o intuito de manter como melhor e mais confiável catálogo de modelos do Brasil, o/a
                    anunciante poderá ser impedido(a) de se registrar no site por diversos motivos, esses serão avaliados pelos responsáveis pelo site, podendo o/a 
                    anunciante ser banido(a) do site por tempo indeterminado.
                </p>
                <p class="col-md-12" style="text-align: justify;">
                    &nbsp;&nbsp;&nbsp;&nbsp; Dos usuários que utilizarem o site para seus devidos fins, ao clicar em "Entrar no Site", este obrigatoriamente deverá possuir 18 anos ou mais,
                    não poderá utilizar de termos inadequados para difamar o(a)s anunciantes aqui cadastrado(a)s, não poderá copiar quaisquer conteúdo e fotos dos perfis
                    aqui apresentados. Pode ao usuário denunciar e avaliar o/a anunciante colaborando assim evitar propagandas falsas de perfis apresentados no site.
                </p>

                <br>
                <p class="col-md-12" style="text-align: right;">
                    &nbsp;&nbsp;&nbsp;&nbsp; Atenciosamente, equipe Clube Luxúria!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </p>
            </div>
            <br>
        </div>

        <a href="<?php echo $this->_basePath().'/';?>" rel="nofollow">Voltar para <strong>Página Inicial</strong></a>

    </div>
</section>
<!-- /CONTENT -->