<script>
    $(document).ready(function () {
        $("#dtInicioPsq").val('<?php $timestamp = strtotime("-15 days");echo date('d/m/Y', $timestamp); ?>');
        $("#dtFimPsq").val('<?php echo date("d/m/Y"); ?>');
    });
</script>
<!-- CONTENT -->
<div id="psqDepoimento">

    <?php $formPsqDepoimento = $this->formPsqDepoimento; ?>
    <?php $formPsqDepoimento->prepare(); ?>
    <?php echo $this->form()->openTag($formPsqDepoimento); ?>

    <!-- BASIC FORM -->
    <div class="panel panel-light margin-bottom8">

        <div class="panel-heading">
            <h3 id="tituloDepoimentoPsq" class="panel-title bold"></h3>
        </div>

        <?php echo $this->formElement($formPsqDepoimento->get('idClientePsqDepoimento')); ?>

        <div class="panel-body">

            <div class="row">

                <div class="col col-md-6">
                    Cliente:
                    <label class="input">
                        <?php echo $this->formElement($formPsqDepoimento->get('idClienteSelectPsqDepoimento')); ?>
                    </label>
                </div>

                <div class="col col-md-6">
                    Usuario:
                    <label class="input">
                        <?php echo $this->formElement($formPsqDepoimento->get('idUsuarioSelectPsqDepoimento')); ?>
                    </label>
                </div>

            </div>

            <div class="row">

                <div class="col col-md-6">
                    Data Início*:
                    <label class="input">
                        <i class="icon-append fa fa-calendar"></i>
                        <?php echo $this->formElement($formPsqDepoimento->get('dtInicioPsq')); ?>
                    </label>
                </div>

                <div class="col col-md-6">
                    Data Fim:
                    <label class="input">
                        <i class="icon-append fa fa-calendar"></i>
                        <?php echo $this->formElement($formPsqDepoimento->get('dtFimPsq')); ?>
                    </label>
                </div>

            </div>

            <div class="row">
                <?php echo $this->formButton()->openTag($formPsqDepoimento->get('btnPesquisarDepoimento')); ?>
                <?php echo '<i class="fa fa-search"></i>' . $formPsqDepoimento->get('btnPesquisarDepoimento')->getLabel(); ?>
                <?php echo $this->formButton()->closeTag(); ?>

                <?php echo $this->formButton()->openTag($formPsqDepoimento->get('btnNovoDepoimento')); ?>
                <?php echo '<i class="fa fa-plus"></i>' . $formPsqDepoimento->get('btnNovoDepoimento')->getLabel(); ?>
                <?php echo $this->formButton()->closeTag(); ?>
            </div>
            <!-- end cut -->

        </div>

    </div>
    <!-- /BASIC FORM -->

    <div id="tableDepoimentos"></div>

    <?php echo $this->form()->closeTag(); ?>

    <br />
    &nbsp;
    <br />
    &nbsp;

</div>