<?php $formCadCaracteristica = $this->formCadCaracteristica; ?>
<?php $formCadCaracteristica->prepare(); ?>

<div class="container">

    <?php echo $this->form()->openTag($formCadCaracteristica); ?>

    <?php echo $this->formElement($formCadCaracteristica->get('idCaracteristica')); ?>
    
    <!-- BASIC FORM -->
    <div class="panel panel-light margin-bottom8">

        <div class="panel-heading">
            <h3 id="tituloCaracteristica" class="panel-title bold"></h3>
        </div>

        <div class="panel-body">

            <div class="row">

                <div class="form-group col-md-6">
                    <label class="control-label" for="tpCaracteristica">Tipo:</label>
                    <?php echo $this->formElement($formCadCaracteristica->get('tpCaracteristica')); ?>
                </div>

                <div class="form-group col-md-6">
                    <label class="control-label" for="noCaracteristica">Característica:</label>
                    <div class="input-group">
                        <?php echo $this->formElement($formCadCaracteristica->get('noCaracteristica')); ?>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </span>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="form-group col-md-12">
                    <?php echo $this->formButton()->openTag($formCadCaracteristica->get('btnPesquisarCaracteristica')); ?>
                    <?php echo '<i class="glyphicon glyphicon-search"></i> ' . $formCadCaracteristica->get('btnPesquisarCaracteristica')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formCadCaracteristica->get('btnNovoCaracteristica')); ?>
                    <?php echo '<i class="glyphicon glyphicon-plus"></i> ' . $formCadCaracteristica->get('btnNovoCaracteristica')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formCadCaracteristica->get('btnGravarCaracteristica')); ?>
                    <?php echo '<i class="glyphicon glyphicon-floppy-disk"></i> ' . $formCadCaracteristica->get('btnGravarCaracteristica')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formCadCaracteristica->get('btnVoltarCaracteristica')); ?>
                    <?php echo '<i class="fa fa-arrow-left"></i>' . $formCadCaracteristica->get('btnVoltarCaracteristica')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>
                </div>
            </div>

        </div>
        <!-- end cut -->

    </div>
    <!-- /BASIC FORM -->

    <div id="tableCaracteristicas"></div>

    <?php echo $this->form()->closeTag(); ?>

</div>
<!-- /CONTENT -->