<!-- CONTENT -->
<div id="psqVideo">

    <?php $formPsqVideo = $this->formPsqVideo; ?>
    <?php $formPsqVideo->prepare(); ?>

        <?php echo $this->form()->openTag($formPsqVideo); ?>

        <!-- BASIC FORM -->
        <div class="panel panel-light margin-bottom8">

            <div class="panel-heading">
                <h3 id="tituloVideoPsq" class="panel-title bold"></h3>
            </div>

            <?php echo $this->formElement($formPsqVideo->get('idClientePsqVideo')); ?>
            
            <div class="panel-body">

                <div class="row">

                    <div class="col col-md-6">
                        Cliente:
                        <label class="input">
                            <?php echo $this->formElement($formPsqVideo->get('idClienteSelectPsqVideo')); ?>
                        </label>
                    </div>
                    
                    <div class="col col-md-6">
                        Tipo Video:
                        <label class="input">
                            <?php echo $this->formElement($formPsqVideo->get('tpVideoPsq')); ?>
                        </label>
                    </div>
                    
                </div>
                
                <div class="row">

                    <div class="col col-md-12">
                        Descrição do Video:
                        <label class="input">
                            <i class="icon-append fa fa-pencil"></i>    
                            <?php echo $this->formElement($formPsqVideo->get('dsVideoPsq')); ?>
                        </label>
                    </div>

                </div>

                <div class="row">
                    <?php echo $this->formButton()->openTag($formPsqVideo->get('btnPesquisarVideo')); ?>
                    <?php echo '<i class="fa fa-search"></i>' . $formPsqVideo->get('btnPesquisarVideo')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>

                    <?php echo $this->formButton()->openTag($formPsqVideo->get('btnNovoVideo')); ?>
                    <?php echo '<i class="fa fa-plus"></i>' . $formPsqVideo->get('btnNovoVideo')->getLabel(); ?>
                    <?php echo $this->formButton()->closeTag(); ?>
                </div>
                <!-- end cut -->

            </div>

        </div>
        <!-- /BASIC FORM -->

        <div id="tableVideos"></div>

        <?php echo $this->form()->closeTag(); ?>

    <br />
    &nbsp;
    <br />
    &nbsp;

</div>